<?php
use Illuminate\Support\Facades\Route;
use Modules\Inventory\Controllers\{InventoryController,InventoryWorkflowController};
use Modules\Inventory\Controllers\InventoryMovementReportController;

Route::middleware(['web','auth','permission:inventory.index'])->prefix('vat-tu')->name('inventory.')->group(function(){
    Route::get('/',[InventoryController::class,'index'])->name('index'); Route::post('/',[InventoryController::class,'store'])->middleware('permission:inventory.create')->name('store'); Route::post('/nhap',[InventoryController::class,'import'])->middleware('permission:inventory.import')->name('import'); Route::patch('/{material}',[InventoryController::class,'update'])->middleware('permission:inventory.edit')->name('update'); Route::delete('/{material}',[InventoryController::class,'destroy'])->middleware('permission:inventory.delete')->name('destroy'); Route::post('/{material}/movement',[InventoryController::class,'movement'])->middleware('permission:inventory.edit')->name('movement');
    Route::get('/danh-muc-nganh',[InventoryWorkflowController::class,'category'])->name('category'); Route::post('/danh-muc-nganh',[InventoryWorkflowController::class,'categoryStore'])->middleware('permission:inventory.create')->name('category.store'); Route::post('/danh-muc-nganh/gan-tai-khoan',[InventoryWorkflowController::class,'assignCategory'])->middleware('permission:inventory.edit')->name('category.assign'); Route::patch('/danh-muc-nganh/{category}',[InventoryWorkflowController::class,'categoryUpdate'])->middleware('permission:inventory.edit')->name('category.update'); Route::delete('/danh-muc-nganh/{category}',[InventoryWorkflowController::class,'categoryDelete'])->middleware('permission:inventory.delete')->name('category.delete');
    Route::get('/cap-nhat',[InventoryWorkflowController::class,'assets'])->name('assets'); Route::post('/cap-nhat',[InventoryWorkflowController::class,'assetStore'])->middleware('permission:inventory.create')->name('assets.store'); Route::patch('/cap-nhat/{asset}',[InventoryWorkflowController::class,'assetUpdate'])->middleware('permission:inventory.edit')->name('assets.update'); Route::delete('/cap-nhat/{asset}',[InventoryWorkflowController::class,'assetDelete'])->middleware('permission:inventory.delete')->name('assets.delete');
    Route::get('/kho',[InventoryWorkflowController::class,'warehouse'])->name('warehouse'); Route::post('/kho',[InventoryWorkflowController::class,'warehouseStore'])->middleware('permission:inventory.create')->name('warehouse.store'); Route::post('/kho/ton',[InventoryWorkflowController::class,'warehouseItemStore'])->middleware('permission:inventory.edit')->name('warehouse.item.store');
    Route::get('/de-xuat',[InventoryWorkflowController::class,'proposals'])->name('proposals'); Route::post('/de-xuat',[InventoryWorkflowController::class,'proposalStore'])->middleware('permission:inventory.create')->name('proposals.store'); Route::patch('/de-xuat/{proposal}',[InventoryWorkflowController::class,'proposalDecide'])->middleware('permission:inventory.approve')->name('proposals.decide');
    Route::get('/phan-cong',[InventoryWorkflowController::class,'repairs'])->name('repairs'); Route::post('/phan-cong',[InventoryWorkflowController::class,'repairStore'])->middleware('permission:inventory.create')->name('repairs.store'); Route::patch('/phan-cong/{repair}',[InventoryWorkflowController::class,'repairComplete'])->middleware('permission:inventory.edit')->name('repairs.complete');
    Route::get('/dieu-dong',[InventoryWorkflowController::class,'transfers'])->name('transfers'); Route::post('/dieu-dong',[InventoryWorkflowController::class,'transferStore'])->middleware('permission:inventory.create')->name('transfers.store'); Route::patch('/dieu-dong/{transfer}',[InventoryWorkflowController::class,'transferDecide'])->middleware('permission:inventory.approve')->name('transfers.decide');
    Route::get('/thanh-ly',[InventoryWorkflowController::class,'liquidation'])->name('liquidation'); Route::get('/nhat-ky',[InventoryWorkflowController::class,'logs'])->name('logs'); Route::get('/nganh-cua-toi',[InventoryWorkflowController::class,'myCatalog'])->name('my-catalog'); Route::get('/tim-kiem',[InventoryWorkflowController::class,'search'])->name('search'); Route::get('/bao-cao',[InventoryWorkflowController::class,'reports'])->name('reports'); Route::get('/bao-cao/word',[InventoryWorkflowController::class,'reportWord'])->middleware('permission:inventory.export')->name('reports.word'); Route::get('/bao-cao/csv',[InventoryWorkflowController::class,'reportCsv'])->middleware('permission:inventory.export')->name('reports.csv'); Route::get('/mau-bao-cao',[InventoryWorkflowController::class,'templates'])->name('templates'); Route::post('/mau-bao-cao',[InventoryWorkflowController::class,'templateStore'])->middleware('permission:inventory.create')->name('templates.store');
    Route::get('/toa-nha/{building}',[InventoryWorkflowController::class,'building'])->name('building'); Route::get('/phong/{classroom}',[InventoryWorkflowController::class,'room'])->name('room'); Route::post('/phong/{classroom}/anh',[InventoryWorkflowController::class,'roomImageStore'])->middleware('permission:inventory.create')->name('room.images.store'); Route::delete('/phong-anh/{image}',[InventoryWorkflowController::class,'roomImageDelete'])->middleware('permission:inventory.delete')->name('room.images.delete'); Route::post('/phong/{classroom}/nguoi-dung',[InventoryWorkflowController::class,'roomUserStore'])->middleware('permission:inventory.edit')->name('room.users.store'); Route::delete('/phong-nguoi-dung/{roomUser}',[InventoryWorkflowController::class,'roomUserDelete'])->middleware('permission:inventory.edit')->name('room.users.delete');
});
Route::middleware(['web','auth','permission:inventory.index'])->prefix('vat-tu')->name('inventory.')->group(function(){Route::get('/bao-cao/di-chuyen',[InventoryMovementReportController::class,'index'])->name('movement-report');Route::get('/bao-cao/di-chuyen/csv',[InventoryMovementReportController::class,'csv'])->middleware('permission:inventory.export')->name('movement-report.csv');});
