@extends('layouts.admin')
@section('title','Duyệt đề')
@section('page-title','Duyệt đề')
@section('content')
<style>
    .essay-approval-shell { color:#1e293b; }
    .essay-approval-shell .bg-white.border.rounded-xl { border-color:#dbeafe; border-radius:1rem; box-shadow:0 8px 24px rgba(30,64,175,.07); }
    .essay-approval-shell .bg-blue-50 { background:#eff6ff !important; }
    .essay-approval-shell .bg-teal-50 { background:#eff6ff !important; border-color:#bfdbfe !important; }
    .essay-approval-shell .border-teal-200,
    .essay-approval-shell .border-teal-100 { border-color:#bfdbfe !important; }
    .essay-approval-shell .text-teal-900,
    .essay-approval-shell .text-teal-800,
    .essay-approval-shell .text-teal-700 { color:#1d4ed8 !important; }
    .essay-approval-shell button.bg-emerald-600,
    .essay-approval-shell button.bg-teal-600,
    .essay-approval-shell button.bg-teal-700,
    .essay-approval-shell button.bg-blue-600 { background:#2563eb !important; color:#fff !important; }
    .essay-approval-shell button.bg-amber-500 { background:#1d4ed8 !important; color:#fff !important; }
    .essay-approval-shell button:hover { filter:brightness(1.08); box-shadow:0 5px 12px rgba(37,99,235,.18); }
    .essay-approval-shell table thead { background:#eff6ff !important; }
    .essay-approval-shell input[type="checkbox"] { accent-color:#2563eb; }
    .essay-approval-shell .space-y-4 > .bg-white.border.rounded-xl { padding:1rem 1.1rem; transition:border-color .18s, box-shadow .18s; }
    .essay-approval-shell .space-y-4 > .bg-white.border.rounded-xl:hover { border-color:#93c5fd; box-shadow:0 10px 25px rgba(37,99,235,.1); }
    .essay-approval-shell .space-y-4 > .bg-white.border.rounded-xl h2 { color:#172033; font-size:1rem; }
</style>
<div class="essay-approval-shell">
@include('partials.module-menu', ['module' => 'exam'])
@if(auth()->user()?->hasAnyRole(['super-admin','system-manager','manager']))<div class="bg-white border rounded-xl p-3 mb-4 flex gap-2"><span class="font-medium">Cấp duyệt:</span><a class="px-3 py-1 rounded bg-slate-100" href="?stage=PENDING_DEPT">Khoa</a><a class="px-3 py-1 rounded bg-slate-100" href="?stage=PENDING_EXAM_OFFICE">Khảo thí</a><a class="px-3 py-1 rounded bg-slate-100" href="?stage=PENDING_BGH">BGH</a></div>@endif
<x-breadcrumb :items="[['title'=>'Đề thi tự luận','url'=>route('essay-exams.index')],['title'=>'Duyệt đề']]" />
<div class="flex justify-between items-center mb-5"><div><h1 class="text-2xl font-bold">Duyệt đề</h1><p class="text-sm text-slate-500">Đang ở cấp: {{ $stage }}. Bao gồm đề tự luận và ngân hàng trắc nghiệm LMS.</p></div><a href="{{ route('essay-exams.index') }}" class="text-blue-600">Đề của tôi</a></div>
@if(session('success'))<div class="mb-4 rounded-lg bg-emerald-50 text-emerald-800 px-4 py-3">{{ session('success') }}</div>@endif
<form class="bg-white border rounded-xl p-4 mb-4 grid md:grid-cols-4 gap-3"><select name="specialization_id" class="border rounded-lg px-3 py-2"><option value="">Tất cả ngành đào tạo</option>@foreach($specializations as $item)<option value="{{ $item->id }}" @selected(request('specialization_id')==$item->id)>{{ $item->code }} — {{ $item->name }}</option>@endforeach</select><select name="subject_id" class="border rounded-lg px-3 py-2"><option value="">Tất cả môn học</option>@foreach($subjects as $item)<option value="{{ $item->id }}" @selected(request('subject_id')==$item->id)>{{ $item->code }} — {{ $item->name }}</option>@endforeach</select><input name="teacher" value="{{ request('teacher') }}" placeholder="Tên hoặc tài khoản giáo viên" class="border rounded-lg px-3 py-2"><button class="px-4 py-2 rounded-lg bg-slate-800 text-white">Lọc</button></form>
@if($lmsBanks->isNotEmpty())<section class="mb-5 bg-teal-50 border border-teal-200 rounded-xl p-4"><div class="flex items-center justify-between mb-3"><div><h2 class="font-bold text-teal-900">Ngân hàng trắc nghiệm LMS</h2><p class="text-sm text-teal-700">Các ngân hàng đang ở cấp {{ $stage }}.</p></div><span class="px-2 py-1 rounded-full bg-white text-teal-800 text-xs font-semibold">{{ $lmsBanks->count() }} ngân hàng</span></div><form method="POST" action="{{ route('essay-exams.approval.lms-banks.bulk-approve') }}" class="mb-3 flex flex-wrap items-center gap-2">@csrf @foreach($lmsBanks as $bank)<label class="inline-flex items-center gap-1 rounded-lg bg-white border border-teal-100 px-2 py-1 text-xs"><input type="checkbox" name="bank_ids[]" value="{{ $bank->id }}">{{ $bank->title }}</label>@endforeach<button name="approve_all" value="1" class="px-3 py-2 rounded-lg bg-teal-700 text-white text-sm font-semibold">Duyệt tất cả</button><button class="px-3 py-2 rounded-lg bg-teal-600 text-white text-sm font-semibold">Duyệt đã chọn</button></form><div class="space-y-3">@foreach($lmsBanks as $bank)<div class="bg-white border border-teal-100 rounded-lg p-3 flex flex-wrap items-center justify-between gap-3"><div><div class="font-semibold text-slate-900">{{ $bank->title }}</div><div class="text-xs text-slate-500">{{ $bank->course?->title }} · {{ $bank->questions_count ?? $bank->questions->count() }} câu · {{ $bank->questions->groupBy('lms_lesson_id')->count() }} bài</div></div><form method="POST" action="{{ route('essay-exams.approval.lms-banks.approve', $bank) }}">@csrf<button class="px-3 py-2 rounded-lg bg-teal-600 text-white text-sm font-semibold">Duyệt ngân hàng trắc nghiệm</button></form></div>@endforeach</div></section>@endif
<div class="space-y-4">@forelse($exams as $exam)<div class="bg-white border rounded-xl p-5"><div class="flex flex-wrap justify-between gap-3"><div><h2 class="font-semibold text-lg">{{ $exam->code }} — {{ $exam->title }}</h2><p class="text-sm text-slate-500">{{ $exam->subject->code }} — {{ $exam->subject->name }} · {{ $exam->questions->where('paper_status',$stage)->groupBy('paper_number')->count() }} đề đang chờ</p><p class="text-sm text-slate-600">Giáo viên đề xuất: <b>{{ $exam->created_by_display_name ?: $exam->created_by_username }}</b></p></div><span class="px-2 py-1 rounded-full bg-amber-100 text-amber-800 text-xs">{{ $exam->status_label }}</span></div>
<form method="POST" action="{{ route('essay-exams.approve',$exam) }}">@csrf<input type="hidden" name="stage" value="{{ $stage }}"><details class="mt-3" open><summary class="cursor-pointer text-blue-600">Xem và chọn đề số để duyệt</summary><div class="mt-3 space-y-4">@foreach($exam->questions->where('paper_status',$stage)->groupBy('paper_number') as $paper => $questions)<section class="border rounded-lg overflow-hidden"><div class="px-4 py-3 bg-blue-50 border-b flex items-center justify-between"><div><b>Đề số {{ $paper }}</b><span class="text-sm text-slate-600"> — {{ $questions->count() }} câu · {{ number_format($questions->sum('points'),2,',','.') }} điểm</span></div><label class="text-sm"><input type="checkbox" name="paper_numbers[]" value="{{ $paper }}" checked> Chọn duyệt</label></div><div class="p-4 space-y-3">@foreach($questions as $q)<div class="border-l-2 border-slate-300 pl-3"><b>Câu {{ $q->question_number }} ({{ $q->points }} điểm)</b><div class="mt-1 whitespace-pre-line"><span class="font-medium">Câu hỏi:</span> {{ $q->content }}</div><div class="mt-1 text-sm text-slate-600 whitespace-pre-line"><span class="font-medium">Đáp án / barem:</span> {{ $q->answer ?: 'Chưa nhập' }}</div></div>@endforeach</div></section>@endforeach</div></details><div class="flex flex-wrap gap-2 mt-4"><button class="px-4 py-2 rounded-lg bg-emerald-600 text-white">Duyệt các đề đã chọn</button></form><form method="POST" action="{{ route('essay-exams.return',$exam) }}" class="flex gap-2">@csrf<input name="return_note" required placeholder="Lý do trả lại" class="border rounded-lg px-3 py-2"><button class="px-4 py-2 rounded-lg bg-amber-500 text-white">Trả lại</button></form></div></div>@empty<div class="bg-white border rounded-xl p-10 text-center text-slate-500">Không có đề đang chờ ở cấp này.</div>@endforelse</div>
</div>
@endsection
