@extends('layouts.admin')
@section('title','Ngân hàng đề tự luận') @section('page-title','Ngân hàng đề tự luận') @section('content')
@include('partials.module-menu', ['module' => 'exam'])
<h1 class="text-2xl font-bold mb-5">Ngân hàng đề tự luận</h1>
<form class="bg-white border rounded-xl p-4 mb-4 grid md:grid-cols-5 gap-2"><input name="search" value="{{ request('search') }}" placeholder="Tìm mã đề, tiêu đề..." class="border rounded-lg px-3 py-2"><input name="academic_year" value="{{ request('academic_year') }}" placeholder="Năm học" class="border rounded-lg px-3 py-2"><input name="semester" value="{{ request('semester') }}" placeholder="Học kỳ" class="border rounded-lg px-3 py-2"><input name="difficulty" value="{{ request('difficulty') }}" placeholder="Mức độ" class="border rounded-lg px-3 py-2"><input name="exam_type" value="{{ request('exam_type') }}" placeholder="Dạng đề" class="border rounded-lg px-3 py-2"><button class="md:col-span-5 px-4 py-2 rounded-lg bg-blue-600 text-white">Lọc ngân hàng</button></form>
@if($exams->count())
@foreach($exams->groupBy(fn($e) => $e->subject->specialization_id ?? 0) as $specializationExams)
<section class="bg-white border rounded-xl overflow-hidden mb-5"><div class="px-4 py-3 bg-blue-50 font-bold">Ngành đào tạo: {{ optional($specializationExams->first()->subject->specialization)->code ?? 'Chưa phân ngành' }} — {{ optional($specializationExams->first()->subject->specialization)->name ?? '' }}</div><div class="overflow-x-auto"><table class="w-full min-w-[1100px] text-sm"><thead class="bg-slate-100"><tr><th class="p-3 text-left">Mã đề</th><th class="p-3 text-left">Môn</th><th class="p-3">Năm học</th><th class="p-3">Học kỳ</th><th class="p-3">Mức độ</th><th class="p-3">Dạng đề</th><th class="p-3">Đề số</th><th class="p-3">QR khóa</th><th class="p-3">Trạng thái</th></tr></thead><tbody class="divide-y">
@foreach($specializationExams as $exam) @foreach($exam->questions->where('paper_status','APPROVED')->groupBy('paper_number') as $paper=>$questions) @php($qrValue=($exam->approval_qr ?: 'QR-EXAM-'.$exam->id).'-D'.str_pad($paper,2,'0',STR_PAD_LEFT))<tr><td class="p-3 font-semibold">{{ $exam->code }}-D{{ str_pad($paper,2,'0',STR_PAD_LEFT) }}</td><td class="p-3">{{ $exam->subject->name ?? '—' }}</td><td class="p-3 text-center">{{ $exam->academic_year ?? '—' }}</td><td class="p-3 text-center">{{ $exam->semester ?? '—' }}</td><td class="p-3 text-center">{{ $exam->difficulty ?? '—' }}</td><td class="p-3 text-center">{{ $exam->exam_type ?? 'Tự luận' }}</td><td class="p-3 text-center font-bold">{{ $paper }}</td><td class="p-3 text-center"><img class="w-20 h-20 mx-auto border rounded" alt="QR khóa đề" src="https://api.qrserver.com/v1/create-qr-code/?size=120x120&data={{ urlencode($qrValue) }}"></td><td class="p-3 text-center"><span class="px-2 py-1 rounded bg-emerald-100 text-emerald-800 text-xs">Đã khóa</span></td></tr>@endforeach @endforeach
</tbody></table></div></section>
@endforeach
@else<div class="bg-white border rounded-xl p-10 text-center text-slate-500">Ngân hàng chưa có đề đã duyệt.</div>@endif
<div class="mt-4">{{ $exams->links() }}</div>
@endsection
