@extends('layouts.admin')
@section('title','Kho đề đã sử dụng')
@section('page-title','Kho đề đã sử dụng')
@section('content')
@include('partials.module-menu', ['module' => 'exam'])
<x-breadcrumb :items="[['title'=>'Đề thi tự luận','url'=>route('essay-exams.index')],['title'=>'Kho đề đã sử dụng']]" />
<div class="flex justify-between items-center mb-5"><div><h1 class="text-2xl font-bold">Kho đề đã sử dụng (đã in)</h1><p class="text-sm text-slate-500">Tra cứu bằng mã đề, mã bốc đề hoặc mã QR.</p></div><a href="{{ route('essay-exams.draw') }}" class="text-blue-600">Rút đề / tra phiếu</a></div>
<form class="bg-white border rounded-xl p-4 mb-4 flex gap-2"><input name="q" value="{{ request('q') }}" class="border rounded-lg px-3 py-2 flex-1" placeholder="Nhập mã đề, mã bốc đề hoặc QR..."><button class="px-4 py-2 rounded-lg bg-slate-800 text-white">Tìm kiếm</button></form>
<div class="bg-white border rounded-xl overflow-hidden"><div class="overflow-x-auto"><table class="w-full min-w-[900px] table-fixed text-sm"><colgroup><col class="w-[15%]"><col class="w-[16%]"><col class="w-[22%]"><col class="w-[14%]"><col class="w-[18%]"><col class="w-[15%]"></colgroup><thead class="bg-slate-100"><tr><th class="p-3 text-left whitespace-nowrap">Mã đề</th><th class="p-3 text-left whitespace-nowrap">Ngày rút</th><th class="p-3 text-left">Lớp thi / tên lớp</th><th class="p-3 text-left whitespace-nowrap">Ngày thi</th><th class="p-3 text-left whitespace-nowrap">Mã bốc đề</th><th class="p-3 text-left whitespace-nowrap">QR</th></tr></thead><tbody class="divide-y">@forelse($draws as $draw)<tr><td class="p-3 font-semibold whitespace-nowrap">{{ $draw->exam->code }}</td><td class="p-3 whitespace-nowrap">{{ $draw->drawn_at?->format('d/m/Y H:i') }}</td><td class="p-3 truncate" title="{{ $draw->class_name }}">{{ $draw->class_name }}</td><td class="p-3 whitespace-nowrap">{{ $draw->exam_date?->format('d/m/Y') }}</td><td class="p-3 font-mono whitespace-nowrap">{{ $draw->draw_code }}</td><td class="p-3 font-mono whitespace-nowrap">{{ $draw->qr_code }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">Chưa có đề đã sử dụng.</td></tr>@endforelse</tbody></table></div></div><div class="mt-4">{{ $draws->links() }}</div>
@endsection
