# Scheduler service at docker-compose.yml on https://github.com/tho076/cdhc2-infra#
services:
  qlhl-scheduler:
    image: qlhl-cdhc2:0.1
    command: ["php", "artisan", "schedule:work"]
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./.env:/var/www/.env
    environment:
      - APP_ENV=production
    restart: unless-stopped
