<?php
namespace Modules\LeaveManagement\Support;
use App\Models\User;
use App\Support\ManagerUnitScope;
use Illuminate\Database\Eloquent\Builder;
final class LeaveAccess {
 public const QUAN_LUC='QUAN_LUC'; public const CO_QUAN_CAN_BO='CO_QUAN_CAN_BO'; public const CO_QUAN_QUAN_LY=self::CO_QUAN_CAN_BO;
 public static function isScoped(?User $user):bool{return ManagerUnitScope::isScoped($user);} public static function unitIds(?User $user):array{return ManagerUnitScope::managedUnitIds($user);} public static function canAccessUnit(int $unitId,?User $user):bool{return ManagerUnitScope::canAccessUnit($unitId,$user);}
 public static function personnel(Builder $query,?User $user):Builder{if(self::isScoped($user))$query->whereIn('unit_id',self::unitIds($user));return $query;} public static function requests(Builder $query,?User $user):Builder{if(self::isScoped($user))$query->where(fn($q)=>$q->whereHas('personnel',fn($p)=>$p->whereIn('unit_id',self::unitIds($user)))->orWhereIn('unit_id',self::unitIds($user)));return $query;}
 public static function ensurePersonnel(int $personnelId,?User $user):void{if(self::isScoped($user)&&!in_array((int)\Modules\LeaveManagement\Models\LeavePersonnel::whereKey($personnelId)->value('unit_id'),self::unitIds($user),true))abort(403,'Bạn chỉ được quản lý nhân sự thuộc đơn vị được phân công.');}
 public static function roleKeys(?User $user):array{if(!$user)return [];return collect(method_exists($user,'getRoleNames')?$user->getRoleNames()->all():[])->map(fn($role)=>(string)preg_replace('/[^a-z0-9]+/','_',trim((string)\Illuminate\Support\Str::ascii(\Illuminate\Support\Str::lower($role)),'_')))->values()->all();}
 public static function isQuanLuc(?User $user):bool{return $user && ($user->isSuperAdmin() || $user->hasRole(\App\Support\PermissionCheck::LEAVE_AGENCY_ROLE) || in_array('quan_luc',self::roleKeys($user),true));}
 public static function agencyForObject(?string $objectType):string{ $value=mb_strtolower(trim((string)$objectType),'UTF-8'); $value=(string)\Illuminate\Support\Str::ascii($value); $value=(string)preg_replace('/[^a-z0-9]+/','_',trim($value,'_')); if(in_array($value,['sq','si_quan','cb','can_bo','canbo','cong_chuc_quoc_phong','cnqp','vcqp'],true))return self::CO_QUAN_CAN_BO; return self::QUAN_LUC; }
 public static function isDepartmentUnitName(?string $unitName):bool{ $value=mb_strtolower(trim((string)$unitName),'UTF-8'); $value=(string)\Illuminate\Support\Str::ascii($value); return (bool)preg_match('/(^|\s)(khoa|phong|ban)(\s|$)/', $value); }
 public static function agencyForUser(?User $user):?string{if(!$user||$user->isSuperAdmin())return null;if(self::isQuanLuc($user))return self::QUAN_LUC;$roles=self::roleKeys($user);if(in_array('co_quan_can_bo',$roles,true)||in_array('cadres_agency_manager',$roles,true))return self::CO_QUAN_CAN_BO;return self::canApprove($user)?self::CO_QUAN_CAN_BO:null;}
 public static function canApprove(?User $user):bool{return $user && (\App\Support\PermissionCheck::can($user,'leave-management.approve')||\App\Support\PermissionCheck::can($user,'leave-management.approvals.approve'));}
 public static function canHandleAgency(string $agency,?User $user):bool{return $user?->isSuperAdmin()||self::agencyForUser($user)===$agency;}
 public static function commanderUserIds():array{$people=\Modules\LeaveManagement\Models\LeavePersonnel::withoutGlobalScopes()->where('active',true)->get(['user_id','name','position'])->filter(fn($person)=>\Illuminate\Support\Str::contains(\Illuminate\Support\Str::lower(\Illuminate\Support\Str::ascii((string)$person->position)),'chi huy'));$ids=$people->pluck('user_id')->filter()->unique()->values();$names=$people->pluck('name')->filter()->map(fn($name)=>trim((string)$name))->unique()->values();return \App\Models\User::where('status',1)->where(function($query)use($ids,$names){if($ids->isNotEmpty())$query->whereIn('id',$ids->all());if($names->isNotEmpty())$query->orWhereIn('name',$names->all());})->pluck('id')->values()->all();}
 public static function isCommanderAccount(?User $user):bool{if(!$user||$user->status!=1)return false;$roles=method_exists($user,'getRoleNames')?$user->getRoleNames()->all():[];foreach($roles as $role){$key=(string)preg_replace('/[^a-z0-9]+/','_',trim((string)\Illuminate\Support\Str::ascii(\Illuminate\Support\Str::lower($role)),'_'));if(in_array($key,['agency_commander','chi_huy_co_quan','chi_huy_don_vi'],true)||str_contains($key,'chi_huy_co_quan')||str_contains($key,'agency_commander'))return true;}return $user->hasRole(\App\Support\RoleCatalog::LEAVE_COMMANDER);}
 public static function isCommanderPersonnel(?string $position):bool{$key=(string)\Illuminate\Support\Str::ascii(\Illuminate\Support\Str::lower((string)$position));return \Illuminate\Support\Str::contains($key,['chi huy co quan','chi huy don vi','truong phong','pho truong phong','truong ban','pho truong ban','truong khoa','pho truong khoa','chu nhiem khoa','pho chu nhiem khoa','truong bo mon','pho truong bo mon','chu nhiem bo mon','pho chu nhiem bo mon']);}
 public static function commanderForUnit(?int $unitId):?User{if(!$unitId)return null;$account=User::where('status',1)->where('unit_id',$unitId)->get()->first(fn($user)=>self::isCommanderAccount($user));if($account)return $account;return \Modules\LeaveManagement\Models\LeavePersonnel::withoutGlobalScopes()->with('user')->where('active',true)->where('unit_id',$unitId)->get()->first(fn($person)=>self::isCommanderPersonnel($person->position)&&$person->user&&$person->user->status==1)?->user;}
 public static function personnelForUser(?User $user):?\Modules\LeaveManagement\Models\LeavePersonnel{if(!$user)return null;return \Modules\LeaveManagement\Models\LeavePersonnel::withoutGlobalScopes()->with(['unitRelation','leaveClass','commander'])->where('active',true)->where('user_id',$user->id)->first();}
}
