<?php
use Illuminate\Support\Facades\Route;
use Modules\LeaveManagement\Controllers\{LeaveMailController,LeaveManagementController,LeaveUnitController,LeaveWorkflowController};
use Modules\LeaveManagement\Controllers\LeaveRequestEditController;
use Modules\LeaveManagement\Controllers\{LeaveProposalController,LeaveDecisionController};
Route::middleware(['web','auth','permission:leave-management.access.index|leave-management.index'])->prefix('quan-ly-phep')->name('leave-management.')->group(function(){
    Route::get('/bao-cao/word',[LeaveWorkflowController::class,'reportWordFixed'])->middleware('permission:leave-management.export')->name('reports.word.compat');
    Route::post('/dia-phuong/reset',[LeaveWorkflowController::class,'localityReset'])->middleware('permission:leave-management.delete')->name('localities.reset');
    Route::get('/cong',[LeaveManagementController::class,'portal'])->name('portal');
    Route::get('/',[LeaveManagementController::class,'index'])->name('index'); Route::post('/personnel',[LeaveManagementController::class,'personnel'])->middleware('permission:leave-management.create|leave-management.personnel.create')->name('personnel.store'); Route::post('/personnel/import',[LeaveManagementController::class,'importPersonnel'])->middleware('permission:leave-management.import')->name('personnel.import'); Route::post('/requests',[LeaveProposalController::class,'store'])->name('requests.store'); Route::patch('/requests/{leaveRequest}/decide',[LeaveDecisionController::class,'decide'])->name('requests.decide'); Route::patch('/requests/{leaveRequest}/cancel',[LeaveManagementController::class,'cancel'])->middleware('permission:leave-management.edit|leave-management.requests.edit')->name('requests.cancel');
    Route::get('/quan-nhan',[LeaveWorkflowController::class,'personnel'])->name('personnel'); Route::patch('/quan-nhan/{personnel}',[LeaveWorkflowController::class,'personnelUpdate'])->middleware('permission:leave-management.edit')->name('personnel.update'); Route::delete('/quan-nhan/{personnel}',[LeaveWorkflowController::class,'personnelDelete'])->middleware('permission:leave-management.delete')->name('personnel.delete'); Route::get('/danh-sach',[LeaveWorkflowController::class,'directory'])->name('directory');
    Route::get('/don-vi',[LeaveUnitController::class,'index'])->name('units'); Route::post('/don-vi',[LeaveUnitController::class,'store'])->middleware('permission:leave-management.create')->name('units.store'); Route::patch('/don-vi/{unit}',[LeaveUnitController::class,'update'])->middleware('permission:leave-management.edit')->name('units.update'); Route::delete('/don-vi/{unit}',[LeaveUnitController::class,'delete'])->middleware('permission:leave-management.delete')->name('units.delete'); Route::post('/don-vi/import',[LeaveUnitController::class,'import'])->middleware('permission:leave-management.import')->name('units.import'); Route::post('/don-vi/seed',[LeaveUnitController::class,'seed'])->middleware('permission:leave-management.create')->name('units.seed');
    Route::get('/de-xuat',[LeaveWorkflowController::class,'requests'])->name('requests'); Route::get('/requests/{leaveRequest}/print',[LeaveWorkflowController::class,'printRequest'])->name('requests.print'); Route::get('/requests/{leaveRequest}',[LeaveWorkflowController::class,'requestDetail'])->name('requests.show'); Route::get('/duyet',[LeaveWorkflowController::class,'approvals'])->name('approvals'); Route::get('/lop',[LeaveWorkflowController::class,'classes'])->name('classes'); Route::post('/lop/dong-bo',[LeaveWorkflowController::class,'syncClasses'])->middleware('permission:leave-management.create|leave-management.edit')->name('classes.sync'); Route::post('/lop',[LeaveWorkflowController::class,'classStore'])->middleware('permission:leave-management.create')->name('classes.store'); Route::delete('/lop/{class}',[LeaveWorkflowController::class,'classDelete'])->middleware('permission:leave-management.delete')->name('classes.delete');
    Route::get('/quy-dinh',[LeaveWorkflowController::class,'regulations'])->name('regulations'); Route::post('/quy-dinh',[LeaveWorkflowController::class,'regulationStore'])->middleware('permission:leave-management.create')->name('regulations.store'); Route::patch('/quy-dinh/{regulation}',[LeaveWorkflowController::class,'regulationUpdate'])->middleware('permission:leave-management.edit')->name('regulations.update'); Route::delete('/quy-dinh/{regulation}',[LeaveWorkflowController::class,'regulationDelete'])->middleware('permission:leave-management.delete')->name('regulations.delete');
    Route::get('/dia-phuong',[LeaveWorkflowController::class,'localities'])->name('localities'); Route::post('/dia-phuong',[LeaveWorkflowController::class,'localityStore'])->middleware('permission:leave-management.create')->name('localities.store'); Route::post('/dia-phuong/import',[LeaveWorkflowController::class,'localityImport'])->middleware('permission:leave-management.import')->name('localities.import'); Route::patch('/dia-phuong/{locality}',[LeaveWorkflowController::class,'localityUpdate'])->middleware('permission:leave-management.edit')->name('localities.update'); Route::delete('/dia-phuong/{locality}',[LeaveWorkflowController::class,'localityDelete'])->middleware('permission:leave-management.delete')->name('localities.delete');
    Route::get('/chuc-vu',[LeaveWorkflowController::class,'positions'])->name('positions'); Route::post('/chuc-vu',[LeaveWorkflowController::class,'positionStore'])->middleware('permission:leave-management.create')->name('positions.store'); Route::patch('/chuc-vu/{position}',[LeaveWorkflowController::class,'positionUpdate'])->middleware('permission:leave-management.edit')->name('positions.update'); Route::delete('/chuc-vu/{position}',[LeaveWorkflowController::class,'positionDelete'])->middleware('permission:leave-management.delete')->name('positions.delete');
    Route::get('/dot-nghi',[LeaveWorkflowController::class,'batches'])->name('batches'); Route::post('/dot-nghi',[LeaveWorkflowController::class,'batchStore'])->middleware('permission:leave-management.create')->name('batches.store'); Route::patch('/dot-nghi/{batch}',[LeaveWorkflowController::class,'batchUpdate'])->middleware('permission:leave-management.edit')->name('batches.update'); Route::delete('/dot-nghi/{batch}',[LeaveWorkflowController::class,'batchDelete'])->middleware('permission:leave-management.delete')->name('batches.delete'); Route::get('/luu-tru',[LeaveWorkflowController::class,'records'])->name('records'); Route::patch('/luu-tru/{record}/archive',[LeaveWorkflowController::class,'archiveRecord'])->middleware('permission:leave-management.edit')->name('records.archive'); Route::get('/nhat-ky',[LeaveWorkflowController::class,'auditLogs'])->name('audit'); Route::get('/thong-bao',[LeaveWorkflowController::class,'alerts'])->name('alerts'); Route::patch('/thong-bao/{alert}/read',[LeaveWorkflowController::class,'alertRead'])->name('alerts.read');
    Route::get('/bao-cao',[LeaveWorkflowController::class,'reports'])->name('reports'); Route::get('/bao-cao/word',[LeaveWorkflowController::class,'reportWord'])->middleware('permission:leave-management.export')->name('reports.word'); Route::get('/bao-cao/csv',[LeaveWorkflowController::class,'reportCsv'])->middleware('permission:leave-management.export')->name('reports.csv'); Route::get('/mail',[LeaveMailController::class,'index'])->name('mail'); Route::post('/mail/cau-hinh',[LeaveMailController::class,'save'])->middleware('permission:leave-management.edit')->name('mail.save'); Route::post('/mail/test',[LeaveMailController::class,'test'])->middleware('permission:leave-management.edit')->name('mail.test');
    Route::get('/bao-cao/word-safe',[LeaveWorkflowController::class,'reportWordFixed'])->middleware('permission:leave-management.export')->name('reports.word.safe');
});
Route::middleware(['web','auth','permission:leave-management.edit|leave-management.approve|leave-management.approvals.approve'])->prefix('quan-ly-phep')->name('leave-management.')->patch('/requests/{leaveRequest}',[LeaveRequestEditController::class,'update'])->name('requests.update');
Route::middleware(['web','auth','permission:leave-management.show'])->prefix('quan-ly-phep')->name('leave-management.')->get('/quy-dinh-chi-tiet',[\Modules\LeaveManagement\Controllers\LeaveRegulationDashboardController::class,'index'])->name('regulations.dashboard');
