@extends('layouts.admin')
@section('title', $title)
@section('page-title', $title)
@section('content')
@include('partials.module-menu', ['module' => 'inventory'])
<div class="space-y-5">
    <div class="flex flex-col gap-3 border-b border-slate-200 pb-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="mb-1 text-xs font-bold uppercase tracking-[.18em] text-indigo-600">Quản trị phân hệ</p><h1 class="text-2xl font-extrabold tracking-tight text-slate-900">{{ $title }}</h1><p class="mt-1 text-sm text-slate-500">Thực hiện nghiệp vụ nhanh, rõ ràng và có kiểm soát.</p></div><a href="{{ route('inventory.index') }}" class="inline-flex items-center gap-2 self-start rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm transition hover:border-indigo-300 hover:bg-indigo-50 hover:text-indigo-700 sm:self-auto"><i class="bi bi-arrow-left"></i> Tổng quan</a></div>
    @if(session('success'))<div class="rounded bg-green-100 p-3 text-green-800">{{ session('success') }}</div>@endif
    @if($section === 'category')
        <form method="POST" action="{{ route('inventory.category.assign') }}" class="mb-3 flex flex-wrap gap-2 rounded border bg-white p-3">@csrf<select name="user_id" required class="rounded border p-2"><option value="">Tài khoản</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select><select name="category_id" required class="rounded border p-2"><option value="">Ngành vật tư</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->code }} — {{ $category->name }}</option>@endforeach</select><button class="rounded bg-slate-700 px-3 py-2 text-white">Gán ngành</button></form>
        <form method="POST" action="{{ route('inventory.category.store') }}" class="grid gap-2 rounded border bg-white p-4 md:grid-cols-4">@csrf<select name="parent_id" class="rounded border p-2"><option value="">Ngành gốc</option>@foreach($parents as $parent)<option value="{{ $parent->id }}">{{ $parent->code }} — {{ $parent->name }}</option>@endforeach</select><input name="code" required placeholder="Mã ngành" class="rounded border p-2"><input name="name" required placeholder="Tên ngành vật tư" class="rounded border p-2"><textarea name="description" placeholder="Mô tả" class="rounded border p-2 md:col-span-4"></textarea><button class="rounded bg-blue-600 px-4 py-2 text-white">Thêm danh mục</button></form><div class="rounded border bg-white p-4">@foreach($categories as $item)<div class="flex items-center justify-between gap-3 border-b p-3"><span>{{ $item->parent?->code ? $item->parent->code.' / ' : '' }}{{ $item->code }} — {{ $item->name }} ({{ $item->materials_count }} vật tư)</span><div class="flex gap-2"><details><summary class="cursor-pointer text-blue-600">Sửa</summary><form method="POST" action="{{ route('inventory.category.update',$item) }}" class="mt-2 flex gap-1">@csrf @method('PATCH')<input name="code" value="{{ $item->code }}" class="w-24 rounded border p-1"><input name="name" value="{{ $item->name }}" class="rounded border p-1"><button class="rounded bg-blue-600 px-2 py-1 text-white">Lưu</button></form></details>@if($item->materials_count===0 && $item->children()->count()===0)<form method="POST" action="{{ route('inventory.category.delete',$item) }}">@csrf @method('DELETE')<button class="text-red-600">Xóa</button></form>@endif</div></div>@endforeach</div>
    @elseif($section === 'warehouse')
        <form method="POST" action="{{ route('inventory.warehouse.store') }}" class="grid gap-2 rounded border bg-white p-4 md:grid-cols-4">@csrf<input name="code" required placeholder="Mã kho" class="rounded border p-2"><input name="name" required placeholder="Tên kho" class="rounded border p-2"><input name="location" placeholder="Vị trí" class="rounded border p-2"><select name="manager_id" class="rounded border p-2"><option value="">Thủ kho</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select><button class="rounded bg-blue-600 px-4 py-2 text-white md:col-span-4">Thêm kho</button></form>
        @foreach($warehouses as $warehouse)<div class="rounded border bg-white p-4"><div class="mb-3 flex justify-between"><h2 class="font-semibold">{{ $warehouse->code }} — {{ $warehouse->name }}</h2><span>{{ $warehouse->manager?->name }}</span></div><form method="POST" action="{{ route('inventory.warehouse.item.store') }}" class="grid gap-2 md:grid-cols-6">@csrf<input type="hidden" name="warehouse_id" value="{{ $warehouse->id }}"><select name="material_id" class="rounded border p-2"><option value="">Vật tư</option>@foreach($materials as $material)<option value="{{ $material->id }}">{{ $material->code }} — {{ $material->name }}</option>@endforeach</select><input name="code" required placeholder="Mã tồn" class="rounded border p-2"><input name="name" required placeholder="Tên hàng" class="rounded border p-2"><input name="quantity" type="number" min="0" step=".01" value="0" class="rounded border p-2"><input name="minimum_quantity" type="number" min="0" step=".01" value="0" placeholder="Tối thiểu" class="rounded border p-2"><button class="rounded bg-blue-600 px-3 py-2 text-white">Cập nhật tồn</button></form><div class="mt-3">@forelse($warehouse->items as $item)<div class="flex justify-between border-t py-2"><span>{{ $item->code }} — {{ $item->name }}</span><span class="{{ $item->quantity <= $item->minimum_quantity ? 'font-semibold text-red-600' : '' }}">{{ $item->quantity }} {{ $item->unit }}</span></div>@empty<span class="text-slate-500">Kho chưa có mặt hàng.</span>@endforelse</div></div>@endforeach
    @elseif($section === 'assets')
        @include('inventory::partials.assets', ['assets' => $assets, 'materials' => $materials, 'classrooms' => $classrooms])
    @elseif($section === 'proposals' || $section === 'liquidation')
        @if($section === 'proposals')<form method="POST" action="{{ route('inventory.proposals.store') }}" class="grid gap-2 rounded border bg-white p-4 md:grid-cols-3">@csrf<select name="type" class="rounded border p-2"><option value="PURCHASE">Mua/cấp phát</option><option value="REPAIR">Sửa chữa</option><option value="RECALL">Thu hồi</option><option value="LIQUIDATION">Thanh lý</option></select><input name="title" required placeholder="Tiêu đề đề xuất" class="rounded border p-2"><select name="unit_id" class="rounded border p-2"><option value="">Đơn vị</option>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->name }}</option>@endforeach</select><select name="asset_id" class="rounded border p-2"><option value="">Tài sản liên quan</option>@foreach($assets as $asset)<option value="{{ $asset->id }}">{{ $asset->asset_code }} — {{ $asset->name }}</option>@endforeach</select><select name="material_id" class="rounded border p-2"><option value="">Vật tư liên quan</option>@foreach($materials as $material)<option value="{{ $material->id }}">{{ $material->code }} — {{ $material->name }}</option>@endforeach</select><input name="quantity" type="number" min=".01" step=".01" value="1" class="rounded border p-2"><textarea name="description" placeholder="Nội dung" class="rounded border p-2 md:col-span-3"></textarea><button class="rounded bg-blue-600 px-4 py-2 text-white">Tạo đề xuất</button></form>@else<form method="POST" action="{{ route('inventory.proposals.store') }}" class="grid gap-2 rounded border bg-white p-4 md:grid-cols-3">@csrf<input type="hidden" name="type" value="LIQUIDATION"><input name="title" required placeholder="Tiêu đề thanh lý" class="rounded border p-2"><select name="unit_id" class="rounded border p-2"><option value="">Đơn vị</option>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->name }}</option>@endforeach</select><select name="asset_id" class="rounded border p-2"><option value="">Tài sản thanh lý</option>@foreach($assets as $asset)<option value="{{ $asset->id }}">{{ $asset->asset_code }} — {{ $asset->name }}</option>@endforeach</select><textarea name="description" placeholder="Lý do thanh lý" class="rounded border p-2 md:col-span-3"></textarea><button class="rounded bg-blue-600 px-4 py-2 text-white">Tạo hồ sơ thanh lý</button></form>@endif
        @include('inventory::partials.proposals')
    @elseif($section === 'repairs')
        <form method="POST" action="{{ route('inventory.repairs.store') }}" class="grid gap-2 rounded border bg-white p-4 md:grid-cols-3">@csrf<select name="asset_id" required class="rounded border p-2"><option value="">Tài sản cần sửa</option>@foreach($assets as $asset)<option value="{{ $asset->id }}">{{ $asset->asset_code }} — {{ $asset->name }}</option>@endforeach</select><select name="assigned_to" class="rounded border p-2"><option value="">Phân công người sửa</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select><input name="cost" type="number" min="0" step=".01" placeholder="Chi phí dự kiến" class="rounded border p-2"><textarea name="content" required placeholder="Nội dung sửa chữa" class="rounded border p-2 md:col-span-3"></textarea><button class="rounded bg-blue-600 px-4 py-2 text-white">Ghi nhận/phân công</button></form><div class="rounded border bg-white p-4">@foreach($repairs as $repair)<div class="flex justify-between border-b p-3"><span>{{ $repair->asset?->asset_code }} — {{ $repair->content }}</span><span>{{ $repair->status }} @if(in_array($repair->status,['OPEN','ASSIGNED']))<form class="inline" method="POST" action="{{ route('inventory.repairs.complete',$repair) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="COMPLETED"><button class="rounded bg-green-600 px-2 py-1 text-white">Hoàn tất</button></form>@endif</span></div>@endforeach</div>
    @elseif($section === 'transfers')
        <form method="POST" action="{{ route('inventory.transfers.store') }}" class="grid gap-2 rounded border bg-white p-4 md:grid-cols-4">@csrf<select name="asset_id" required class="rounded border p-2"><option value="">Chọn tài sản</option>@foreach($assets as $asset)<option value="{{ $asset->id }}">{{ $asset->asset_code }} — {{ $asset->name }}</option>@endforeach</select><select name="type" class="rounded border p-2"><option value="TRANSFER">Điều động</option><option value="RECALL">Thu hồi</option></select><select name="from_classroom_id" class="rounded border p-2"><option value="">Phòng đi</option>@foreach($classrooms as $room)<option value="{{ $room->id }}">{{ $room->name }}</option>@endforeach</select><select name="to_classroom_id" class="rounded border p-2"><option value="">Phòng đến</option>@foreach($classrooms as $room)<option value="{{ $room->id }}">{{ $room->name }}</option>@endforeach</select><textarea name="reason" placeholder="Lý do" class="rounded border p-2 md:col-span-4"></textarea><button class="rounded bg-blue-600 px-4 py-2 text-white md:col-span-4">Tạo phiếu</button></form><div class="rounded border bg-white p-4">@foreach($transfers as $transfer)<div class="flex justify-between border-b p-3"><span>{{ $transfer->asset?->asset_code }} — {{ $transfer->type }}</span><span>{{ $transfer->fromClassroom?->name }} → {{ $transfer->toClassroom?->name }} — {{ $transfer->status }}</span></div>@endforeach</div>
    @elseif($section === 'logs')
        @include('inventory::partials.audit-logs', ['auditLogs' => $auditLogs])
        @include('inventory::partials.broken-logs', ['brokenLogs' => $brokenLogs])
        <div class="grid gap-4 lg:grid-cols-3"><div class="overflow-x-auto rounded border bg-white lg:col-span-2"><h2 class="p-3 font-semibold">Nhập / xuất vật tư</h2><table class="w-full text-left text-sm"><thead class="bg-slate-100"><tr><th class="p-3">Thời gian</th><th class="p-3">Vật tư</th><th class="p-3">Loại</th><th class="p-3">Số lượng</th><th class="p-3">Người thực hiện</th></tr></thead><tbody>@foreach($logs as $log)<tr class="border-t"><td class="p-3">{{ $log->created_at?->format('d/m/Y H:i') }}</td><td class="p-3">{{ $log->material?->code }} — {{ $log->material?->name }}</td><td class="p-3">{{ $log->type }}</td><td class="p-3">{{ $log->quantity }}</td><td class="p-3">{{ $log->user?->name }}</td></tr>@endforeach</tbody></table><div class="p-3">{{ $logs->links() }}</div></div><div class="space-y-4"><div class="rounded border bg-white p-3"><h2 class="font-semibold">Điều động / thu hồi</h2>@foreach($transferLogs as $item)<div class="border-b p-2 text-sm">{{ $item->asset?->asset_code }} — {{ $item->type }} — {{ $item->status }}</div>@endforeach</div><div class="rounded border bg-white p-3"><h2 class="font-semibold">Sửa chữa / đề xuất</h2>@foreach($repairLogs as $item)<div class="border-b p-2 text-sm">{{ $item->asset?->asset_code }} — {{ $item->status }}</div>@endforeach @foreach($proposalLogs as $item)<div class="border-b p-2 text-sm">#{{ $item->id }} — {{ $item->type }} — {{ $item->status }}</div>@endforeach</div></div></div>
    @elseif($section === 'my-catalog')
        <div class="rounded border bg-white p-4">@foreach($categories as $item)<div class="flex justify-between border-b p-3"><span>{{ $item->code }} — {{ $item->name }}</span><span>{{ $item->materials_count }} vật tư</span></div>@endforeach</div>
    @elseif($section === 'building')
        <div class="rounded border bg-white p-4">@foreach($classrooms as $room)<a class="flex justify-between border-b p-3 hover:bg-slate-50" href="{{ route('inventory.room',$room) }}"><span>{{ $room->name }}</span><span>{{ $room->inventory_count }} tài sản</span></a>@endforeach</div>
    @elseif($section === 'room')
        @include('inventory::partials.room-details', ['classroom'=>$classroom, 'assets'=>$assets, 'roomImages'=>$roomImages, 'roomUsers'=>$roomUsers, 'users'=>$users])
    @elseif($section === 'search')
        <form class="flex gap-2"><input name="q" value="{{ request('q') }}" placeholder="Mã/tên vật tư hoặc tài sản" class="rounded border px-3 py-2"><button class="rounded bg-blue-600 px-4 py-2 text-white">Tìm kiếm</button></form><div class="rounded border bg-white p-4"><h2 class="font-semibold">Danh mục vật tư</h2>@foreach($materials as $item)<div class="border-b p-2">{{ $item->code }} — {{ $item->name }} — {{ $item->quantity }} {{ $item->unit }} — {{ $item->classroom?->name }}</div>@endforeach<h2 class="mt-5 font-semibold">Tài sản phòng</h2>@foreach($assets as $item)<div class="border-b p-2">{{ $item->asset_code }} — {{ $item->name }} — {{ $item->classroom?->name }}</div>@endforeach</div>
    @elseif($section === 'movement-report')
        <div class="flex gap-2"><a href="{{ route('inventory.movement-report.csv', request()->query()) }}" class="rounded bg-slate-700 px-4 py-2 text-white">Xu?t CSV</a></div><div class="overflow-x-auto rounded border bg-white"><table class="w-full text-left text-sm"><thead class="bg-slate-100"><tr><th class="p-2">Th?i gian</th><th class="p-2">V?t tu</th><th class="p-2">Lo?i</th><th class="p-2">S? lu?ng</th><th class="p-2">Tham chi?u</th><th class="p-2">Ngu?i th?c hi?n</th></tr></thead><tbody>@forelse($rows as $row)<tr class="border-t"><td class="p-2">{{ $row->created_at?->format('d/m/Y H:i') }}</td><td class="p-2">{{ $row->material?->code }} ? {{ $row->material?->name }}</td><td class="p-2">{{ $row->type }}</td><td class="p-2">{{ $row->quantity }}</td><td class="p-2">{{ $row->reference }}</td><td class="p-2">{{ $row->user?->name }}</td></tr>@empty<tr><td colspan="6" class="p-5 text-center">Chua c? d? li?u.</td></tr>@endforelse</tbody></table><div class="p-3">{{ $rows->links() }}</div></div><div class="mt-4 rounded border bg-white p-4"><h2 class="mb-2 font-semibold">?i?u d?ng / thu h?i</h2>@foreach($transfers as $item)<div class="border-b p-2">{{ $item->asset?->asset_code }} ? {{ $item->type }} ? {{ $item->status }}</div>@endforeach</div>
    @elseif($section === 'reports')
        @include('inventory::partials.report-links')
        <div class="grid gap-4 md:grid-cols-4">@foreach([['Vật tư',$materialCount],['Tài sản',$assetCount],['Đang sửa',$repairCount],['Đề xuất chờ duyệt',$proposalCount]] as $stat)<div class="rounded border bg-white p-5"><div class="text-sm text-slate-500">{{ $stat[0] }}</div><div class="text-3xl font-bold">{{ $stat[1] }}</div></div>@endforeach</div><a href="{{ route('inventory.reports.word') }}" class="inline-block rounded bg-blue-600 px-4 py-2 text-white">Xuất báo cáo Word</a><div class="grid gap-4 lg:grid-cols-3"><div class="rounded border bg-white p-4"><h2 class="mb-2 font-semibold">Vật tư hỏng / đang sửa</h2>@foreach($brokenAssets as $item)<div class="border-b p-2">{{ $item->asset_code }} — {{ $item->name }} — {{ $item->status }}</div>@endforeach</div><div class="rounded border bg-white p-4"><h2 class="mb-2 font-semibold">Sắp hết hạn</h2>@foreach($expiringAssets as $item)<div class="border-b p-2">{{ $item->name }} — {{ $item->expiry_date?->format('d/m/Y') }}</div>@endforeach</div><div class="rounded border bg-white p-4"><h2 class="mb-2 font-semibold">Lịch sử sửa chữa</h2>@foreach($repairHistory as $item)<div class="border-b p-2">{{ $item->asset?->asset_code }} — {{ $item->status }} — {{ $item->completed_at?->format('d/m/Y') }}</div>@endforeach</div></div>
    @elseif($section === 'templates')
        <form method="POST" action="{{ route('inventory.templates.store') }}" enctype="multipart/form-data" class="grid gap-2 rounded border bg-white p-4 md:grid-cols-3">@csrf<input name="code" required placeholder="Mã mẫu" class="rounded border p-2"><input name="name" required placeholder="Tên mẫu" class="rounded border p-2"><input name="file" type="file" accept=".doc,.docx" class="rounded border p-2"><textarea name="description" placeholder="Mô tả" class="rounded border p-2 md:col-span-3"></textarea><button class="rounded bg-blue-600 px-4 py-2 text-white">Lưu mẫu Word</button></form><div class="rounded border bg-white p-5">@forelse($templates as $item)<div class="border-b p-3">{{ $item->code }} — {{ $item->name }} @if($item->file_path)<span class="text-green-600">(đã có file)</span>@endif</div>@empty<p class="text-slate-500">Chưa có mẫu.</p>@endforelse</div>
    @endif
</div>
@endsection

