@extends('layouts.admin')
@php($portalHome = route('inventory.portal'))
@php($portalTitle = 'Cổng quản lý vật tư')
@php($portalIcon = 'bi-box-seam')
@section('title', 'Quản lý vật tư')
@section('page-title', 'Quản lý vật tư')
@section('content')
@if(false)
<div class="mb-5 flex flex-col gap-4 rounded-2xl border border-blue-100 bg-gradient-to-r from-blue-950 to-blue-700 p-5 text-white sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-widest text-blue-200">Cổng nghiệp vụ</p><h1 class="mt-1 text-2xl font-extrabold">Quản lý vật tư</h1><p class="mt-1 text-sm text-blue-100">Mở giao diện quản lý vật tư riêng, không dùng sidebar Dashboard.</p></div><a href="{{ route('inventory.portal') }}" class="inline-flex items-center justify-center rounded-xl bg-white px-4 py-2.5 font-extrabold text-blue-900 shadow-sm hover:bg-blue-50">Xem cổng <i class="bi bi-arrow-up-right ml-2"></i></a></div>
@endif
<x-breadcrumb :items="[['title' => 'Trang chủ'], ['title' => 'Quản lý vật tư']]" />
<x-page-header title="QUẢN LÝ VẬT TƯ" subtitle="Danh mục vật tư · kho · điều động · sửa chữa · báo cáo" />
<div class="mb-8 grid grid-cols-1 gap-4 sm:grid-cols-3">
    <div class="rounded-xl border border-blue-100 border-l-4 border-l-blue-500 bg-white p-5 shadow-sm"><p class="text-sm text-slate-600">Mặt hàng vật tư</p><p class="mt-1 text-3xl font-bold text-slate-900">{{ number_format($stats['materials']) }}</p></div>
    <div class="rounded-xl border border-emerald-100 border-l-4 border-l-emerald-500 bg-white p-5 shadow-sm"><p class="text-sm text-slate-600">Số lượng tồn kho</p><p class="mt-1 text-3xl font-bold text-slate-900">{{ number_format($stats['quantity'], 2) }}</p></div>
    <div class="rounded-xl border border-indigo-100 border-l-4 border-l-indigo-500 bg-white p-5 shadow-sm"><p class="text-sm text-slate-600">Đề xuất chờ xử lý</p><p class="mt-1 text-3xl font-bold text-slate-900">{{ number_format($stats['pending']) }}</p></div>
</div>
<div class="mb-4 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
    @foreach([['inventory.portal','Xem cổng vật tư','Giao diện cổng nghiệp vụ riêng — tách biệt Dashboard','bi-box-seam','border-blue-300 ring-1 ring-blue-100'],['inventory.warehouse','Kho vật tư','Theo dõi kho và tồn kho','bi-boxes',''],['inventory.category','Danh mục vật tư','Phân loại ngành và danh mục','bi-tags',''],['inventory.proposals','Đề xuất nghiệp vụ','Mua sắm, sửa chữa, thanh lý','bi-send',''],['inventory.transfers','Điều động & thu hồi','Quản lý tài sản theo phòng','bi-arrow-left-right',''],['inventory.reports','Báo cáo vật tư','Tổng hợp và xuất báo cáo','bi-bar-chart',''],['inventory.assets','Cập nhật vật tư','Cập nhật tài sản và thiết bị','bi-pencil-square',''],['inventory.search','Tìm kiếm vật tư','Tra cứu nhanh theo mã, tên','bi-search','']] as [$route,$label,$desc,$icon,$style])
        <a href="{{ route($route) }}" class="group rounded-xl border bg-white p-5 shadow-sm transition hover:border-blue-200 hover:shadow-md {{ $style }}"><div class="mb-3 flex h-11 w-11 items-center justify-center rounded-lg bg-blue-100 text-xl text-blue-700"><i class="bi {{ $icon }}"></i></div><span class="font-semibold text-slate-900 group-hover:text-blue-700">{{ $label }}</span><span class="mt-1 block text-sm text-slate-500">{{ $desc }}</span></a>
    @endforeach
</div>
@if(false)
<div class="space-y-5"><h1 class="text-2xl font-bold">Quản lý vật tư</h1>@if(session('success'))<div class="rounded bg-green-100 p-3 text-green-800">{{ session('success') }}</div>@endif
<div class="flex flex-wrap gap-2"><form class="flex gap-2"><input name="search" value="{{ request('search') }}" placeholder="Tìm mã hoặc tên vật tư" class="rounded border px-3 py-2"><button class="rounded bg-blue-600 px-4 py-2 text-white">Tìm</button></form><form method="POST" action="{{ route('inventory.import') }}" enctype="multipart/form-data" class="flex gap-2">@csrf<input name="file" type="file" accept=".xlsx,.xls,.csv" required class="rounded border px-2 py-1"><button class="rounded bg-slate-700 px-3 py-2 text-white">Import Excel/CSV</button></form></div>
<div class="grid gap-5 lg:grid-cols-3"><form method="POST" action="{{ route('inventory.store') }}" class="rounded border bg-white p-4">@csrf<h2 class="mb-3 font-semibold">Thêm vật tư</h2><input name="code" required placeholder="Mã vật tư" class="mb-2 w-full rounded border p-2"><input name="name" required placeholder="Tên vật tư" class="mb-2 w-full rounded border p-2"><select name="category_id" class="mb-2 w-full rounded border p-2"><option value="">Không phân loại</option>@foreach($categories as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select><select name="building_id" class="mb-2 w-full rounded border p-2"><option value="">Tòa nhà</option>@foreach($buildings as $item)<option value="{{ $item->id }}">{{ $item->code }} — {{ $item->name }}</option>@endforeach</select><select name="classroom_id" class="mb-2 w-full rounded border p-2"><option value="">Phòng</option>@foreach($classrooms as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select><div class="grid grid-cols-2 gap-2"><input name="unit" value="cái" class="rounded border p-2"><input name="quantity" type="number" min="0" step=".01" value="0" class="rounded border p-2"></div><input name="location" placeholder="Vị trí/kho" class="my-2 w-full rounded border p-2"><button class="rounded bg-blue-600 px-4 py-2 text-white">Lưu</button></form>
<div class="overflow-x-auto rounded border bg-white lg:col-span-2"><table class="w-full text-left text-sm"><thead class="bg-slate-100"><tr><th class="p-3">Mã</th><th class="p-3">Tên</th><th class="p-3">Tồn</th><th class="p-3">Nhập/Xuất</th></tr></thead><tbody>@forelse($materials as $item)<tr class="border-t"><td class="p-3 font-mono">{{ $item->code }}</td><td class="p-3">{{ $item->name }}<div class="text-xs text-slate-500">{{ $item->building?->name }} {{ $item->classroom?->name }} {{ $item->location }}</div><details class="mt-1"><summary class="cursor-pointer text-xs text-blue-600">Sửa / xóa</summary><form method="POST" action="{{ route('inventory.update',$item) }}" class="mt-1 flex flex-wrap gap-1">@csrf @method('PATCH')<input name="code" value="{{ $item->code }}" class="w-24 rounded border p-1"><input name="name" value="{{ $item->name }}" class="rounded border p-1"><input name="unit" value="{{ $item->unit }}" class="w-16 rounded border p-1"><input name="location" value="{{ $item->location }}" placeholder="Vị trí" class="rounded border p-1"><input type="hidden" name="category_id" value="{{ $item->category_id }}"><input type="hidden" name="building_id" value="{{ $item->building_id }}"><input type="hidden" name="classroom_id" value="{{ $item->classroom_id }}"><button class="rounded bg-blue-600 px-2 py-1 text-xs text-white">Lưu</button></form><form method="POST" action="{{ route('inventory.destroy',$item) }}" class="mt-1">@csrf @method('DELETE')<button class="text-xs text-red-600">Xóa vật tư</button></form></details></td><td class="p-3">{{ $item->quantity }} {{ $item->unit }}</td><td class="p-3"><form method="POST" action="{{ route('inventory.movement',$item) }}" class="flex gap-1">@csrf<select name="type" class="rounded border"><option value="IN">Nhập</option><option value="OUT">Xuất</option><option value="ADJUST">Điều chỉnh</option></select><input name="quantity" required type="number" min=".01" step=".01" class="w-20 rounded border"><button class="rounded bg-slate-700 px-2 py-1 text-white">Lưu</button></form></td></tr>@empty<tr><td colspan="4" class="p-8 text-center">Chưa có vật tư.</td></tr>@endforelse</tbody></table><div class="p-3">{{ $materials->links() }}</div></div></div></div>
@endif
@endsection
