@extends('layouts.admin')
@section('title','Đáp án đề tích hợp')
@section('content')
@include('partials.module-menu', ['module' => 'exam'])
@php($labels=['DRAFT'=>'Bản nháp','PENDING_DEPT'=>'Chờ khoa duyệt','PENDING_EXAM_OFFICE'=>'Chờ khảo thí duyệt','PENDING_BGH'=>'Chờ BGH duyệt','APPROVED'=>'Đã duyệt','RETURNED'=>'Trả lại'])
@php($formatAnswer = static fn ($answer) => preg_replace('/\R\s*(\[[^\x5D\r\n]*(?:\x{0111}i\x{1EC3}m|diem)[^\x5D\r\n]*\])/iu', ' $1', trim((string) $answer)) ?: trim((string) $answer))
<x-breadcrumb :items="[['title'=>'Đáp án đề tích hợp','url'=>route('essay-exams.integrated-answers.index')],['title'=>$answerSet->code]]" />
<div class="bg-white border rounded-xl p-5 mb-5"><div class="flex items-start justify-between gap-4"><div><h1 class="text-2xl font-bold">{{ $answerSet->title }}</h1><p class="mt-1 text-sm text-slate-500">{{ $answerSet->code }} · {{ $answerSet->subject->name ?? '—' }} · {{ $answerSet->items->groupBy('paper_number')->count() }} đề</p></div><span class="px-3 py-1 rounded-full bg-blue-50 text-blue-800 font-bold text-sm">{{ $labels[$answerSet->status] ?? $answerSet->status }}</span></div>@if($answerSet->status === 'APPROVED')<p class="mt-4 rounded-lg bg-emerald-50 border border-emerald-200 p-3 text-emerald-800 font-semibold">Bộ đáp án đã được BGH duyệt. Chỉ được xem; không khóa, không tạo QR, không sửa và không xóa.</p>@endif</div>
<div class="space-y-4">@foreach($answerSet->items->groupBy('paper_number') as $paper=>$items)<section class="bg-white border rounded-xl overflow-hidden"><div class="px-4 py-3 bg-blue-50 border-b font-bold">Đề số {{ $paper }} <span class="font-normal text-slate-500">({{ $items->count() }} đáp án)</span></div><div class="divide-y">@foreach($items as $item)<div class="grid grid-cols-[90px_1fr_100px] gap-3 p-3"><b>Câu {{ $item->question_number }}</b><div class="whitespace-pre-line">{{ $item->answer ? $formatAnswer($item->answer) : 'Chưa có đáp án' }}</div><span class="text-right text-slate-500">{{ $item->points }} điểm</span></div>@endforeach</div></section>@endforeach</div>
@if(in_array($answerSet->status,['DRAFT','RETURNED'],true) && auth()->user()->can('essay-exams.submission.create'))<form class="mt-5" method="POST" action="{{ route('essay-exams.integrated-answers.submit',$answerSet) }}">@csrf<button class="px-5 py-2 rounded-lg bg-emerald-600 text-white font-bold">Gửi đi duyệt</button></form>@endif
@if(in_array($answerSet->status,['PENDING_DEPT','PENDING_EXAM_OFFICE','PENDING_BGH'],true) && auth()->user()->can('essay-exams.approval.approve'))<div class="mt-5 flex flex-wrap gap-2"><form method="POST" action="{{ route('essay-exams.integrated-answers.approve',$answerSet) }}">@csrf<input type="hidden" name="stage" value="{{ $answerSet->status }}"><button class="px-5 py-2 rounded-lg bg-blue-600 text-white font-bold">Duyệt bộ đáp án</button></form><form method="POST" action="{{ route('essay-exams.integrated-answers.return',$answerSet) }}" class="flex gap-2">@csrf<input name="return_note" required placeholder="Lý do trả lại" class="border rounded-lg px-3 py-2"><button class="px-5 py-2 rounded-lg bg-amber-500 text-white font-bold">Trả lại</button></form></div>@endif
@endsection
