<?php

namespace Modules\Inventory\Controllers;

use App\Http\Controllers\ModuleBaseController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Modules\Building\Models\Building;
use Modules\Classroom\Models\Classroom;
use Modules\Inventory\Models\{InventoryAsset,InventoryAuditLog,InventoryBrokenLog,InventoryCategory,InventoryMaterial,InventoryMovement,InventoryProposal,InventoryRepair,InventoryReportTemplate,InventoryRoomImage,InventoryRoomUser,InventoryTransfer,InventoryUserCategory,InventoryWarehouse,InventoryWarehouseItem};

class InventoryWorkflowController extends ModuleBaseController
{
    public function category(){return view('inventory::feature',['section'=>'category','title'=>'Danh mục ngành vật tư','categories'=>InventoryCategory::with('parent')->withCount('materials')->latest()->get(),'parents'=>InventoryCategory::whereNull('parent_id')->orderBy('name')->get(),'users'=>\App\Models\User::where('status',1)->orderBy('name')->get()]);}
    public function categoryStore(Request $r){InventoryCategory::create($r->validate(['parent_id'=>'nullable|exists:inventory_categories,id','code'=>'required|string|max:50|unique:inventory_categories,code','name'=>'required|string|max:255','description'=>'nullable|string']));return back()->with('success','Đã thêm danh mục.');}
    public function categoryUpdate(Request $r,InventoryCategory $category){$category->update($r->validate(['parent_id'=>'nullable|exists:inventory_categories,id','code'=>'required|string|max:50|unique:inventory_categories,code,'.$category->id,'name'=>'required|string|max:255','description'=>'nullable|string']));return back()->with('success','Đã cập nhật danh mục.');}
    public function categoryDelete(InventoryCategory $category){if($category->materials()->exists()||$category->children()->exists())return back()->withErrors(['category'=>'Không thể xóa danh mục đang có dữ liệu con.']);$category->delete();return back()->with('success','Đã xóa danh mục.');}

    public function assets(Request $r){$assets=InventoryAsset::with(['material','classroom'])->when($r->search,fn($q,$s)=>$q->where(fn($x)=>$x->where('asset_code','like',"%$s%")->orWhere('name','like',"%$s%")))->latest()->paginate(20)->withQueryString();return view('inventory::feature',['section'=>'assets','title'=>'Cập nhật vật tư','assets'=>$assets,'materials'=>InventoryMaterial::orderBy('name')->get(),'classrooms'=>Classroom::active()->orderBy('name')->get()]);}
    public function assetStore(Request $r){$d=$r->validate(['material_id'=>'nullable|exists:inventory_materials,id','classroom_id'=>'nullable|exists:classrooms,id','holding_unit_id'=>'nullable|exists:units,id','asset_code'=>'required|string|max:100|unique:inventory_assets,asset_code','name'=>'required|string|max:255','category'=>'nullable|string|max:255','quantity'=>'required|numeric|min:.01','broken_quantity'=>'nullable|numeric|min:0','unit'=>'nullable|string|max:30','grade'=>'nullable|integer|min:1|max:5','manufacture_year'=>'nullable|integer|min:1900|max:2200','usage_year'=>'nullable|integer|min:1900|max:2200','install_address'=>'nullable|string|max:255','status'=>'required|in:NORMAL,BROKEN,REPAIRING,LIQUIDATED','purchase_date'=>'nullable|date','expiry_date'=>'nullable|date','broken_at'=>'nullable|date','repair_started_at'=>'nullable|date','repair_completed_at'=>'nullable|date','repair_performer'=>'nullable|string|max:255','note'=>'nullable|string','description'=>'nullable|string']);InventoryAsset::create($d);return back()->with('success','Đã thêm tài sản.');}
    public function assetUpdate(Request $r,InventoryAsset $asset){$d=$r->validate(['material_id'=>'nullable|exists:inventory_materials,id','classroom_id'=>'nullable|exists:classrooms,id','holding_unit_id'=>'nullable|exists:units,id','asset_code'=>'required|string|max:100|unique:inventory_assets,asset_code,'.$asset->id,'name'=>'required|string|max:255','category'=>'nullable|string|max:255','quantity'=>'required|numeric|min:.01','broken_quantity'=>'nullable|numeric|min:0','unit'=>'nullable|string|max:30','grade'=>'nullable|integer|min:1|max:5','manufacture_year'=>'nullable|integer|min:1900|max:2200','usage_year'=>'nullable|integer|min:1900|max:2200','install_address'=>'nullable|string|max:255','status'=>'required|in:NORMAL,BROKEN,REPAIRING,LIQUIDATED','purchase_date'=>'nullable|date','expiry_date'=>'nullable|date','broken_at'=>'nullable|date','repair_started_at'=>'nullable|date','repair_completed_at'=>'nullable|date','repair_performer'=>'nullable|string|max:255','note'=>'nullable|string','description'=>'nullable|string']);$asset->update($d);return back()->with('success','Đã cập nhật tài sản.');}
    public function assetDelete(InventoryAsset $asset){if($asset->repairs()->exists()||$asset->proposals()->exists())return back()->withErrors(['asset'=>'Không thể xóa tài sản đã có lịch sử.']);$asset->delete();return back()->with('success','Đã xóa tài sản.');}

    public function warehouse(){return view('inventory::feature',['section'=>'warehouse','title'=>'Kho vật tư','warehouses'=>InventoryWarehouse::with(['manager','items'])->latest()->get(),'users'=>\App\Models\User::where('status',1)->orderBy('name')->get(),'materials'=>InventoryMaterial::orderBy('name')->get()]);}
    public function warehouseStore(Request $r){InventoryWarehouse::create($r->validate(['code'=>'required|string|max:80|unique:inventory_warehouses,code','name'=>'required|string|max:255','location'=>'nullable|string|max:255','manager_id'=>'nullable|exists:users,id','description'=>'nullable|string']));return back()->with('success','Đã thêm kho.');}
    public function warehouseItemStore(Request $r){$d=$r->validate(['warehouse_id'=>'required|exists:inventory_warehouses,id','material_id'=>'nullable|exists:inventory_materials,id','code'=>'required|string|max:100','name'=>'required|string|max:255','unit'=>'nullable|string|max:30','quantity'=>'required|numeric|min:0','minimum_quantity'=>'nullable|numeric|min:0','note'=>'nullable|string']);InventoryWarehouseItem::updateOrCreate(['warehouse_id'=>$d['warehouse_id'],'code'=>$d['code']],$d);return back()->with('success','Đã cập nhật tồn kho.');}

    public function proposals(){return view('inventory::feature',['section'=>'proposals','title'=>'Đề xuất / thanh lý','proposals'=>InventoryProposal::with(['unit','items'])->latest()->get(),'units'=>\Modules\Unit\Models\Unit::active()->orderBy('name')->get(),'assets'=>InventoryAsset::orderBy('name')->get(),'materials'=>InventoryMaterial::orderBy('name')->get()]);}
    public function proposalStore(Request $r){$d=$r->validate(['type'=>'required|in:REPAIR,RECALL,LIQUIDATION,PURCHASE','title'=>'required|string|max:255','description'=>'nullable|string','unit_id'=>'nullable|exists:units,id','asset_id'=>'nullable|exists:inventory_assets,id','material_id'=>'nullable|exists:inventory_materials,id','quantity'=>'nullable|numeric|min:.01','item_note'=>'nullable|string','nganh_code'=>'nullable|string|max:80']);$p=DB::transaction(function()use($d,$r){$p=InventoryProposal::create(collect($d)->except(['asset_id','material_id','quantity','item_note'])->merge(['created_by'=>$r->user()->id,'proposed_by_user_id'=>$r->user()->id,'proposed_by_username'=>$r->user()->email,'proposed_by_display_name'=>$r->user()->name])->all());if(($d['asset_id']??null)||($d['material_id']??null)){$m=$d['material_id']?InventoryMaterial::find($d['material_id']):null;$a=$d['asset_id']?InventoryAsset::find($d['asset_id']):null;$p->items()->create(['asset_id'=>$a?->id,'material_id'=>$m?->id,'material_code'=>$m?->code,'material_name'=>$m?->name??$a?->name,'name'=>$m?->name??$a?->name??$d['title'],'quantity'=>$d['quantity']??1,'unit'=>$m?->unit??$a?->unit,'note'=>$d['item_note']??null,'original_grade'=>$a?->grade,'original_code'=>$a?->asset_code]);}InventoryAuditLog::create(['user_id'=>$r->user()->id,'action'=>'CREATE','entity_type'=>'proposal','entity_id'=>$p->id,'details'=>$d]);return $p;});return back()->with('success','Đã tạo đề xuất.');}
    public function proposalDecide(Request $r,InventoryProposal $proposal){$d=$r->validate(['status'=>'required|in:APPROVED,REJECTED,COMPLETED','decision_note'=>'nullable|string','decision_number'=>'nullable|string|max:100','decision_issuing_level'=>'nullable|string|max:100','decision_signer'=>'nullable|string|max:255']);DB::transaction(function()use($d,$proposal,$r){$proposal->update($d+['decided_by'=>$r->user()->id,'decided_at'=>now(),'completed_at'=>$d['status']==='COMPLETED'?now():null]);if(in_array($d['status'],['APPROVED','COMPLETED'],true))foreach($proposal->items as $item){if($proposal->type==='LIQUIDATION'&&$item->asset)$item->asset->update(['status'=>'LIQUIDATED']);if($proposal->type==='RECALL'&&$item->asset)$item->asset->update(['classroom_id'=>null]);if($proposal->type==='REPAIR'&&$item->asset)$item->asset->update(['status'=>'REPAIRING']);}InventoryAuditLog::create(['user_id'=>$r->user()->id,'action'=>$d['status'],'entity_type'=>'proposal','entity_id'=>$proposal->id,'details'=>$d]);});return back()->with('success','Đã cập nhật quyết định.');}

    public function repairs(){return view('inventory::feature',['section'=>'repairs','title'=>'Phân công sửa chữa','repairs'=>InventoryRepair::with(['asset','assignee'])->latest()->get(),'assets'=>InventoryAsset::whereIn('status',['BROKEN','REPAIRING'])->orderBy('name')->get(),'users'=>\App\Models\User::where('status',1)->orderBy('name')->get()]);}
    public function repairStore(Request $r){$d=$r->validate(['asset_id'=>'required|exists:inventory_assets,id','content'=>'required|string','assigned_to'=>'nullable|exists:users,id','cost'=>'nullable|numeric|min:0','performer'=>'nullable|string|max:255']);$a=InventoryAsset::findOrFail($d['asset_id']);$repair=InventoryRepair::create($d+['status'=>($d['assigned_to']??null)?'ASSIGNED':'OPEN','source_type'=>'REPAIR_REQUEST','requested_by'=>$r->user()->id,'opened_at'=>now(),'started_at'=>now()]);$a->update(['status'=>'REPAIRING','repair_started_at'=>now(),'repair_performer'=>$d['performer']??null]);InventoryBrokenLog::create(['event_type'=>'BROKEN','source_type'=>'REPAIR_REQUEST','source_id'=>$repair->id,'asset_id'=>$a->id,'asset_code'=>$a->asset_code,'asset_name'=>$a->name,'quantity'=>$a->quantity,'original_grade'=>$a->grade,'grade_after'=>5,'status_after'=>'REPAIRING','reason'=>$d['content'],'performer'=>$d['performer']??null,'event_at'=>now(),'actor_user_id'=>$r->user()->id]);return back()->with('success','Đã ghi nhận sửa chữa.');}
    public function repairComplete(Request $r,InventoryRepair $repair){$d=$r->validate(['status'=>'required|in:COMPLETED,CANCELLED','result'=>'nullable|string','result_note'=>'nullable|string','performer'=>'nullable|string|max:255']);$repair->update($d+['completed_at'=>now(),'result_note'=>$d['result_note']??($d['result']??null)]);if($d['status']==='COMPLETED'){$a=$repair->asset;$a?->update(['status'=>'NORMAL','repair_completed_at'=>now(),'repair_performer'=>$d['performer']??$repair->performer]);if($a)InventoryBrokenLog::create(['event_type'=>'COMPLETED','source_type'=>'REPAIR_REQUEST','source_id'=>$repair->id,'asset_id'=>$a->id,'asset_code'=>$a->asset_code,'asset_name'=>$a->name,'quantity'=>$a->quantity,'original_grade'=>$a->grade,'grade_after'=>2,'status_after'=>'NORMAL','result_note'=>$d['result_note']??($d['result']??null),'performer'=>$d['performer']??$repair->performer,'event_at'=>now(),'actor_user_id'=>$r->user()->id]);}return back()->with('success','Đã cập nhật sửa chữa.');}

    public function transfers(){return view('inventory::feature',['section'=>'transfers','title'=>'Điều động và thu hồi','transfers'=>InventoryTransfer::with(['asset','fromClassroom','toClassroom'])->latest()->get(),'assets'=>InventoryAsset::orderBy('name')->get(),'classrooms'=>Classroom::active()->orderBy('name')->get()]);}
    public function transferStore(Request $r){$d=$r->validate(['asset_id'=>'required|exists:inventory_assets,id','from_classroom_id'=>'nullable|exists:classrooms,id','to_classroom_id'=>'nullable|exists:classrooms,id','type'=>'required|in:TRANSFER,RECALL','reason'=>'nullable|string']);InventoryTransfer::create($d+['requested_by'=>$r->user()->id]);return back()->with('success','Đã tạo phiếu điều động.');}
    public function transferDecide(Request $r,InventoryTransfer $transfer){$d=$r->validate(['status'=>'required|in:APPROVED,REJECTED,COMPLETED','decision_note'=>'nullable|string','decision_number'=>'nullable|string|max:100']);DB::transaction(function()use($d,$transfer,$r){$transfer->update($d+['decided_by'=>$r->user()->id,'decided_at'=>now()]);if($d['status']==='COMPLETED'&&$transfer->asset)$transfer->asset->update(['classroom_id'=>$transfer->type==='RECALL'?null:$transfer->to_classroom_id]);});return back()->with('success','Đã cập nhật phiếu điều động.');}

    public function search(Request $r){$term=$r->string('q')->toString();return view('inventory::feature',['section'=>'search','title'=>'Tìm kiếm vật tư','materials'=>InventoryMaterial::with(['building','classroom'])->when($term,fn($q)=>$q->where(fn($x)=>$x->where('code','like',"%$term%")->orWhere('name','like',"%$term%")))->get(),'assets'=>InventoryAsset::with('classroom')->when($term,fn($q)=>$q->where(fn($x)=>$x->where('asset_code','like',"%$term%")->orWhere('name','like',"%$term%")))->get()]);}
    public function logs(){return view('inventory::feature',['section'=>'logs','title'=>'Nhật ký vật tư','logs'=>InventoryMovement::with(['material','user'])->latest()->paginate(30),'transferLogs'=>InventoryTransfer::with(['asset','fromClassroom','toClassroom'])->latest()->limit(50)->get(),'repairLogs'=>InventoryRepair::with('asset')->latest()->limit(50)->get(),'proposalLogs'=>InventoryProposal::with('items')->latest()->limit(50)->get(),'auditLogs'=>InventoryAuditLog::with('user')->latest()->limit(100)->get(),'brokenLogs'=>InventoryBrokenLog::with(['asset','actor'])->latest()->limit(100)->get()]);}
    public function assignCategory(Request $r){$d=$r->validate(['user_id'=>'required|exists:users,id','category_id'=>'required|exists:inventory_categories,id']);InventoryUserCategory::firstOrCreate($d);InventoryAuditLog::create(['user_id'=>$r->user()->id,'action'=>'ASSIGN','entity_type'=>'user_category','entity_id'=>$d['category_id'],'details'=>$d]);return back()->with('success','Đã gán ngành vật tư.');}
    public function myCatalog(Request $r){$categories=InventoryCategory::withCount('materials')->whereHas('userAssignments',fn($q)=>$q->where('user_id',$r->user()->id))->orderBy('name')->get();return view('inventory::feature',['section'=>'my-catalog','title'=>'Ngành vật tư của tôi','categories'=>$categories]);}
    public function liquidation(){return view('inventory::feature',['section'=>'liquidation','title'=>'Thanh lý vật tư','proposals'=>InventoryProposal::with(['unit','items'])->where('type','LIQUIDATION')->latest()->get(),'units'=>\Modules\Unit\Models\Unit::active()->orderBy('name')->get(),'assets'=>InventoryAsset::where('status','<>','LIQUIDATED')->orderBy('name')->get(),'materials'=>InventoryMaterial::orderBy('name')->get()]);}

    public function building(Building $building){$classrooms=Classroom::where('building_id',$building->id)->orderBy('name')->get();$classrooms->each(fn($room)=>$room->inventory_count=InventoryAsset::where('classroom_id',$room->id)->count());return view('inventory::feature',['section'=>'building','title'=>'Tòa nhà: '.$building->name,'building'=>$building,'classrooms'=>$classrooms]);}
    public function room(Classroom $classroom){return view('inventory::feature',['section'=>'room','title'=>'Phòng: '.$classroom->name,'classroom'=>$classroom,'assets'=>InventoryAsset::where('classroom_id',$classroom->id)->with('material')->orderBy('name')->get(),'roomImages'=>InventoryRoomImage::where('classroom_id',$classroom->id)->latest()->get(),'roomUsers'=>InventoryRoomUser::where('classroom_id',$classroom->id)->with('user')->latest()->get(),'users'=>\App\Models\User::where('status',1)->orderBy('name')->get()]);}
    public function roomImageStore(Request $r,Classroom $classroom){$d=$r->validate(['image'=>'required|image|max:10240','caption'=>'nullable|string|max:255']);InventoryRoomImage::create(['classroom_id'=>$classroom->id,'path'=>$r->file('image')->store('inventory-room-images'),'caption'=>$d['caption']??null,'uploaded_by'=>$r->user()->id]);return back()->with('success','Đã thêm ảnh phòng.');}
    public function roomImageDelete(InventoryRoomImage $image){abort_unless(auth()->user()?->can('inventory.delete'),403);Storage::delete($image->path);$image->delete();return back()->with('success','Đã xóa ảnh phòng.');}
    public function roomUserStore(Request $r,Classroom $classroom){$d=$r->validate(['user_id'=>'required|exists:users,id','role'=>'nullable|string|max:100']);InventoryRoomUser::updateOrCreate(['classroom_id'=>$classroom->id,'user_id'=>$d['user_id']],['role'=>$d['role']??null]);return back()->with('success','Đã gán người phụ trách phòng.');}
    public function roomUserDelete(InventoryRoomUser $roomUser){$roomUser->delete();return back()->with('success','Đã bỏ người phụ trách phòng.');}

    public function reports(){return view('inventory::feature',['section'=>'reports','title'=>'Báo cáo vật tư','materialCount'=>InventoryMaterial::count(),'assetCount'=>InventoryAsset::count(),'repairCount'=>InventoryRepair::whereIn('status',['OPEN','ASSIGNED','REPAIRING'])->count(),'proposalCount'=>InventoryProposal::where('status','PENDING')->count(),'materials'=>InventoryMaterial::with('category')->orderBy('name')->get(),'brokenAssets'=>InventoryAsset::with('classroom')->whereIn('status',['BROKEN','REPAIRING'])->orderBy('name')->get(),'expiringAssets'=>InventoryAsset::with('classroom')->whereNotNull('expiry_date')->whereBetween('expiry_date',[now()->toDateString(),now()->addMonths(3)->toDateString()])->orderBy('expiry_date')->get(),'repairHistory'=>InventoryRepair::with('asset')->latest()->limit(50)->get()]);}
    public function reportWord(){ $word=new \PhpOffice\PhpWord\PhpWord();$word->setDefaultFontName('Arial');$section=$word->addSection();$section->addTitle('INVENTORY REPORT',1);$section->addText('Generated: '.now()->format('Y-m-d H:i'));$table=$section->addTable(['borderSize'=>6,'borderColor'=>'999999']);foreach(['No','Code','Name','Unit','Quantity'] as $h)$table->addCell(1800)->addText($h);foreach(InventoryMaterial::orderBy('name')->get() as $i=>$m){$row=$table->addRow();foreach([$i+1,$m->code,$m->name,$m->unit,$m->quantity] as $v)$row->addCell(1800)->addText((string)$v);} $path=storage_path('app/report-inventory-'.now()->format('YmdHis').'.docx');(new \PhpOffice\PhpWord\Writer\Word2007($word))->save($path);return response()->download($path,'inventory-report.docx')->deleteFileAfterSend(true);}
    public function reportCsv(){$rows=InventoryMaterial::orderBy('name')->get();$callback=function()use($rows){$out=fopen('php://output','w');fputcsv($out,['No','Code','Name','Unit','Quantity','Location']);foreach($rows as $i=>$m)fputcsv($out,[$i+1,$m->code,$m->name,$m->unit,$m->quantity,$m->location]);fclose($out);};return response()->streamDownload($callback,'inventory-report.csv',['Content-Type'=>'text/csv; charset=UTF-8']);}
    public function templates(){return view('inventory::feature',['section'=>'templates','title'=>'Mẫu báo cáo Word','templates'=>InventoryReportTemplate::where('active',true)->latest()->get()]);}
    public function templateStore(Request $r){$d=$r->validate(['code'=>'required|string|max:80|unique:inventory_report_templates,code','name'=>'required|string|max:255','description'=>'nullable|string','file'=>'nullable|file|mimes:doc,docx|max:10240']);if($r->hasFile('file'))$d['file_path']=$r->file('file')->store('inventory-templates');unset($d['file']);InventoryReportTemplate::create($d);return back()->with('success','Đã lưu mẫu Word.');}
}
