<?php
namespace Modules\Inventory\Controllers;

use App\Http\Controllers\ModuleBaseController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Modules\Inventory\Models\{InventoryAuditLog,InventoryCategory,InventoryMaterial,InventoryMovement};

class InventoryController extends ModuleBaseController
{
    public function index(Request $request){$materials=InventoryMaterial::with(['category','building','classroom'])->when($request->search,fn($q,$s)=>$q->where(fn($x)=>$x->where('code','like',"%$s%")->orWhere('name','like',"%$s%")))->latest()->paginate(20)->withQueryString();$categories=InventoryCategory::where('active',true)->orderBy('name')->get();$buildings=\Modules\Building\Models\Building::where('status',true)->orderBy('name')->get();$classrooms=\Modules\Classroom\Models\Classroom::active()->orderBy('name')->get();return view('inventory::index',compact('materials','categories','buildings','classrooms'));}
    public function store(Request $request){$d=$request->validate(['category_id'=>'nullable|exists:inventory_categories,id','building_id'=>'nullable|exists:buildings,id','classroom_id'=>'nullable|exists:classrooms,id','code'=>'required|string|max:80|unique:inventory_materials,code','name'=>'required|string|max:255','unit'=>'required|string|max:30','quantity'=>'required|numeric|min:0','min_quantity'=>'nullable|numeric|min:0','price'=>'nullable|numeric|min:0','status'=>'nullable|string|max:30','manufacture_year'=>'nullable|integer|min:1900|max:2200','usage_year'=>'nullable|integer|min:1900|max:2200','classification'=>'nullable|string|max:255','asset_status'=>'nullable|string|max:30','purchase_date'=>'nullable|date','expiry_date'=>'nullable|date','location'=>'nullable|string|max:255','note'=>'nullable|string','description'=>'nullable|string']);DB::transaction(function()use($d,$request){$m=InventoryMaterial::create($d);if((float)$d['quantity']>0)InventoryMovement::create(['material_id'=>$m->id,'type'=>'IN','quantity'=>$d['quantity'],'note'=>'Opening stock','created_by'=>$request->user()->id]);InventoryAuditLog::create(['user_id'=>$request->user()->id,'action'=>'CREATE','entity_type'=>'material','entity_id'=>$m->id,'details'=>$d]);});return back()->with('success','Đã thêm vật tư.');}
    public function import(Request $request){$request->validate(['file'=>'required|file|mimes:xlsx,xls,csv,txt|max:20480']);$rows=\PhpOffice\PhpSpreadsheet\IOFactory::load($request->file('file')->getRealPath())->getActiveSheet()->toArray(null,true,true,true);$headers=array_map(fn($v)=>strtolower(trim((string)$v)),array_shift($rows));$count=0;DB::transaction(function()use($rows,$headers,$request,&$count){foreach($rows as $row){$v=[];foreach($headers as $key=>$header)$v[$header]=trim((string)($row[$key]??''));if(($v['code']??'')===''||($v['name']??'')==='')continue;$cat=($v['category_code']??'')!==''?InventoryCategory::where('code',$v['category_code'])->first():null;$payload=['category_id'=>$cat?->id,'name'=>$v['name'],'unit'=>$v['unit']??'cái','quantity'=>(float)($v['quantity']??0),'min_quantity'=>(float)($v['min_quantity']??0),'price'=>(float)($v['price']??0),'status'=>$v['status']??'ACTIVE','manufacture_year'=>($v['manufacture_year']??null)?(int)$v['manufacture_year']:null,'usage_year'=>($v['usage_year']??null)?(int)$v['usage_year']:null,'classification'=>$v['classification']??null,'asset_status'=>$v['asset_status']??'NORMAL','purchase_date'=>$v['purchase_date']??null,'expiry_date'=>$v['expiry_date']??null,'location'=>$v['location']??null,'note'=>$v['note']??null,'description'=>$v['description']??null];$m=InventoryMaterial::updateOrCreate(['code'=>$v['code']],$payload);if((float)$payload['quantity']>0)InventoryMovement::create(['material_id'=>$m->id,'type'=>'IN','quantity'=>$payload['quantity'],'note'=>'Imported material','created_by'=>$request->user()->id]);InventoryAuditLog::create(['user_id'=>$request->user()->id,'action'=>'IMPORT','entity_type'=>'material','entity_id'=>$m->id,'details'=>$payload+['code'=>$v['code']]]);$count++;}});return back()->with('success',"Đã import {$count} dòng vật tư.");}
    public function movement(Request $request,InventoryMaterial $material){$d=$request->validate(['type'=>'required|in:IN,OUT,ADJUST','quantity'=>'required|numeric|min:.01','reference'=>'nullable|string|max:255','note'=>'nullable|string']);DB::transaction(function()use($d,$material,$request){$change=$d['type']==='OUT'?-abs($d['quantity']):($d['type']==='IN'?abs($d['quantity']):$d['quantity']-(float)$material->quantity);abort_if($d['type']==='OUT'&&(float)$material->quantity<abs($change),422,'Số lượng xuất vượt tồn kho.');$material->increment('quantity',$change);$movement=InventoryMovement::create($d+['material_id'=>$material->id,'created_by'=>$request->user()->id]);InventoryAuditLog::create(['user_id'=>$request->user()->id,'action'=>'MOVEMENT','entity_type'=>'material','entity_id'=>$material->id,'details'=>$d+['movement_id'=>$movement->id,'balance_change'=>$change]]);});return back()->with('success','Đã cập nhật kho.');}
    public function update(Request $request,InventoryMaterial $material){$d=$request->validate(['category_id'=>'nullable|exists:inventory_categories,id','building_id'=>'nullable|exists:buildings,id','classroom_id'=>'nullable|exists:classrooms,id','code'=>'required|string|max:80|unique:inventory_materials,code,'.$material->id,'name'=>'required|string|max:255','unit'=>'required|string|max:30','min_quantity'=>'nullable|numeric|min:0','price'=>'nullable|numeric|min:0','status'=>'nullable|string|max:30','manufacture_year'=>'nullable|integer|min:1900|max:2200','usage_year'=>'nullable|integer|min:1900|max:2200','classification'=>'nullable|string|max:255','asset_status'=>'nullable|string|max:30','purchase_date'=>'nullable|date','expiry_date'=>'nullable|date','location'=>'nullable|string|max:255','note'=>'nullable|string','description'=>'nullable|string']);$material->update($d);InventoryAuditLog::create(['user_id'=>$request->user()->id,'action'=>'UPDATE','entity_type'=>'material','entity_id'=>$material->id,'details'=>$d]);return back()->with('success','Đã cập nhật vật tư.');}
    public function destroy(Request $request,InventoryMaterial $material){if($material->movements()->exists())return back()->withErrors(['material'=>'Không thể xóa vật tư đã có nhật ký nhập xuất.']);$id=$material->id;$material->delete();InventoryAuditLog::create(['user_id'=>$request->user()->id,'action'=>'DELETE','entity_type'=>'material','entity_id'=>$id]);return back()->with('success','Đã xóa vật tư.');}
}
