@extends('layouts.module-portal')
@php
    $portalHome = route('leave-management.portal');
    $portalTitle = 'Cổng quản lý phép';
    $portalIcon = 'bi-calendar2-check';
@endphp
@section('title', $title)
@section('page-title', $title)
@section('content')
@include('partials.module-menu', ['module' => 'leave'])
<div class="leave-management-page space-y-5 {{ $section === 'reports' ? 'leave-report-page' : '' }}">
    @if($section === 'reports')
    <style>
        .leave-report-page { gap: 22px; }
        .leave-report-page > .flex:first-of-type { position: relative; padding: 4px 0 22px; border-bottom: 1px solid #dbeafe; }
        .leave-report-page > .flex:first-of-type:before { content: ''; position: absolute; left: 0; top: -18px; width: 92px; height: 4px; border-radius: 99px; background: linear-gradient(90deg,#2563eb,#38bdf8); }
        .leave-report-page > .flex:first-of-type h1 { font-size: 30px; letter-spacing: -.035em; }
        .leave-report-page > .flex:first-of-type p:last-child { color: #64748b; font-size: 14px; }
        .leave-report-page > .flex:first-of-type a { border-color: #bfdbfe; color: #1d4ed8; box-shadow: 0 5px 14px rgba(37,99,235,.08); }
        .leave-report-page > .flex:first-of-type a:hover { background: #eff6ff; }
        .leave-report-page > .flex:nth-of-type(2) { display: flex; flex-wrap: wrap; align-items: center; gap: 12px; padding: 14px 16px; border: 1px solid #dbeafe; border-radius: 16px; background: linear-gradient(105deg,#eff6ff,#f8fbff 55%,#eef7ff); box-shadow: 0 8px 24px rgba(30,64,175,.07); }
        .leave-report-page > .flex:nth-of-type(2) a { margin: 0; }
        .leave-report-page > form { display: flex; align-items: center; gap: 10px; padding: 10px; border: 1px solid #e2e8f0; border-radius: 14px; background: #fff; box-shadow: 0 5px 16px rgba(15,23,42,.04); }
        .leave-report-page > form:before { content: 'Năm báo cáo'; margin: 0 4px 0 6px; color: #334155; font-size: 13px; font-weight: 700; }
        .leave-report-page > form input { width: 120px; border-color: #bfdbfe; border-radius: 10px; font-weight: 700; color: #1e3a8a; }
        .leave-report-page > form button { border-radius: 10px; background: #1d4ed8; padding: 9px 16px; font-weight: 700; box-shadow: 0 4px 10px rgba(29,78,216,.2); }
        .leave-report-page > .grid.md\:grid-cols-4 { gap: 14px; }
        .leave-report-page > .grid.md\:grid-cols-4 > div { position: relative; min-height: 116px; overflow: hidden; border: 1px solid #dbeafe; border-radius: 17px; padding: 20px; box-shadow: 0 8px 22px rgba(30,64,175,.08); }
        .leave-report-page > .grid.md\:grid-cols-4 > div:after { content: ''; position: absolute; right: -22px; bottom: -28px; width: 90px; height: 90px; border-radius: 50%; background: #eff6ff; }
        .leave-report-page > .grid.md\:grid-cols-4 > div:nth-child(1) { border-top: 4px solid #f59e0b; }
        .leave-report-page > .grid.md\:grid-cols-4 > div:nth-child(2) { border-top: 4px solid #10b981; }
        .leave-report-page > .grid.md\:grid-cols-4 > div:nth-child(3) { border-top: 4px solid #ef4444; }
        .leave-report-page > .grid.md\:grid-cols-4 > div:nth-child(4) { border-top: 4px solid #2563eb; }
        .leave-report-page > .grid.md\:grid-cols-4 > div > div:first-child { position: relative; z-index: 1; color: #64748b; font-size: 13px; font-weight: 700; }
        .leave-report-page > .grid.md\:grid-cols-4 > div > div:last-child { position: relative; z-index: 1; margin-top: 8px; color: #0f172a; font-size: 34px; line-height: 1; }
        .leave-report-page > a { display: inline-flex; align-items: center; gap: 8px; width: max-content; border-radius: 11px; background: #2563eb; padding: 11px 17px; font-weight: 700; box-shadow: 0 7px 16px rgba(37,99,235,.2); }
        .leave-report-page > a:before { content: '↓'; font-size: 18px; }
        .leave-report-page > .grid.lg\:grid-cols-3 { gap: 16px; }
        .leave-report-page > .grid.lg\:grid-cols-3 > div { min-height: 210px; border: 1px solid #dbe3f0; border-radius: 17px; padding: 0; overflow: hidden; box-shadow: 0 8px 22px rgba(15,23,42,.055); }
        .leave-report-page > .grid.lg\:grid-cols-3 > div h2 { margin: 0; padding: 16px 18px; border-bottom: 1px solid #e0e7ff; background: linear-gradient(110deg,#eff6ff,#fff); color: #172554; font-size: 15px; }
        .leave-report-page > .grid.lg\:grid-cols-3 > div h2:before { content: '•'; margin-right: 8px; color: #2563eb; font-size: 22px; vertical-align: -2px; }
        .leave-report-page > .grid.lg\:grid-cols-3 > div > div { margin: 0 18px; padding: 13px 0; border-color: #e2e8f0; color: #334155; font-size: 13px; }
        .leave-report-page > .grid.lg\:grid-cols-3 > div > div:last-child { border-bottom: 0; }
        @media (max-width: 640px) { .leave-report-page > form { align-items: stretch; flex-direction: column; } .leave-report-page > form:before { margin-left: 0; } .leave-report-page > form input, .leave-report-page > form button { width: 100%; } }
    </style>
    @endif
    <div class="flex flex-col gap-3 border-b border-slate-200 pb-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="mb-1 text-xs font-bold uppercase tracking-[.18em] text-blue-600">Quản trị phân hệ</p><h1 class="text-2xl font-extrabold tracking-tight text-slate-900">{{ $title }}</h1><p class="mt-1 text-sm text-slate-500">Theo dõi, xử lý và kiểm soát toàn bộ quy trình nghỉ phép.</p></div><a class="inline-flex items-center gap-2 self-start rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm transition hover:border-blue-300 hover:bg-blue-50 hover:text-blue-700 sm:self-auto" href="{{ route('leave-management.index') }}"><i class="bi bi-arrow-left"></i> Tổng quan</a></div>
    @if(session('success'))<div class="rounded bg-green-100 p-3 text-green-800">{{ session('success') }}</div>@endif

    @if($section === 'personnel')
        @include('leave-management::partials.personnel-create', ['users' => $users, 'units' => $units, 'objects' => $objects, 'positions' => $positions])
        <script>document.querySelectorAll('select[name="hometown"],select[name="permanent_residence"]').forEach(function(select){Array.from(select.options).forEach(function(option){if(option.value && !/\s[—–-]\s/.test(option.textContent))option.remove();});});</script>
        @include('leave-management::partials.personnel-detail-list')
    @endif
    @if($section === 'directory')
        @if($section === 'personnel')
            @include('leave-management::partials.personnel-create', ['users' => $users, 'units' => $units, 'objects' => $objects])
            <script>document.querySelectorAll('select[name="hometown"],select[name="permanent_residence"]').forEach(function(select){Array.from(select.options).forEach(function(option){if(option.value && !option.textContent.includes('—'))option.remove();});});</script>
            @include('leave-management::partials.personnel-detail-list')
        @endif
        <div class="overflow-x-auto rounded border bg-white"><table class="w-full text-left text-sm"><thead class="bg-slate-100"><tr><th class="p-3">Mã</th><th class="p-3">Họ tên</th><th class="p-3">Đơn vị</th><th class="p-3">Chức vụ / đối tượng</th><th class="p-3">{{ $section === 'directory' ? 'Ngày phép đã duyệt' : 'Email / thao tác' }}</th></tr></thead><tbody>@forelse($items as $item)<tr class="border-t"><td class="p-3">{{ $item->staff_code }}</td><td class="p-3 font-medium">{{ $item->name }}</td><td class="p-3">{{ $item->unitRelation?->name ?? $item->unit }}</td><td class="p-3">{{ $item->position }} / {{ $item->object_type }}</td><td class="p-3">@if($section === 'directory'){{ $item->approved_leave_days ?? 0 }}@else{{ $item->email }}<details><summary class="cursor-pointer text-xs text-blue-600">Sửa / xóa</summary><form method="POST" action="{{ route('leave-management.personnel.update',$item) }}" class="mt-1 flex flex-wrap gap-1">@csrf @method('PATCH')<input name="staff_code" value="{{ $item->staff_code }}" class="w-20 rounded border p-1"><input name="name" value="{{ $item->name }}" class="rounded border p-1"><input name="position" value="{{ $item->position }}" class="rounded border p-1"><input name="object_type" value="{{ $item->object_type }}" class="w-20 rounded border p-1"><button class="rounded bg-blue-600 px-2 py-1 text-xs text-white">Lưu</button></form><form method="POST" action="{{ route('leave-management.personnel.delete',$item) }}">@csrf @method('DELETE')<button class="text-xs text-red-600">Xóa</button></form></details>@endif</td></tr>@empty<tr><td colspan="5" class="p-6 text-center text-slate-500">Chưa có nhân sự quản lý phép.</td></tr>@endforelse</tbody></table></div>
    @elseif($section === 'classes')
        @php
            $units = $units->filter(fn($unit) => str_contains(mb_strtolower((string) $unit->name, 'UTF-8'), 'đại đội') && $unit->parent && str_contains(mb_strtolower((string) $unit->parent->name, 'UTF-8'), 'tiểu đoàn'))->values();
        @endphp
        <div class="mb-3 rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm text-blue-900"><i class="bi bi-info-circle mr-1"></i> Lớp do <strong>Đại đội</strong> quản lý. Đại đội phải thuộc một <strong>Tiểu đoàn</strong>.</div>
        <div class="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4"><div><h2 class="font-bold text-amber-900">Đồng bộ dữ liệu lớp / học viên</h2><p class="mt-1 text-sm text-amber-800">Chỉ chạy khi bấm nút; không tự động đồng bộ khi mở trang.</p></div><form method="POST" action="{{ route('leave-management.classes.sync') }}">@csrf<button class="rounded-lg bg-amber-600 px-4 py-2 font-bold text-white hover:bg-amber-700">Đồng bộ ngay</button></form></div>
        @include('leave-management::partials.classes-dashboard', ['units' => $units, 'items' => $items])
        @if(false)
        <form method="POST" action="{{ route('leave-management.classes.store') }}" class="flex flex-wrap gap-2 rounded border bg-white p-4">@csrf<select name="unit_id" required class="rounded border p-2"><option value="">Chọn đơn vị / đại đội</option>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->code }} — {{ $unit->name }}</option>@endforeach</select><input name="name" required placeholder="Tên lớp" class="rounded border p-2"><button class="rounded bg-blue-600 px-4 py-2 text-white">Thêm lớp</button></form><div class="rounded border bg-white p-4">@foreach($items as $item)<div class="flex justify-between border-b p-2"><span>{{ $item->unit?->name }} — {{ $item->name }}</span><form method="POST" action="{{ route('leave-management.classes.delete',$item) }}">@csrf @method('DELETE')<button class="text-red-600">Xóa</button></form></div>@endforeach</div>
        @endif
    @elseif($section === 'units')
        @include('leave-management::partials.units-actions', ['parents' => $parents])
        @if(false)
        <div class="rounded border bg-white p-4">@foreach($items as $item)<div class="flex justify-between border-b p-3"><span>{{ $item->code }} — {{ $item->name }}</span><span>{{ $item->instructors_count }} hồ sơ giảng viên</span></div>@endforeach</div>
        @endif
    @elseif($section === 'request-detail')
        @php
            $statusLabels=['PENDING'=>'Chờ gửi','PENDING_COMMANDER'=>'Chờ chỉ huy cơ quan','PENDING_AGENCY'=>'Chờ cơ quan cán bộ / Quân lực','APPROVED'=>'Đã duyệt','REJECTED'=>'Từ chối'];
        @endphp
        @if(in_array($request->status,['PENDING','DRAFT','PENDING_COMMANDER','PENDING_AGENCY'],true))
            @include('leave-management::partials.request-edit', ['request' => $request])
        @endif
        <div class="rounded border bg-white p-5"><div class="grid gap-3 md:grid-cols-3"><div><span class="text-slate-500">Nhân sự</span><p class="font-semibold">{{ $request->personnel?->name ?? $request->personnel_name }}</p></div><div><span class="text-slate-500">Người gửi</span><p>{{ $request->proposed_by_display_name ?? $request->proposed_by_username ?? '—' }}</p></div><div><span class="text-slate-500">Loại phép</span><p>{{ $request->leave_type }}</p></div><div><span class="text-slate-500">Trạng thái</span><p class="font-semibold">{{ $statusLabels[$request->status] ?? $request->status }}</p></div><div><span class="text-slate-500">Chỉ huy cơ quan</span><p>{{ $request->commander?->name ?? $request->commander_name ?? 'Chưa gán' }}</p></div><div><span class="text-slate-500">Thời gian</span><p>{{ $request->from_date?->format('d-m-Y') }} - {{ $request->to_date?->format('d-m-Y') }}</p></div><div><span class="text-slate-500">Số ngày</span><p>{{ $request->total_days }} (chuẩn {{ $request->base_days }}, đi đường {{ $request->travel_days }}, cộng {{ $request->extra_days }})</p></div><div><span class="text-slate-500">Địa phương</span><p>{{ $request->locality_path }}</p></div></div><div class="mt-4"><span class="text-slate-500">Lý do</span><p>{{ $request->reason }}</p></div></div>
        @if($request->status === 'PENDING_COMMANDER' && ((int) $request->commander_user_id === (int) auth()->id() || auth()->user()?->isSuperAdmin()))
            <div class="rounded border border-amber-200 bg-amber-50 p-5"><h2 class="font-semibold text-amber-900">Đề xuất đang chờ chỉ huy cơ quan xử lý</h2><form method="POST" action="{{ route('leave-management.requests.decide',$request) }}" class="mt-3 flex flex-wrap gap-2">@csrf @method('PATCH')<input name="decision_note" placeholder="Ghi chú xử lý" class="rounded border px-3 py-2"><button name="status" value="PENDING_AGENCY" class="rounded bg-emerald-600 px-3 py-2 font-semibold text-white">Duyệt và gửi cơ quan quản lý</button><button name="status" value="REJECTED" class="rounded bg-red-600 px-3 py-2 font-semibold text-white">Từ chối</button></form></div>
        @elseif($request->status === 'PENDING_AGENCY' && \Modules\LeaveManagement\Support\LeaveAccess::canHandleAgency((string) $request->managing_agency, auth()->user()))
            <div class="rounded border border-blue-200 bg-blue-50 p-5"><h2 class="font-semibold text-blue-900">Đề xuất đang chờ quân lực xử lý</h2><p class="mt-1 text-sm text-blue-800">Quân lực kiểm tra, in đơn trình Ban Giám hiệu ký, sau đó xác nhận duyệt cuối.</p><div class="mt-3 flex flex-wrap gap-2"><a target="_blank" href="{{ route('leave-management.requests.print',$request) }}" class="rounded border border-blue-300 bg-white px-3 py-2 font-semibold text-blue-700">In đơn trình BGH</a><form method="POST" action="{{ route('leave-management.requests.decide',$request) }}" class="flex flex-wrap gap-2">@csrf @method('PATCH')<input type="hidden" name="bgh_signed" value="1"><input name="bgh_note" required placeholder="Số/ngày văn bản BGH ký" class="rounded border px-3 py-2"><input name="decision_note" placeholder="Ghi chú duyệt" class="rounded border px-3 py-2"><button name="status" value="APPROVED" class="rounded bg-blue-600 px-3 py-2 font-semibold text-white">Đã ký BGH · Duyệt cuối</button><button name="status" value="REJECTED" class="rounded bg-red-600 px-3 py-2 font-semibold text-white">Từ chối</button></form></div></div>
        @endif
        <div class="rounded border bg-white p-5"><h2 class="mb-3 font-semibold">Nhật ký xử lý</h2>@forelse($audit as $item)<div class="border-b p-2">{{ $item->created_at?->format('d-m-Y H:i') }} — {{ $item->action }} — {{ $item->user?->name }}</div>@empty<p class="text-slate-500">Chưa có nhật ký.</p>@endforelse</div>
    @elseif($section === 'requests' || $section === 'approvals')
        @php
            $isCommanderPersonnel = $isCommanderPersonnel ?? (($militaryPersonnel ?? null) && \Illuminate\Support\Str::contains(\Illuminate\Support\Str::lower(\Illuminate\Support\Str::ascii((string) ($militaryPersonnel->position ?? ''))), 'chi huy'));
        @endphp
        @if($section === 'requests' && !$isCommanderPersonnel) @include('leave-management::partials.request-create', ['personnel' => $personnel, 'replacementPersonnel' => $replacementPersonnel, 'classes' => $classes, 'localities' => $localities, 'extraStandards' => $extraStandards, 'regulations' => $regulations]) @elseif($section === 'requests') <div class="rounded-xl border border-amber-200 bg-amber-50 p-5 text-amber-900"><p class="font-bold">Tài khoản chỉ huy cơ quan</p><p class="mt-1 text-sm">Tài khoản này chỉ thực hiện tiếp nhận và duyệt đề xuất phép, không được tự đề xuất phép.</p></div> @endif
        @include('leave-management::partials.multistage-approvals', ['items' => $items, 'section' => $section])
        <div class="overflow-x-auto rounded border bg-white"><table class="w-full text-left text-sm"><thead class="bg-slate-100"><tr><th class="p-3">Nhân sự</th><th class="p-3">Thời gian</th><th class="p-3">Loại phép</th><th class="p-3">Số ngày</th><th class="p-3">Trạng thái</th><th class="p-3">Thao tác</th></tr></thead><tbody>@forelse($items as $item)<tr class="border-t"><td class="p-3">{{ $item->personnel?->name }}</td><td class="p-3">{{ $item->from_date?->format('d/m/Y') }} - {{ $item->to_date?->format('d/m/Y') }}</td><td class="p-3">{{ $item->leave_type }}</td><td class="p-3">{{ $item->total_days }}</td><td class="p-3">{{ $item->status }}</td><td class="p-3">@if($item->status === 'PENDING')<form method="POST" action="{{ route('leave-management.requests.decide', $item) }}" class="flex gap-2">@csrf @method('PATCH')<input name="decision_note" placeholder="Ghi chú" class="w-32 rounded border px-2 py-1"><button name="status" value="APPROVED" class="rounded bg-green-600 px-2 py-1 text-white">Duyệt</button><button name="status" value="REJECTED" class="rounded bg-red-600 px-2 py-1 text-white">Từ chối</button></form>@else<span class="text-slate-500">Đã xử lý</span>@endif</td></tr>@empty<tr><td colspan="6" class="p-6 text-center text-slate-500">Không có đơn phép.</td></tr>@endforelse</tbody></table></div>
         <script>const requestTables=document.querySelectorAll('.overflow-x-auto table');if(requestTables.length)requestTables[requestTables.length-1].closest('.overflow-x-auto').style.display='none';</script>
        @php
            $leaveTypeLabels = ['ANNUAL' => 'Phép năm', 'EXTRA' => 'Phép thêm', 'SHORT_LEAVE' => 'Nghỉ ngắn ngày'];
            $leaveStatusLabels = ['PENDING' => 'Chờ gửi', 'DRAFT' => 'Bản nháp', 'PENDING_COMMANDER' => 'Chờ chỉ huy', 'PENDING_AGENCY' => 'Chờ cơ quan quản lý', 'APPROVED' => 'Đã duyệt', 'REJECTED' => 'Từ chối', 'CANCELLED' => 'Đã hủy'];
        @endphp
        <div class="mt-4 overflow-x-auto rounded border bg-white"><table class="w-full min-w-[900px] text-left text-sm"><thead class="bg-slate-100"><tr><th class="p-3">Quân nhân</th><th class="p-3">Loại</th><th class="p-3">Tổng ngày</th><th class="p-3">Nơi nghỉ</th><th class="p-3">Trạng thái</th><th class="p-3">Ngày tạo</th></tr></thead><tbody>@forelse($items as $item)<tr class="border-t"><td class="p-3 font-semibold">{{ $item->personnel?->name ?? $item->personnel_name }}</td><td class="p-3">{{ $leaveTypeLabels[$item->leave_type] ?? $item->leave_type }}</td><td class="p-3 font-bold">{{ $item->total_days }} ngày</td><td class="p-3">{{ $item->locality_path ?: '—' }}</td><td class="p-3">{{ $leaveStatusLabels[$item->status] ?? $item->status }}</td><td class="p-3">{{ $item->created_at?->format('d/m/Y H:i') }}</td></tr>@empty<tr><td colspan="6" class="p-6 text-center text-slate-500">Chưa có đơn phép.</td></tr>@endforelse</tbody></table></div>
     @elseif($section === 'regulations')
        <form method="POST" action="{{ route('leave-management.regulations.store') }}" class="grid gap-2 rounded border bg-white p-4 md:grid-cols-4">@csrf<input name="leave_type" value="ANNUAL" placeholder="Loại phép" class="rounded border p-2"><select name="object_type" class="rounded border p-2"><option value="">Mọi đối tượng</option>@foreach($objects as $object)<option value="{{ $object->code }}">{{ $object->name }}</option>@endforeach</select><input name="base_days" type="number" min="0" required placeholder="Số ngày chuẩn" class="rounded border p-2"><input name="label" placeholder="Tên quy định" class="rounded border p-2"><input name="min_years" type="number" min="0" placeholder="Từ năm công tác" class="rounded border p-2"><input name="max_years" type="number" min="0" placeholder="Đến năm công tác" class="rounded border p-2"><textarea name="description" placeholder="Mô tả" class="rounded border p-2 md:col-span-4"></textarea><button class="rounded bg-blue-600 px-4 py-2 text-white">Thêm quy định</button></form><div class="rounded border bg-white p-4">@foreach($items as $item)<div class="flex justify-between border-b p-2"><span>{{ $item->label }} — {{ $item->leave_type }} — {{ $item->object_type ?: 'Mọi đối tượng' }} — {{ $item->base_days }} ngày</span><div class="flex gap-2"><details><summary class="cursor-pointer text-blue-600">Sửa</summary><form method="POST" action="{{ route('leave-management.regulations.update',$item) }}" class="mt-1 flex gap-1">@csrf @method('PATCH')<input name="leave_type" value="{{ $item->leave_type }}" class="w-20 rounded border p-1"><input name="base_days" type="number" value="{{ $item->base_days }}" class="w-16 rounded border p-1"><input name="label" value="{{ $item->label }}" class="rounded border p-1"><button class="rounded bg-blue-600 px-2 py-1 text-white">Lưu</button></form></details><form method="POST" action="{{ route('leave-management.regulations.delete',$item) }}">@csrf @method('DELETE')<button class="text-red-600">Xóa</button></form></div></div>@endforeach</div>
    @elseif($section === 'localities')
        <div class="mb-3 flex justify-end"><form method="POST" action="{{ route('leave-management.localities.reset') }}" onsubmit="return confirm('Xóa toàn bộ danh mục địa phương để import lại? Thao tác này không thể hoàn tác.');">@csrf<button class="rounded-lg border border-rose-200 bg-white px-3 py-2 text-sm font-bold text-rose-600 hover:bg-rose-600 hover:text-white">Xóa toàn bộ địa phương</button></form></div>
        @php
            $items = $items->filter(fn($item) => strtoupper((string) $item->level) !== 'PROVINCE')->values();
        @endphp
        @include('leave-management::partials.locality-actions', ['items' => $items])
        <form method="POST" action="{{ route('leave-management.localities.store') }}" class="flex flex-wrap gap-2 rounded border bg-white p-4">@csrf<input name="name" required placeholder="Tên địa phương" class="rounded border p-2"><input name="level" required placeholder="Tỉnh/Huyện/Xã" class="rounded border p-2"><input name="code" placeholder="Mã" class="rounded border p-2"><button class="rounded bg-blue-600 px-4 py-2 text-white">Thêm</button></form><form method="POST" action="{{ route('leave-management.localities.import') }}" enctype="multipart/form-data" class="my-3 flex flex-wrap gap-2 rounded border bg-white p-3">@csrf<input name="file" type="file" accept=".xlsx,.xls,.csv,.txt" required class="rounded border px-2 py-1"><button class="rounded bg-slate-700 px-3 py-1 text-white">Import Excel/CSV</button></form>
    @elseif($section === 'positions')
        @include('leave-management::partials.position-actions', ['items' => $items])
        <form method="POST" action="{{ route('leave-management.positions.store') }}" class="rounded-2xl border border-blue-100 bg-gradient-to-r from-blue-50 to-white p-5 shadow-sm">@csrf<div class="mb-3"><h2 class="font-extrabold text-slate-900">Thêm chức vụ mới</h2><p class="mt-1 text-sm font-medium text-slate-500">Tên chức vụ sẽ được dùng trong hồ sơ nhân sự và quy trình nghỉ phép.</p></div><div class="grid gap-3 sm:grid-cols-[1fr_150px_auto]"><input name="name" required placeholder="Ví dụ: Chỉ huy, Trợ lý..." class="rounded-xl border px-3 py-2.5"><input name="sort_order" type="number" value="0" class="rounded-xl border px-3 py-2.5"><button class="rounded-xl bg-blue-700 px-5 py-2.5 font-bold text-white shadow-md shadow-blue-100 transition hover:bg-blue-800"><i class="bi bi-plus-lg mr-1"></i>Thêm chức vụ</button></div></form>
    @elseif($section === 'batches')
        @if(false)
        <form method="POST" action="{{ route('leave-management.batches.store') }}" class="grid gap-2 rounded border bg-white p-4 md:grid-cols-4">@csrf<select name="request_id" required class="rounded border p-2"><option value="">Đơn đã duyệt</option>@foreach($requests as $request)<option value="{{ $request->id }}">#{{ $request->id }} — {{ $request->leave_type }}</option>@endforeach</select><input name="label" required placeholder="Tên đợt nghỉ" class="rounded border p-2"><input name="start_date" type="date" required class="rounded border p-2"><input name="end_date" type="date" required class="rounded border p-2"><input name="total_days" type="number" min="1" required placeholder="Số ngày" class="rounded border p-2"><button class="rounded bg-blue-600 px-4 py-2 text-white">Tạo đợt nghỉ</button></form><div class="rounded border bg-white p-4">@foreach($items as $item)<div class="flex justify-between border-b p-2"><span>{{ $item->label }}: {{ $item->start_date?->format('d/m/Y') }} – {{ $item->end_date?->format('d/m/Y') }} ({{ $item->total_days }} ngày)</span><div class="flex gap-2"><form method="POST" action="{{ route('leave-management.batches.update',$item) }}">@csrf @method('PATCH')<input type="hidden" name="label" value="{{ $item->label }}"><input type="hidden" name="start_date" value="{{ $item->start_date?->format('Y-m-d') }}"><input type="hidden" name="end_date" value="{{ $item->end_date?->format('Y-m-d') }}"><input type="hidden" name="total_days" value="{{ $item->total_days }}"><button class="text-blue-600">Lưu lại</button></form><form method="POST" action="{{ route('leave-management.batches.delete',$item) }}">@csrf @method('DELETE')<button class="text-red-600">Xóa</button></form></div></div>@endforeach</div>
        @endif
        @include('leave-management::partials.batches-table', ['items' => $items])
    @elseif($section === 'records')
        @if(false)
        <div class="rounded border bg-white p-4">@foreach($items as $item)<div class="flex justify-between border-b p-2"><span>Đơn #{{ $item->request_id }} — {{ $item->leave_type }} — {{ $item->status }} — {{ $item->total_days }} ngày @if($item->archived_at)<small>(đã lưu trữ)</small>@endif</span>@if(!$item->archived_at)<form method="POST" action="{{ route('leave-management.records.archive',$item) }}">@csrf @method('PATCH')<button class="text-blue-600">Lưu trữ</button></form>@endif</div>@endforeach</div>
        @endif
        @include('leave-management::partials.records-table', ['items' => $items])
    @elseif($section === 'alerts')
        <div class="rounded border bg-white p-4">@forelse($items as $item)<div class="flex justify-between border-b p-3 {{ $item->read_at ? 'opacity-60' : '' }}"><div><div class="font-semibold">{{ $item->title }}</div><div class="text-sm text-slate-600">{{ $item->body }}</div><div class="text-xs text-slate-500">{{ $item->created_at?->format('d/m/Y H:i') }}</div></div>@if(!$item->read_at)<form method="POST" action="{{ route('leave-management.alerts.read',$item) }}">@csrf @method('PATCH')<button class="text-blue-600">Đã đọc</button></form>@endif</div>@empty<p class="text-slate-500">Không có thông báo.</p>@endforelse<div class="p-3">{{ $items->links() }}</div></div>
    @elseif($section === 'audit')
        <div class="overflow-x-auto rounded border bg-white"><table class="w-full text-left text-sm"><thead class="bg-slate-100"><tr><th class="p-3">Thời gian</th><th class="p-3">Người dùng</th><th class="p-3">Thao tác</th><th class="p-3">Đối tượng</th><th class="p-3">Chi tiết</th></tr></thead><tbody>@foreach($items as $item)<tr class="border-t"><td class="p-3">{{ $item->created_at?->format('d/m/Y H:i') }}</td><td class="p-3">{{ $item->user?->name ?? $item->user_id }}</td><td class="p-3">{{ $item->action }}</td><td class="p-3">{{ $item->entity_type }} #{{ $item->entity_id }}</td><td class="p-3">{{ json_encode($item->details,JSON_UNESCAPED_UNICODE) }}</td></tr>@endforeach</tbody></table></div>
    @elseif($section === 'mail')
        <form method="POST" action="{{ route('leave-management.mail.save') }}" class="grid gap-2 rounded border bg-white p-4 md:grid-cols-3">@csrf<input name="host" value="{{ $setting?->host }}" placeholder="SMTP host" class="rounded border p-2"><input name="port" value="{{ $setting?->port }}" type="number" placeholder="Port" class="rounded border p-2"><input name="username" value="{{ $setting?->username }}" type="email" placeholder="SMTP user" class="rounded border p-2"><input name="password" type="password" placeholder="Mật khẩu (để trống nếu giữ nguyên)" class="rounded border p-2"><input name="from_address" value="{{ $setting?->from_address }}" type="email" placeholder="Địa chỉ gửi" class="rounded border p-2"><input name="from_name" value="{{ $setting?->from_name }}" placeholder="Tên người gửi" class="rounded border p-2"><select name="encryption" class="rounded border p-2"><option value="tls">TLS</option><option value="ssl">SSL</option><option value="null">Không mã hóa</option></select><label class="flex items-center gap-2 p-2"><input name="dev_mode" type="checkbox" value="1" @checked($setting?->dev_mode)> Chế độ thử nghiệm</label><button class="rounded bg-blue-600 px-4 py-2 text-white">Lưu cấu hình email</button></form><form method="POST" action="{{ route('leave-management.mail.test') }}" class="my-4 flex gap-2 rounded border bg-white p-4">@csrf<input name="to" type="email" required placeholder="Email nhận kiểm tra" class="flex-1 rounded border p-2"><button class="rounded bg-slate-700 px-4 py-2 text-white">Gửi mail thử</button></form><div class="rounded border bg-white p-4"><h2 class="mb-2 font-semibold">Nhật ký gửi mail</h2>@forelse($logs as $log)<div class="border-b p-2">{{ $log->created_at?->format('d/m/Y H:i') }} — {{ $log->to_email }} — {{ $log->kind }} — {{ $log->ok ? 'OK' : 'Lỗi' }} @if($log->error)<span class="text-red-600">{{ $log->error }}</span>@endif</div>@empty<p>Chưa có nhật ký mail.</p>@endforelse</div>
    @elseif($section === 'reports')
        @include('leave-management::partials.report-links', ['year' => $year])
        <form class="flex gap-2"><input name="year" type="number" value="{{ $year }}" class="rounded border p-2"><button class="rounded bg-slate-700 px-3 py-2 text-white">Xem năm</button></form><div class="grid gap-4 md:grid-cols-4">@foreach([['Chờ duyệt',$pending],['Đã duyệt',$approved],['Từ chối',$rejected],['Tổng ngày phép',$days]] as $stat)<div class="rounded border bg-white p-5"><div class="text-sm text-slate-500">{{ $stat[0] }}</div><div class="text-3xl font-bold">{{ $stat[1] }}</div></div>@endforeach</div><a href="{{ route('leave-management.reports.word',['year'=>$year]) }}" class="inline-block rounded bg-blue-600 px-4 py-2 text-white">Xuất báo cáo Word</a><script>document.querySelectorAll('.grid.gap-4.lg\\:grid-cols-3').forEach(function(box){box.style.display='none';});</script>@include('leave-management::partials/report-tables', ['taken' => $taken, 'notYet' => $notYet, 'comparison' => $comparison, 'year' => $year])
    @endif
</div>
@endsection
