@extends('layouts.admin')
@section('title', 'Quy định về phép')
@section('page-title', 'Quy định về phép')
@section('content')
@include('partials.module-menu', ['module' => 'leave'])
<div class="space-y-5">
    <div><h1 class="text-2xl font-extrabold text-slate-900">Quy định về phép</h1><p class="mt-1 text-sm font-medium text-slate-500">Quản lý đối tượng, phép hàng năm, phép thêm và phép đặc biệt.</p></div>
    <nav class="flex flex-wrap gap-2 rounded-2xl border border-blue-100 bg-white p-2 shadow-sm">
        @foreach([['objects','Đối tượng'],['annual','Phép hàng năm'],['extra','Phép thêm'],['special','Phép đặc biệt']] as [$key,$label])<a href="{{ route('leave-management.regulations.dashboard',['tab'=>$key]) }}" class="rounded-xl px-4 py-2.5 text-sm font-extrabold {{ $tab === $key ? 'bg-blue-700 text-white shadow-md' : 'text-slate-700 hover:bg-blue-50 hover:text-blue-700' }}">{{ $label }}@if($key==='objects') ({{ $objects->count() }}) @endif</a>@endforeach
    </nav>

    @if($tab === 'objects')
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 bg-blue-50 px-5 py-4"><h2 class="font-extrabold text-slate-900">Danh mục đối tượng</h2><p class="mt-1 text-sm text-slate-600">Mã đối tượng và tên đối tượng áp dụng quy định phép.</p></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs font-extrabold text-slate-700"><tr><th class="px-5 py-3">Mã ĐT</th><th class="px-5 py-3">Tên ĐT</th><th class="px-5 py-3">Thứ tự</th><th class="px-5 py-3">Trạng thái</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($objects as $object)<tr><td class="px-5 py-3 font-bold text-blue-800">{{ $object->code }}</td><td class="px-5 py-3 font-semibold">{{ $object->name }}</td><td class="px-5 py-3">{{ $object->sort_order }}</td><td class="px-5 py-3"><span class="rounded-full bg-green-100 px-2 py-1 text-xs font-bold text-green-700">Hoạt động</span></td></tr>@empty<tr><td colspan="4" class="p-6 text-center text-slate-500">Chưa có đối tượng.</td></tr>@endforelse</tbody></table></div></section>
    @elseif($tab === 'annual' || $tab === 'extra')
        <form method="POST" action="{{ route('leave-management.regulations.store') }}" class="grid gap-3 rounded-2xl border border-blue-100 bg-gradient-to-r from-blue-50 to-white p-5 md:grid-cols-4">@csrf<input type="hidden" name="leave_type" value="{{ $tab === 'annual' ? 'ANNUAL' : 'EXTRA' }}"><select name="object_type" required class="rounded-xl border px-3 py-2.5"><option value="">Chọn đối tượng</option>@foreach($objects as $object)<option value="{{ $object->code }}">{{ $object->code }} — {{ $object->name }}</option>@endforeach</select><input name="min_years" type="number" min="0" placeholder="Từ năm công tác" class="rounded-xl border px-3 py-2.5"><input name="max_years" type="number" min="0" placeholder="Đến năm công tác" class="rounded-xl border px-3 py-2.5"><input name="base_days" type="number" min="0" required placeholder="Số ngày" class="rounded-xl border px-3 py-2.5"><input name="label" placeholder="Tên quy định" class="rounded-xl border px-3 py-2.5 md:col-span-2"><input name="description" placeholder="Mô tả" class="rounded-xl border px-3 py-2.5 md:col-span-2"><button class="rounded-xl bg-blue-700 px-4 py-2.5 font-bold text-white md:col-span-4">+ Thêm mức phép</button></form>
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-extrabold text-slate-900">{{ $tab === 'annual' ? 'Tiêu chuẩn phép hàng năm' : 'Tiêu chuẩn phép thêm' }}</h2></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs font-extrabold text-slate-700"><tr><th class="px-5 py-3">Đối tượng</th><th class="px-5 py-3">Thâm niên</th><th class="px-5 py-3">Số ngày</th><th class="px-5 py-3">Mô tả</th><th class="px-5 py-3">Thao tác</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($regulations->where('leave_type',$tab === 'annual' ? 'ANNUAL' : 'EXTRA') as $rule)<tr><td class="px-5 py-3 font-bold">{{ $objects->firstWhere('code',$rule->object_type)?->name ?? $rule->object_type }}</td><td class="px-5 py-3">{{ $rule->min_years ?? 0 }} – {{ $rule->max_years ?? 'trở lên' }} năm</td><td class="px-5 py-3 font-extrabold text-blue-700">{{ $rule->base_days }} ngày</td><td class="px-5 py-3 text-slate-600">{{ $rule->description ?: $rule->label }}</td><td class="px-5 py-3"><form method="POST" action="{{ route('leave-management.regulations.delete',$rule) }}">@csrf @method('DELETE')<button class="font-bold text-rose-600">Xóa</button></form></td></tr>@empty<tr><td colspan="5" class="p-6 text-center text-slate-500">Chưa có quy định.</td></tr>@endforelse</tbody></table></div></section>
    @else
        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-extrabold text-slate-900">Phép đặc biệt</h2><div class="mt-4 space-y-3 text-sm leading-6 text-slate-700"><p><strong>Đối tượng:</strong> Sĩ quan, QNCN, CNQP, VCQP (không áp dụng HSQBS / HV).</p><p><strong>Thời gian:</strong> Mỗi lần không quá <strong>10 ngày</strong>.</p><p class="font-bold">Được nghỉ phép đặc biệt khi:</p><ol class="list-decimal space-y-2 pl-6"><li>Bản thân kết hôn, hoặc con đẻ / con nuôi hợp pháp kết hôn.</li><li>Gia đình gặp khó khăn đột xuất do vợ hoặc chồng, con đẻ / con nuôi hợp pháp, bố mẹ / người nuôi dưỡng hợp pháp của bản thân, của vợ hoặc của chồng bị đau ốm nặng, tai nạn rủi ro, hy sinh, từ trần hoặc bị thiệt hại nặng nề về tài sản do thiên tai, hỏa hoạn, dịch bệnh nguy hiểm gây ra.</li></ol></div></section>
    @endif
</div>
@endsection
