<div class="rounded-2xl border border-slate-200 bg-white shadow-sm">
    <div class="flex flex-col gap-3 border-b border-slate-100 bg-gradient-to-r from-blue-50 to-white px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div class="flex items-center gap-3"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-700 text-white shadow-md shadow-blue-100"><i class="bi bi-person-vcard"></i></span><div><h2 class="text-lg font-extrabold text-slate-900">Danh sách chức vụ</h2><p class="text-sm font-medium text-slate-500">Quản lý tên gọi và thứ tự hiển thị trong hệ thống.</p></div></div><span class="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-800">{{ count($items) }} chức vụ</span></div>
    <div class="space-y-2 p-4">
        @forelse($items as $item)
            <div class="group flex flex-col gap-3 rounded-xl border border-slate-100 bg-slate-50/60 px-4 py-3 transition hover:border-blue-200 hover:bg-blue-50/50 sm:flex-row sm:items-center sm:justify-between"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-lg bg-white text-sm font-extrabold text-blue-700 shadow-sm">{{ $loop->iteration }}</span><div><p class="font-bold text-slate-800">{{ $item->name }}</p><p class="mt-0.5 text-xs font-medium text-slate-500">Thứ tự hiển thị: {{ $item->sort_order }}</p></div></div><div class="flex items-center gap-2"><details class="relative"><summary class="cursor-pointer list-none rounded-lg border border-blue-200 bg-white px-3 py-1.5 text-xs font-bold text-blue-700 transition hover:bg-blue-700 hover:text-white"><i class="bi bi-pencil-square mr-1"></i>Sửa</summary><div class="absolute right-0 z-20 mt-2 w-64 rounded-xl border border-slate-200 bg-white p-3 text-left shadow-xl"><form method="POST" action="{{ route('leave-management.positions.update',$item) }}" class="grid gap-2">@csrf @method('PATCH')<label class="text-xs font-bold text-slate-600">Tên chức vụ</label><input name="name" value="{{ $item->name }}" class="rounded-lg border px-2 py-1.5 text-sm"><label class="text-xs font-bold text-slate-600">Thứ tự</label><input name="sort_order" type="number" value="{{ $item->sort_order }}" class="rounded-lg border px-2 py-1.5 text-sm"><button class="rounded-lg bg-blue-700 px-3 py-2 text-sm font-bold text-white">Lưu thay đổi</button></form></div></details><form method="POST" action="{{ route('leave-management.positions.delete',$item) }}">@csrf @method('DELETE')<button class="rounded-lg border border-rose-200 bg-white px-3 py-1.5 text-xs font-bold text-rose-600 transition hover:bg-rose-600 hover:text-white">Xóa</button></form></div></div>
        @empty
            <div class="rounded-xl border border-dashed border-slate-300 px-5 py-10 text-center"><i class="bi bi-person-vcard text-3xl text-slate-300"></i><p class="mt-2 font-bold text-slate-700">Chưa có chức vụ</p><p class="mt-1 text-sm text-slate-500">Tạo chức vụ đầu tiên bằng biểu mẫu bên dưới.</p></div>
        @endforelse
    </div>
</div>
