@if(in_array($request->status,['PENDING','DRAFT','PENDING_COMMANDER','PENDING_AGENCY'],true))
    @php
        $selectedExtraIds = collect($request->extra_reasons ?? [])->pluck('id')->map(fn($id) => (int) $id)->all();
        $leaveTypeLabels = ['ANNUAL'=>'Phép hàng năm','EXTRA'=>'Phép thêm','SICK'=>'Nghỉ ốm','PERSONAL'=>'Nghỉ việc riêng','SHORT_LEAVE'=>'Nghỉ tranh thủ'];
    @endphp
    <section class="mt-4 overflow-visible rounded-2xl border border-blue-100 bg-white shadow-sm">
        <div class="border-b border-blue-100 bg-gradient-to-r from-blue-50 via-white to-sky-50 px-5 py-4">
            <h2 class="text-lg font-extrabold text-slate-900">Thông tin đề xuất</h2>
            <p class="mt-1 text-sm text-slate-500">Có thể chỉnh sửa các thông tin trước khi gửi lại biểu mẫu.</p>
        </div>
        <form method="POST" action="{{ route('leave-management.requests.update',$request) }}" class="grid gap-x-4 gap-y-3 p-4 md:grid-cols-2 md:p-5">
            @csrf @method('PATCH')<input type="hidden" name="extra_standard_ids_marker" value="1">
            <label class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Quân nhân</span><input value="{{ ($request->personnel?->staff_code ? $request->personnel->staff_code.' — ' : '').($request->personnel?->name ?? $request->personnel_name) }}" readonly class="w-full rounded-xl border-slate-200 bg-slate-50 px-3 py-2.5"></label>
            <label class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Người thay thế trong thời gian nghỉ</span><select name="replacement_personnel_id" class="w-full rounded-xl border-slate-200 px-3 py-2.5"><option value="">Chọn quân nhân thay thế...</option>@foreach($replacementPersonnel as $replacement)<option value="{{ $replacement->id }}" @selected((int)$request->replacement_personnel_id === (int)$replacement->id)>{{ $replacement->staff_code }} — {{ $replacement->name }}</option>@endforeach</select><span class="mt-1 block text-xs text-slate-500">Chỉ hiển thị quân nhân cùng đơn vị với người nghỉ.</span></label>
            <label class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Loại phép</span><select name="leave_type" class="w-full rounded-xl border-slate-200 px-3 py-2.5">@foreach($leaveTypeLabels as $value=>$label)<option value="{{ $value }}" @selected($request->leave_type === $value)>{{ $label }}</option>@endforeach</select></label>
            <label class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Ngày bắt đầu <b class="text-red-500">*</b></span><input name="from_date" type="date" required value="{{ $request->from_date?->format('Y-m-d') }}" class="w-full rounded-xl border-slate-200 px-3 py-2.5"></label>
            <label class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Ngày kết thúc <b class="text-red-500">*</b></span><input type="text" readonly value="{{ $request->to_date?->format('d/m/Y') }}" placeholder="Tự động tính ngày kết thúc" class="w-full rounded-xl border-slate-200 bg-slate-50 px-3 py-2.5"><span class="mt-1 block text-xs text-slate-500">Ngày kết thúc sẽ được cập nhật theo số ngày phép mới.</span></label>
            <label class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Ngày đi đường</span><input name="travel_days" type="number" min="0" value="{{ $request->travel_days ?? 0 }}" class="w-full rounded-xl border-slate-200 px-3 py-2.5"></label>
            <label class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Nơi nghỉ (phường / xã)</span><select name="locality_id" class="w-full rounded-xl border-slate-200 px-3 py-2.5"><option value="">Chọn phường / xã</option>@foreach($localities->whereNotNull('parent_id') as $locality)<option value="{{ $locality->id }}" @selected((int)$request->locality_id === (int)$locality->id)>{{ $locality->parent?->name }} — {{ $locality->name }}</option>@endforeach</select></label>
            <label class="block md:col-span-2"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Ghi chú / lý do nghỉ</span><textarea name="reason" rows="2" class="w-full rounded-xl border-slate-200 px-3 py-2.5" placeholder="Nhập lý do nghỉ...">{{ $request->reason }}</textarea></label>
            <div class="rounded-2xl border border-slate-200 bg-white p-3 md:col-span-2"><div class="mb-3 text-sm font-extrabold text-slate-800">Phép thêm</div><div class="space-y-2">@forelse($extraStandards as $standard)<label class="flex cursor-pointer items-start gap-3 rounded-lg border border-slate-200 p-3"><input type="checkbox" name="extra_standard_ids[]" value="{{ $standard->id }}" @checked(in_array((int)$standard->id,$selectedExtraIds,true)) class="mt-1 h-4 w-4 accent-blue-600"><span><span class="block font-semibold text-slate-700">{{ $standard->description ?: $standard->label }}</span><span class="mt-1 block text-xs text-slate-500">{{ $standard->base_days }} ngày</span></span></label>@empty<p class="text-sm text-slate-500">Chưa có tiêu chuẩn phép thêm.</p>@endforelse</div></div>
            <div class="rounded-lg border border-slate-200 bg-slate-100 px-4 py-3 text-sm font-bold text-slate-800 md:col-span-2">Tổng hiện tại: {{ $request->total_days }} ngày — Phép cơ bản: {{ $request->base_days }} ngày — Đi đường: {{ $request->travel_days ?? 0 }} ngày — Phép thêm: {{ $request->extra_days ?? 0 }} ngày</div>
            <div class="flex justify-end md:col-span-2"><button class="rounded-lg bg-blue-700 px-5 py-2.5 font-bold text-white hover:bg-blue-800">Cập nhật và gửi lại biểu mẫu</button></div>
        </form>
    </section>
@endif
