@can('leave-management.create')
@php($canProposeForUnit = auth()->user()?->isSuperAdmin() || auth()->user()?->can('leave-management.approvals.approve') || auth()->user()?->can('leave-management.approve'))
<section class="mb-5 overflow-hidden rounded-2xl border border-blue-100 bg-white shadow-sm">
    <div class="border-b border-blue-100 bg-gradient-to-r from-blue-50 via-white to-sky-50 px-5 py-4">
        <p class="text-xs font-bold uppercase tracking-[.16em] text-blue-600">Quy trình đề xuất</p>
        <h2 class="mt-1 text-lg font-extrabold text-slate-900">Đề xuất nghỉ phép</h2>
        <p class="mt-1 text-sm text-slate-500">Đại đội chọn đúng hình thức đề xuất: cả lớp, cá nhân hoặc nghỉ tranh thủ.</p>
    </div>
    <form id="leave-proposal-form" method="POST" action="{{ route('leave-management.requests.store') }}" class="grid gap-4 p-5 md:grid-cols-3">
        @csrf
        <label class="block md:col-span-3"><span class="mb-1.5 block text-sm font-bold text-slate-700">Hình thức đề xuất</span><select id="proposal-scope" name="request_scope" required class="w-full rounded-xl border-slate-200 px-3 py-2.5 shadow-sm">@if($canProposeForUnit)<option value="CLASS">Phép lớp — đại đội đề xuất cho toàn bộ học viên</option><option value="SHORT_LEAVE">Phép tranh thủ — đại đội tích chọn học viên</option>@endif<option value="PERSONAL">Phép cá nhân — một quân nhân</option></select></label>
        <label id="personnel-field" class="hidden block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Quân nhân</span><select id="proposal-personnel" name="personnel_id" class="w-full rounded-xl border-slate-200 px-3 py-2.5 shadow-sm"><option value="">Chọn quân nhân</option>@foreach($personnel as $person)<option value="{{ $person->id }}">{{ $person->staff_code }} — {{ $person->name }}</option>@endforeach</select></label>
        <label id="class-field" class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Lớp / đại đội <b class="text-red-500">*</b></span><select id="proposal-class" name="class_id" required class="w-full rounded-xl border-slate-200 px-3 py-2.5 shadow-sm"><option value="">Chọn lớp</option>@foreach($classes as $class)<option value="{{ $class->id }}" data-people='@json($class->personnel->map(fn($p)=>["id"=>$p->id,"name"=>$p->name,"code"=>$p->staff_code]))'>{{ $class->unit?->name }} — {{ $class->name }} ({{ $class->personnel->count() }} học viên)</option>@endforeach</select></label>
        <label id="leave-type-field" class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Loại phép</span><select id="proposal-leave-type" name="leave_type" class="w-full rounded-xl border-slate-200 px-3 py-2.5 shadow-sm"><option value="ANNUAL">Nghỉ phép năm</option><option value="SICK">Nghỉ ốm</option><option value="PERSONAL">Nghỉ việc riêng</option></select></label>
        <div id="short-people" class="hidden rounded-xl border border-blue-100 bg-blue-50/60 p-4 md:col-span-3"><div class="mb-3 flex items-center justify-between"><div><h3 class="font-bold text-slate-900">Danh sách học viên nghỉ tranh thủ</h3><p class="text-xs text-slate-500">Tích đúng những học viên được nghỉ từ tối thứ Sáu đến chiều Chủ nhật.</p></div><button type="button" id="check-all-short" class="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white">Tích tất cả</button></div><div id="short-people-list" class="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"></div></div>
        <label class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Từ ngày <b class="text-red-500">*</b></span><input id="proposal-from" name="from_date" type="date" required class="w-full rounded-xl border-slate-200 px-3 py-2.5 shadow-sm"></label>
        <label class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Đến ngày <b class="text-red-500">*</b></span><input id="proposal-to" name="to_date" type="date" required class="w-full rounded-xl border-slate-200 px-3 py-2.5 shadow-sm"></label>
        <label id="annual-fields" class="block"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Ngày đi đường</span><input id="proposal-travel" name="travel_days" type="number" min="0" value="0" class="w-full rounded-xl border-slate-200 px-3 py-2.5 shadow-sm"></label>
        <label class="block md:col-span-3"><span class="mb-1.5 block text-sm font-semibold text-slate-700">Lý do / ghi chú</span><textarea id="proposal-reason" name="reason" rows="2" class="w-full rounded-xl border-slate-200 px-3 py-2.5 shadow-sm" placeholder="Ví dụ: Nghỉ hè theo kế hoạch của lớp; việc riêng; ..."></textarea></label>
        <div class="rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm md:col-span-3"><b class="text-blue-800">Lưu ý:</b> Phép lớp tạo một đề xuất chung cho cả lớp. Phép tranh thủ tạo đề xuất riêng cho từng học viên được tích chọn và được hiển thị theo cuối tuần trên lịch.</div>
        <div class="flex justify-end md:col-span-3"><button class="rounded-xl bg-blue-600 px-5 py-2.5 font-bold text-white shadow-lg shadow-blue-200 hover:bg-blue-700"><i class="bi bi-send mr-1"></i> Gửi đề xuất</button></div>
    </form>
</section>
<script>
(()=>{const form=document.getElementById('leave-proposal-form'),scope=document.getElementById('proposal-scope'),cls=document.getElementById('proposal-class'),classField=document.getElementById('class-field'),personField=document.getElementById('personnel-field'),shortBox=document.getElementById('short-people'),shortList=document.getElementById('short-people-list'),typeField=document.getElementById('leave-type-field'),from=document.getElementById('proposal-from'),to=document.getElementById('proposal-to'),reason=document.getElementById('proposal-reason'),annual=document.getElementById('annual-fields');function selectedPeople(){const option=cls.options[cls.selectedIndex];try{return JSON.parse(option?.dataset.people||'[]')}catch(e){return[]}}function setWeekend(){if(scope.value!=='SHORT_LEAVE'||!from.value)return;const d=new Date(from.value+'T00:00:00'),fr=new Date(d);fr.setDate(d.getDate()+(5-d.getDay()+7)%7);from.value=fr.toISOString().slice(0,10);const su=new Date(fr);su.setDate(fr.getDate()+2);to.value=su.toISOString().slice(0,10)}function render(){const s=scope.value,isPersonal=s==='PERSONAL',isShort=s==='SHORT_LEAVE';classField.classList.toggle('hidden',isPersonal);personField.classList.toggle('hidden',!isPersonal);shortBox.classList.toggle('hidden',!isShort);typeField.classList.toggle('hidden',!isPersonal);annual.classList.toggle('hidden',!isPersonal);cls.required=!isPersonal;shortList.innerHTML='';if(isShort)selectedPeople().forEach(p=>{const label=document.createElement('label');label.className='flex items-center gap-2 rounded-lg bg-white p-3';label.innerHTML=`<input type="checkbox" name="personnel_ids[]" value="${p.id}" class="short-person h-4 w-4 accent-blue-600"><span class="font-semibold text-slate-700">${p.code||''} — ${p.name}</span>`;shortList.appendChild(label)});if(s==='CLASS'){reason.value='Nghỉ hè theo kế hoạch của lớp';reason.placeholder='Lý do lớp nghỉ';}else if(isShort){reason.value='';reason.placeholder='Ghi chú nghỉ tranh thủ (nếu có)';setWeekend()}else{reason.value='';reason.placeholder='Nhập lý do nghỉ cá nhân';}}document.getElementById('check-all-short').addEventListener('click',()=>document.querySelectorAll('.short-person').forEach(x=>x.checked=true));scope.addEventListener('change',render);cls.addEventListener('change',render);from.addEventListener('change',()=>{if(scope.value==='SHORT_LEAVE')setWeekend()});render()})();
</script>
@endcan
