@php($battalions = $parents->filter(fn ($unit) => str_contains(mb_strtolower((string) $unit->name, 'UTF-8'), 'tiểu đoàn')))
@php($managedClasses = \Modules\LeaveManagement\Models\LeaveClass::with('unit')->where('active', true)->whereIn('unit_id', $items->pluck('id'))->get()->groupBy('unit_id'))
<div class="space-y-5">
    <section class="rounded-2xl border border-blue-100 bg-gradient-to-r from-blue-50 to-white p-5 shadow-sm">
        <div class="mb-4 flex items-start gap-3"><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-700 text-xl text-white shadow-md"><i class="bi bi-diagram-3"></i></span><div><h2 class="text-lg font-extrabold text-slate-900">Thêm đơn vị</h2><p class="mt-1 text-sm font-medium text-slate-500">Có thể thêm Khoa, Phòng, Tiểu đoàn, Đại đội… theo đúng đơn vị cấp trên.</p></div></div>
        <form id="unit-create-form" method="POST" action="{{ route('leave-management.units.store') }}" class="grid gap-3 md:grid-cols-5">@csrf<label class="block"><span class="mb-1 block text-xs font-bold text-slate-600">Mã đơn vị</span><input name="code" required placeholder="Ví dụ: D1, K1" class="w-full rounded-xl border border-slate-200 px-3 py-2.5"></label><label class="block"><span class="mb-1 block text-xs font-bold text-slate-600">Tên đơn vị</span><input id="unit-name" name="name" required placeholder="Khoa / Phòng / Tiểu đoàn / Đại đội" class="w-full rounded-xl border border-slate-200 px-3 py-2.5"></label><label class="block"><span class="mb-1 block text-xs font-bold text-slate-600">Đơn vị cấp trên</span><select id="unit-parent" name="parent_id" class="w-full rounded-xl border border-slate-200 px-3 py-2.5"><option value="">Không chọn cấp trên</option>@foreach($parents as $parent)<option value="{{ $parent->id }}">{{ $parent->code }} — {{ $parent->name }}</option>@endforeach</select></label><label class="block"><span class="mb-1 block text-xs font-bold text-slate-600">Cấp đơn vị</span><input id="unit-level" name="level" type="number" min="1" value="2" class="w-full rounded-xl border border-slate-200 px-3 py-2.5"></label><input type="hidden" name="status" value="active"><button class="self-end rounded-xl bg-blue-700 px-4 py-2.5 font-bold text-white shadow-md shadow-blue-100 hover:bg-blue-800"><i class="bi bi-plus-lg mr-1"></i>Thêm đơn vị</button></form>
        <script>(function(){const n=document.getElementById('unit-name'),p=document.getElementById('unit-parent'),l=document.getElementById('unit-level');if(!n||!p||!l)return;function sync(){const company=/đại đội/i.test(n.value);p.required=company;if(company){const selected=p.options[p.selectedIndex];if(!selected||!/tiểu đoàn/i.test(selected.text)){p.value='';}Array.from(p.options).forEach(o=>{if(o.value)o.hidden=!/tiểu đoàn/i.test(o.text);});l.value=3;}else{Array.from(p.options).forEach(o=>o.hidden=false);if(!l.value||l.value==='3')l.value=2;}}n.addEventListener('input',sync);p.addEventListener('change',function(){if(/đại đội/i.test(n.value))l.value=3;});sync();})();</script>
    </section>
    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="mb-4 flex items-center justify-between"><div><h2 class="text-lg font-extrabold text-slate-900">Cây đơn vị quản lý phép</h2><p class="mt-1 text-sm text-slate-500">Quan hệ quản lý: Trường Cao đẳng → Tiểu đoàn → Đại đội → Lớp.</p></div><span class="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-blue-800">{{ $items->count() }} đơn vị · {{ $managedClasses->flatten()->count() }} lớp</span></div><div class="space-y-2">@include('leave-management::partials.unit-tree', ['nodes' => $items->whereNull('parent_id'), 'allUnits' => $items, 'managedClasses' => $managedClasses, 'depth' => 0])</div></section>
    <div class="flex flex-wrap gap-3"><form method="POST" action="{{ route('leave-management.units.import') }}" enctype="multipart/form-data" class="flex flex-wrap items-center gap-2 rounded-xl border border-slate-200 bg-white p-3 shadow-sm">@csrf<input name="file" type="file" accept=".xlsx,.xls,.csv" required class="rounded-lg border border-slate-200 p-2"><button class="rounded-lg bg-slate-700 px-3 py-2 text-sm font-bold text-white">Import đơn vị</button></form><form method="POST" action="{{ route('leave-management.units.seed') }}" class="rounded-xl border border-slate-200 bg-white p-3 shadow-sm">@csrf<button class="rounded-lg border px-3 py-2 text-sm font-bold text-slate-700">Đồng bộ đơn vị hệ thống</button></form></div>
</div>
