@extends('layouts.app')

@section('content')
<div class="mx-auto max-w-[1600px] space-y-5 px-4 py-6 sm:px-6 lg:px-8">
    <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-slate-600">Database Management Hub</p><h1 class="mt-1 text-2xl font-bold text-slate-900">Audit History</h1><p class="mt-1 text-sm text-slate-500">Lịch sử chỉnh sửa dữ liệu, mapping và truy vấn SQL chỉ đọc.</p></div><span class="rounded-xl bg-slate-200 px-4 py-2 text-sm font-semibold text-slate-700">AUDIT LOG</span></div>
    <form class="flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><select name="action" class="rounded-xl border border-slate-300 px-3 py-2 text-sm"><option value="">Tất cả thao tác</option><option value="update" @selected(request('action') === 'update')>Update dữ liệu</option><option value="sql_read" @selected(request('action') === 'sql_read')>SQL đọc</option></select><input name="table_name" value="{{ request('table_name') }}" placeholder="Tên bảng..." class="rounded-xl border border-slate-300 px-3 py-2 text-sm"><button class="rounded-xl bg-slate-800 px-4 py-2 text-sm font-semibold text-white">Lọc</button></form>
    <div class="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-4 py-3">Thời gian</th><th class="px-4 py-3">Người thao tác</th><th class="px-4 py-3">Hành động</th><th class="px-4 py-3">Đối tượng</th><th class="px-4 py-3">Chi tiết</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($audits as $audit)<tr class="align-top hover:bg-slate-50"><td class="whitespace-nowrap px-4 py-3 text-xs text-slate-500">{{ optional($audit->created_at)->format('d/m/Y H:i:s') }}</td><td class="px-4 py-3"><div class="font-semibold text-slate-800">{{ $audit->actor?->name ?? 'Đã xóa tài khoản' }}</div><div class="text-xs text-slate-500">{{ $audit->actor?->email }}</div></td><td class="px-4 py-3"><span class="rounded-full bg-blue-100 px-2.5 py-1 text-xs font-semibold text-blue-700">{{ $audit->action }}</span></td><td class="px-4 py-3 text-xs"><div>{{ $audit->table_name }}</div><div class="text-slate-500">{{ $audit->record_key ?? '—' }}</div></td><td class="max-w-xl px-4 py-3"><details><summary class="cursor-pointer text-xs font-semibold text-slate-600">Xem payload</summary><pre class="mt-2 max-h-40 overflow-auto rounded-lg bg-slate-950 p-3 text-[11px] text-emerald-300">{{ json_encode(['before' => $audit->before_values, 'after' => $audit->after_values], JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></details></td></tr>@empty<tr><td colspan="5" class="px-4 py-12 text-center text-slate-500">Chưa có audit log.</td></tr>@endforelse</tbody></table><div class="border-t border-slate-200 p-4">{{ $audits->links() }}</div></div>
</div>
@endsection
