@extends('layouts.app')

@section('content')
<div class="mx-auto max-w-[1300px] space-y-5 px-4 py-6 sm:px-6 lg:px-8">
    <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-600">Database Management Hub</p><h1 class="mt-1 text-2xl font-bold text-slate-900">Integrity Audit</h1><p class="mt-1 text-sm text-slate-500">Báo cáo dữ liệu có nguy cơ lệch liên kết. Không tự động sửa.</p></div><span class="rounded-xl bg-cyan-100 px-4 py-2 text-sm font-semibold text-cyan-800">READ ONLY</span></div>
    <div class="grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="text-xs uppercase text-slate-500">Tổng kiểm tra</div><div class="mt-2 text-3xl font-bold text-slate-900">{{ count($checks) }}</div></div><div class="rounded-2xl border border-red-200 bg-red-50 p-5 shadow-sm"><div class="text-xs uppercase text-red-700">Cần xử lý</div><div class="mt-2 text-3xl font-bold text-red-900">{{ collect($checks)->whereIn('severity', ['high','medium'])->sum('count') }}</div></div><div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 shadow-sm"><div class="text-xs uppercase text-emerald-700">Trạng thái</div><div class="mt-2 text-xl font-bold text-emerald-900">Đã quét</div></div></div>
    <div class="space-y-3">@forelse($checks as $check)<div class="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><h2 class="font-semibold text-slate-900">{{ $check['label'] }}</h2><p class="mt-1 text-xs text-slate-500">Mã kiểm tra: {{ $check['key'] }}</p></div><div class="flex items-center gap-3"><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $check['severity'] === 'high' ? 'bg-red-100 text-red-700' : ($check['severity'] === 'medium' ? 'bg-amber-100 text-amber-700' : 'bg-blue-100 text-blue-700') }}">{{ strtoupper($check['severity']) }}</span><strong class="text-xl text-slate-900">{{ $check['count'] }}</strong></div></div>@empty<div class="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-slate-500">Chưa có bảng cần kiểm tra.</div>@endforelse</div>
</div>
@endsection
