@extends('layouts.app')

@section('content')
<div class="mx-auto max-w-[1500px] space-y-5 px-4 py-6 sm:px-6 lg:px-8">
    <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-amber-600">Database Management Hub</p><h1 class="mt-1 text-2xl font-bold text-slate-900">Migration Designer</h1><p class="mt-1 text-sm text-slate-500">Workflow an toàn: validation → backup → publish → rollback.</p></div><span class="rounded-xl bg-amber-100 px-4 py-2 text-sm font-semibold text-amber-800">CONTROLLED RELEASE</span></div>
    <div class="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><span>SQL schema chỉ chạy qua deployment pipeline sau khi staging pass.</span><button id="create-migration-version" class="rounded-xl bg-amber-600 px-4 py-2 text-sm font-semibold text-white hover:bg-amber-700">Tạo version draft</button></div>
    @if($versions->isNotEmpty())
    <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold text-slate-900">Migration versions</h2><div class="mt-3 space-y-2">
    @foreach($versions as $version)
        <div class="rounded-xl border border-slate-200 p-3"><div class="flex flex-wrap items-center justify-between gap-3"><span class="text-xs"><strong>v{{ $version->version }}</strong> · {{ $version->status }} · checksum {{ substr($version->checksum, 0, 12) }}… @if($version->backup_reference) · backup {{ $version->backup_reference }} @endif</span><span class="flex flex-wrap gap-2">@if($version->status === 'draft')<button data-workflow-url="{{ route('database-management.migrations.validate', $version) }}" class="rounded-lg bg-blue-600 px-2 py-1 text-xs font-semibold text-white">Validate</button>@endif @if(in_array($version->status, ['draft','validated'], true))<button data-workflow-url="{{ route('database-management.migrations.backup', $version) }}" class="rounded-lg bg-indigo-600 px-2 py-1 text-xs font-semibold text-white">Backup</button><button data-workflow-url="{{ route('database-management.migrations.reject', $version) }}" class="rounded-lg bg-slate-600 px-2 py-1 text-xs font-semibold text-white">Reject</button>@endif @if($version->status === 'validated' && $version->backup_reference)<button data-workflow-url="{{ route('database-management.migrations.publish', $version) }}" class="rounded-lg bg-emerald-600 px-2 py-1 text-xs font-semibold text-white">Publish</button>@endif @if($version->status === 'published')<button data-workflow-url="{{ route('database-management.migrations.rollback', $version) }}" class="rounded-lg bg-red-600 px-2 py-1 text-xs font-semibold text-white">Rollback</button>@endif</span></div>@if($version->validation_report)<pre class="mt-2 overflow-auto rounded-lg bg-slate-950 p-3 text-[11px] text-emerald-300">{{ json_encode($version->validation_report, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre>@endif</div>
    @endforeach
    </div></div>
    @endif
    <div class="space-y-4">@forelse($proposals as $proposal)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold text-slate-900">{{ $proposal->name }}</h2><p class="mt-1 text-xs text-slate-500">{{ $proposal->source_table }}.{{ $proposal->source_field }} → {{ $proposal->target_table }}.{{ $proposal->target_field }}</p></div><span class="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-800">PROPOSED</span></div><pre class="mt-4 overflow-x-auto rounded-xl bg-slate-950 p-4 text-xs text-emerald-300">{{ $previews[$proposal->id] }}</pre></article>@empty<div class="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-slate-500">Chưa có Business Map ở trạng thái đề xuất.</div>@endforelse</div>
</div>
<script>
const workflowHeaders={'X-CSRF-TOKEN':'{{ csrf_token() }}','Accept':'application/json','X-Requested-With':'XMLHttpRequest'};
async function workflow(url){const response=await fetch(url,{method:'POST',headers:workflowHeaders});const payload=await response.json().catch(()=>({}));if(!response.ok){window.Notify?.error?.(payload.message||'Workflow thất bại.');return;}window.location.reload();}
document.getElementById('create-migration-version')?.addEventListener('click',()=>workflow('{{ route('database-management.migrations.versions.store') }}'));
document.querySelectorAll('[data-workflow-url]').forEach((button)=>button.addEventListener('click',()=>workflow(button.dataset.workflowUrl)));
</script>
@endsection
