@extends('layouts.app')

@section('content')
<div class="mx-auto max-w-[1600px] space-y-5 px-4 py-6 sm:px-6 lg:px-8">
    <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-rose-600">Database Management Hub</p><h1 class="mt-1 text-2xl font-bold text-slate-900">SQL Console</h1><p class="mt-1 text-sm text-slate-500">Sprint 31 — chỉ truy vấn đọc, mỗi câu lệnh được ghi vào audit log.</p></div><span class="rounded-xl bg-rose-100 px-4 py-2 text-sm font-semibold text-rose-800">READ ONLY SQL</span></div>
    <form method="post" action="{{ route('database-management.sql.execute') }}" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">@csrf<textarea name="query" rows="7" required placeholder="SELECT * FROM users LIMIT 50" class="w-full rounded-xl border border-slate-300 bg-slate-950 p-4 font-mono text-sm text-emerald-300 outline-none focus:ring-2 focus:ring-rose-500">{{ old('query', $query ?? '') }}</textarea><div class="mt-3 flex flex-wrap items-center justify-between gap-3"><p class="text-xs text-slate-500">Cho phép SELECT, WITH, SHOW, DESCRIBE, EXPLAIN. Không cho INSERT/UPDATE/DELETE/ALTER/DROP.</p><button class="rounded-xl bg-rose-600 px-5 py-2 text-sm font-semibold text-white hover:bg-rose-700">Chạy truy vấn đọc</button></div></form>
    @if(isset($result))<div class="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 p-4 text-sm font-semibold text-slate-800">{{ count($result) }} dòng trả về</div>@if(count($result))<table class="min-w-full text-left text-xs"><thead class="bg-slate-50 text-slate-500"><tr>@foreach(array_keys((array) $result[0]) as $column)<th class="px-3 py-3">{{ $column }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-100">@foreach($result as $row)<tr>@foreach((array) $row as $value)<td class="max-w-sm px-3 py-2 align-top">{{ is_scalar($value) || $value === null ? (string) $value : json_encode($value, JSON_UNESCAPED_UNICODE) }}</td>@endforeach</tr>@endforeach</tbody></table>@else<div class="p-8 text-center text-slate-500">Không có dòng dữ liệu.</div>@endif</div>@endif
</div>
@endsection
