<div class="space-y-4">
    <div class="flex items-center justify-between rounded border bg-white p-4"><div><p class="text-xs uppercase text-slate-500">{{ $isRoot ? 'Ngành vật tư' : 'Loại vật tư thuộc ngành '.$category->parent?->code }}</p><h2 class="text-xl font-bold">{{ $category->code }} — {{ $category->name }}</h2></div><a href="{{ route('inventory.category') }}" class="rounded border px-3 py-2">Quay lại cây ngành</a></div>
    @if($isRoot)
        <form method="POST" action="{{ route('inventory.category.store') }}" class="grid gap-3 rounded border bg-white p-4 md:grid-cols-3">@csrf<input type="hidden" name="parent_id" value="{{ $category->id }}"><h2 class="md:col-span-3 font-semibold">Thêm loại vật tư thuộc {{ $category->code }}</h2><input name="name" required placeholder="Tên loại vật tư" class="rounded border p-2 md:col-span-2"><button class="rounded bg-blue-600 px-4 py-2 text-white">Thêm loại — tự sinh mã</button><p class="text-xs text-slate-500 md:col-span-3">Mã được sinh tuần tự theo ngành: {{ $category->code }}01, {{ $category->code }}02...</p></form>
        <div class="overflow-x-auto rounded border bg-white p-4"><h2 class="mb-3 font-semibold">Các loại vật tư trong ngành</h2><table class="w-full text-left text-sm"><thead class="bg-slate-100"><tr><th class="p-3">STT</th><th class="p-3">Mã loại</th><th class="p-3">Tên loại</th><th class="p-3">Số vật tư</th><th class="p-3">Thao tác</th></tr></thead><tbody>@forelse($category->children as $i=>$type)<tr class="border-t"><td class="p-3">{{ $i+1 }}</td><td class="p-3 font-semibold">{{ $type->code }}</td><td class="p-3">{{ $type->name }}</td><td class="p-3">{{ $type->materials_count }}</td><td class="p-3"><a href="{{ route('inventory.category.show',$type) }}" class="text-blue-600">Xem chi tiết loại</a></td></tr>@empty<tr><td colspan="5" class="p-4 text-center text-slate-500">Ngành chưa có loại vật tư.</td></tr>@endforelse</tbody></table></div>
    @else
        <div class="grid gap-4 lg:grid-cols-2"><form method="POST" action="{{ route('inventory.store') }}" class="grid gap-3 rounded border bg-white p-4 md:grid-cols-2">@csrf<input type="hidden" name="category_id" value="{{ $category->id }}"><h2 class="font-semibold md:col-span-2">Thêm vật tư vào {{ $category->code }}</h2><input name="code" required placeholder="Mã vật tư" class="rounded border p-2"><input name="name" required placeholder="Tên vật tư" class="rounded border p-2"><input name="unit" required value="cái" placeholder="Đơn vị tính" class="rounded border p-2"><input name="quantity" type="number" min="0" step=".01" value="0" placeholder="Số lượng" class="rounded border p-2"><input name="manufacture_year" type="number" placeholder="Năm sản xuất" class="rounded border p-2"><input name="usage_year" type="number" placeholder="Năm sử dụng" class="rounded border p-2"><input name="classification" placeholder="Phân cấp" class="rounded border p-2"><input name="status" value="ACTIVE" placeholder="Trạng thái" class="rounded border p-2"><label class="text-sm">Ngày mua<input name="purchase_date" type="date" class="mt-1 w-full rounded border p-2"></label><label class="text-sm">Ngày hết hạn bảo hành<input name="expiry_date" type="date" class="mt-1 w-full rounded border p-2"></label><button class="rounded bg-blue-600 px-4 py-2 text-white md:col-span-2">Thêm vật tư</button></form><form method="POST" action="{{ route('inventory.import') }}" enctype="multipart/form-data" class="rounded border bg-white p-4">@csrf<input type="hidden" name="category_id" value="{{ $category->id }}"><h2 class="mb-3 font-semibold">Import vật tư vào {{ $category->code }}</h2><p class="mb-3 text-sm text-slate-500">Tất cả dòng import sẽ thuộc loại vật tư này.</p><input name="file" type="file" accept=".xlsx,.xls,.csv" required class="w-full rounded border p-2"><div class="mt-3 flex gap-2"><button class="rounded bg-slate-700 px-4 py-2 text-white">Import</button><a href="{{ route('inventory.import.template') }}" class="rounded border px-4 py-2">Tải mẫu</a></div></form></div>
        <div class="overflow-x-auto rounded border bg-white p-4"><h2 class="mb-3 font-semibold">Vật tư thuộc {{ $category->code }} — {{ $category->name }}</h2><table class="w-full min-w-[1100px] text-left text-sm"><thead class="bg-slate-100"><tr><th class="p-3">STT</th><th class="p-3">Mã</th><th class="p-3">Tên</th><th class="p-3">Đơn vị</th><th class="p-3">Số lượng</th><th class="p-3">Năm SX</th><th class="p-3">Năm SD</th><th class="p-3">Phân cấp</th><th class="p-3">Trạng thái</th><th class="p-3">Ngày mua</th><th class="p-3">HSD bảo hành</th></tr></thead><tbody>@forelse($category->materials as $i=>$material)<tr class="border-t"><td class="p-3">{{ $i+1 }}</td><td class="p-3">{{ $material->code }}</td><td class="p-3 font-semibold">{{ $material->name }}</td><td class="p-3">{{ $material->unit }}</td><td class="p-3">{{ $material->quantity }}</td><td class="p-3">{{ $material->manufacture_year ?: '—' }}</td><td class="p-3">{{ $material->usage_year ?: '—' }}</td><td class="p-3">{{ $material->classification ?: '—' }}</td><td class="p-3">{{ $material->status ?: '—' }}</td><td class="p-3">{{ $material->purchase_date?->format('d/m/Y') ?: '—' }}</td><td class="p-3">{{ $material->expiry_date?->format('d/m/Y') ?: '—' }}</td></tr>@empty<tr><td colspan="11" class="p-4 text-center text-slate-500">Loại vật tư chưa có vật tư.</td></tr>@endforelse</tbody></table></div>
    @endif
</div>
