<div class="space-y-4">
    <form method="GET" action="{{ route('inventory.reports') }}" class="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-5">
        <input type="date" name="from" value="{{ $from }}" class="rounded-lg border px-3 py-2.5" aria-label="Từ ngày">
        <input type="date" name="to" value="{{ $to }}" class="rounded-lg border px-3 py-2.5" aria-label="Đến ngày">
        <select name="category_id" class="rounded-lg border px-3 py-2.5"><option value="">Ngành vật tư</option>@foreach($categories as $item)<option value="{{ $item->id }}" @selected(request('category_id')==$item->id)>{{ $item->name }}</option>@endforeach</select>
        <select name="building_id" class="rounded-lg border px-3 py-2.5"><option value="">Tòa nhà</option>@foreach($buildings as $item)<option value="{{ $item->id }}" @selected(request('building_id')==$item->id)>{{ $item->name }}</option>@endforeach</select>
        <select name="classroom_id" class="rounded-lg border px-3 py-2.5"><option value="">Phòng</option>@foreach($classrooms as $item)<option value="{{ $item->id }}" @selected(request('classroom_id')==$item->id)>{{ $item->name }}</option>@endforeach</select>
        <input name="search" value="{{ request('search') }}" placeholder="Tên hoặc mã vật tư" class="rounded-lg border px-3 py-2.5 md:col-span-2">
        <button class="rounded-lg bg-slate-900 px-4 py-2.5 font-bold text-white">Lọc báo cáo</button>
    </form>
    <div class="flex flex-wrap gap-2 rounded-2xl border bg-white p-2">@foreach([['summary','Thống kê'],['broken','Hỏng và đang sửa'],['warehouse','Kho vật tư'],['expiry','Sắp hết hạn'],['repairs','Lịch sử sửa chữa'],['logs','Nhật ký cập nhật']] as [$key,$label])<button type="button" class="report-tab rounded-lg px-4 py-2 text-sm font-bold {{ $loop->first?'bg-slate-900 text-white':'text-slate-600' }}" data-report-tab="{{ $key }}">{{ $label }}</button>@endforeach</div>
    <section data-report-panel="summary" class="report-panel rounded-2xl border bg-white p-5"><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach([['Tổng bản ghi vật tư',$stats['records']],['Tổng số lượng',number_format($stats['quantity'],2,',','.')],['Số nhóm',$stats['groups']],['Số tòa có vật tư',$stats['buildings']]] as [$label,$value])<div class="rounded-xl bg-slate-50 p-4"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-extrabold text-slate-900">{{ $value }}</p></div>@endforeach</div><div class="mt-5 grid gap-4 lg:grid-cols-2"><div><h3 class="mb-2 font-bold">Theo trạng thái</h3><p class="border-b p-2">Bình thường: {{ $stats['normal'] }}</p><p class="border-b p-2">Hỏng / đang sửa: {{ $stats['broken'] }}</p></div><div><h3 class="mb-2 font-bold">Theo loại vật tư</h3>@foreach($materials->groupBy(fn($m)=>$m->category?->name ?: 'Chưa phân loại') as $name=>$items)<p class="border-b p-2">{{ $name }}: {{ $items->count() }} bản ghi</p>@endforeach</div></div></section>
    <section data-report-panel="broken" class="report-panel hidden rounded-2xl border bg-white p-5"><h2 class="mb-3 text-lg font-bold">Hỏng và đang sửa</h2><div class="grid gap-4 lg:grid-cols-2"><div><h3 class="mb-2 font-semibold">Nhật ký vật tư hỏng cần sửa chữa</h3>@forelse($brokenLogs as $log)<p class="border-b p-2 text-sm">{{ $log->event_at?->format('d/m/Y H:i') }} — {{ $log->asset_code }} — {{ $log->asset_name }} — {{ $log->reason }}</p>@empty<p class="text-slate-500">Chưa có nhật ký.</p>@endforelse</div><div><h3 class="mb-2 font-semibold">Phiếu báo cáo hỏng</h3>@forelse($repairs as $repair)<p class="border-b p-2 text-sm">{{ $repair->asset?->asset_code }} — {{ $repair->content }} — {{ $repair->status==='COMPLETED'?'Đã hoàn thành':($repair->status==='CANCELLED'?'Đã hủy':'Đang xử lý') }}</p>@empty<p class="text-slate-500">Chưa có phiếu.</p>@endforelse</div></div><div class="mt-5"><h3 class="mb-2 font-semibold">Hiện trạng vật tư hỏng / đang sửa chữa</h3>@foreach($assets->whereIn('status',['BROKEN','REPAIRING']) as $asset)<p class="border-b p-2 text-sm">{{ $asset->asset_code }} — {{ $asset->name }} — {{ $asset->status==='BROKEN'?'Hỏng':'Đang sửa chữa' }}</p>@endforeach</div></section>
    <section data-report-panel="warehouse" class="report-panel hidden rounded-2xl border bg-white p-5"><h2 class="mb-3 text-lg font-bold">Kho vật tư</h2><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach([['Vật tư cấp 1–4',$assets->whereIn('grade',[1,2,3,4])->sum('quantity')],['Số loại cấp 1–4',$assets->whereIn('grade',[1,2,3,4])->count()],['Tổng vật tư hỏng cấp 5',$assets->where('grade',5)->sum('quantity')],['Vật tư hỏng / đang sửa',$assets->whereIn('status',['BROKEN','REPAIRING'])->sum('quantity')]] as [$label,$value])<div class="rounded-xl bg-slate-50 p-4"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-2 text-2xl font-bold">{{ number_format($value,2,',','.') }}</p></div>@endforeach</div></section>
    <section data-report-panel="expiry" class="report-panel hidden rounded-2xl border bg-white p-5"><form method="GET" class="mb-4 flex flex-wrap items-end gap-3"><input type="hidden" name="tab" value="expiry"><label class="text-sm font-semibold">Sắp hết hạn trong (tháng)<input type="number" name="months" min="1" max="60" value="{{ $months }}" class="mt-1 block rounded-lg border px-3 py-2.5"></label><button class="rounded-lg bg-slate-900 px-4 py-2.5 font-bold text-white">Xem</button></form>@forelse($expiringAssets as $asset)<p class="border-b p-2">{{ $asset->code }} — {{ $asset->name }} — Hết hạn: {{ $asset->expiry_date?->format('d/m/Y') }}</p>@empty<p class="text-slate-500">Không có vật tư sắp hết hạn.</p>@endforelse</section>
    <section data-report-panel="repairs" class="report-panel hidden rounded-2xl border bg-white p-5"><form method="GET" class="mb-4 flex flex-wrap items-end gap-3"><label class="text-sm font-semibold">Từ ngày<input type="date" name="from" value="{{ $from }}" class="mt-1 block rounded-lg border px-3 py-2.5"></label><label class="text-sm font-semibold">Đến ngày<input type="date" name="to" value="{{ $to }}" class="mt-1 block rounded-lg border px-3 py-2.5"></label><button class="rounded-lg bg-slate-900 px-4 py-2.5 font-bold text-white">Lọc lịch sử</button></form>@forelse($repairs as $repair)<p class="border-b p-2">{{ $repair->opened_at?->format('d/m/Y') }} — {{ $repair->asset?->asset_code }} — {{ $repair->content }} — {{ $repair->status }}</p>@empty<p class="text-slate-500">Chưa có lịch sử sửa chữa.</p>@endforelse</section>
    <section data-report-panel="logs" class="report-panel hidden overflow-x-auto rounded-2xl border bg-white p-5"><h2 class="mb-3 text-lg font-bold">Nhật ký cập nhật vật tư</h2><table class="w-full min-w-[900px] text-left text-sm"><thead class="bg-slate-50"><tr><th class="p-2">Thời gian</th><th class="p-2">Thao tác</th><th class="p-2">Đối tượng</th><th class="p-2">Người thực hiện</th><th class="p-2">Chi tiết</th></tr></thead><tbody>@forelse($auditLogs as $log)<tr class="border-t"><td class="p-2">{{ $log->created_at?->format('d/m/Y H:i') }}</td><td class="p-2">{{ ['INCREASE'=>'Tăng','DECREASE'=>'Giảm','ADJUST'=>'Điều chỉnh','TRANSFER'=>'Điều động','RECALL'=>'Thu hồi'][$log->action] ?? $log->action }}</td><td class="p-2">{{ $log->entity_type }} #{{ $log->entity_id }}</td><td class="p-2">{{ $log->user?->name }}</td><td class="p-2">{{ collect($log->details ?? [])->filter(fn($v)=>is_scalar($v))->map(fn($v)=>$v)->implode(' — ') }}</td></tr>@empty<tr><td colspan="5" class="p-6 text-center text-slate-500">Chưa có nhật ký cập nhật.</td></tr>@endforelse</tbody></table></section>
    <script>document.querySelectorAll('.report-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.report-tab').forEach(x=>x.classList.toggle('bg-slate-900',x===tab));document.querySelectorAll('.report-tab').forEach(x=>x.classList.toggle('text-white',x===tab));document.querySelectorAll('.report-panel').forEach(x=>x.classList.toggle('hidden',x.dataset.reportPanel!==tab.dataset.reportTab))}));</script>
</div>
