@php
    $stableAssets = ($assets ?? collect())->filter(fn ($asset) => $asset->status === 'NORMAL' && (float) $asset->quantity > 0)->values();
    $brokenAssets = ($assets ?? collect())->filter(fn ($asset) => in_array($asset->status, ['BROKEN', 'REPAIRING'], true) || (float) $asset->broken_quantity > 0)->values();
@endphp
<section class="space-y-4" data-room-assets>
    <div class="rounded-lg border bg-slate-50 p-3">
        <h3 class="mb-3 font-semibold">Thêm vật tư có sẵn vào phòng</h3>
        <form method="POST" action="{{ route('inventory.room.assets.store', $classroom) }}" class="grid gap-3 md:grid-cols-4">
            @csrf
            <label class="text-sm font-semibold md:col-span-2">Vật tư trong bảng vật tư<select name="material_id" required class="mt-1 w-full rounded border p-2"><option value="">Chọn vật tư có sẵn</option>@foreach(($materials ?? collect()) as $material)<option value="{{ $material->id }}" data-quantity="{{ (int) $material->quantity }}">{{ $material->code }} — {{ $material->name }} (tồn {{ $material->quantity }} {{ $material->unit }})</option>@endforeach</select></label>
            <label class="text-sm font-semibold">Số lượng<input name="quantity" type="number" min="1" step="1" value="1" required class="mt-1 w-full rounded border p-2"></label>
            <label class="text-sm font-semibold">Đơn vị quản lý<select name="holding_unit_id" class="mt-1 w-full rounded border p-2"><option value="">Theo đơn vị quản lý phòng</option>@foreach(($units ?? collect()) as $unit)<option value="{{ $unit->id }}" @selected((int) old('holding_unit_id', $classroom->managing_unit_id) === (int) $unit->id)>{{ $unit->name }}</option>@endforeach</select></label>
            <button class="w-fit rounded bg-blue-600 px-4 py-2 text-white">Thêm vào phòng</button>
        </form>
    </div>
    <div class="rounded-lg border bg-white p-3">
        <h3 class="mb-3 font-semibold">Import vật tư có sẵn vào phòng</h3>
        <form method="POST" action="{{ route('inventory.room.assets.import', $classroom) }}" enctype="multipart/form-data" class="flex flex-wrap items-end gap-3">
            @csrf
            <label class="text-sm font-semibold">Tệp CSV/XLSX<input name="file" type="file" accept=".csv,.xlsx,.xls" required class="mt-1 block rounded border p-2"></label>
            <label class="text-sm font-semibold">Đơn vị quản lý<select name="holding_unit_id" class="mt-1 w-full rounded border p-2"><option value="">Theo đơn vị quản lý phòng</option>@foreach(($units ?? collect()) as $unit)<option value="{{ $unit->id }}" @selected((int) old('holding_unit_id', $classroom->managing_unit_id) === (int) $unit->id)>{{ $unit->name }}</option>@endforeach</select></label>
            <button class="rounded border border-blue-600 px-4 py-2 text-blue-700">Import vào phòng</button>
            <span class="text-xs text-slate-500">Cột bắt buộc: code, quantity</span>
        </form>
    </div>

    <div class="rounded-lg border bg-white p-3">
        <div class="mb-3 flex items-center justify-between gap-3">
            <h3 class="font-semibold">Vật tư ổn định trong phòng</h3>
            <span class="text-sm text-slate-500">{{ $stableAssets->count() }} dòng</span>
        </div>
        <table class="w-full min-w-[1100px] text-left text-sm"><thead class="bg-slate-100"><tr><th class="p-2">Mã vật tư</th><th class="p-2">Tên vật tư</th><th class="p-2">Loại vật tư</th><th class="p-2">Số lượng ổn định</th><th class="p-2">Đơn vị quản lý</th><th class="p-2">Phân cấp</th><th class="p-2">Trạng thái</th><th class="p-2">Thao tác</th></tr></thead><tbody>
    @forelse($stableAssets as $asset)
        <tr class="border-t align-top"><td class="p-2">{{ $asset->asset_code }}</td><td class="p-2">{{ $asset->name }}</td><td class="p-2">{{ $asset->material?->category?->parent?->name ? $asset->material->category->parent->name.' / ' : '' }}{{ $asset->material?->category?->name ?: $asset->category ?: '—' }}</td><td class="p-2">{{ $asset->quantity }} {{ $asset->unit }}</td><td class="p-2">{{ $asset->holdingUnit?->name ?: '—' }}</td><td class="p-2">Cấp {{ $asset->grade ?: '—' }}</td><td class="p-2">{{ ['NORMAL'=>'Bình thường','BROKEN'=>'Hỏng','REPAIRING'=>'Đang sửa','LIQUIDATED'=>'Đã thanh lý'][$asset->status] ?? $asset->status }}</td><td class="relative p-2"><details class="relative inline-block" data-room-asset-edit><summary class="cursor-pointer rounded bg-blue-600 px-3 py-1.5 text-xs font-bold text-white">Sửa</summary><form method="POST" action="{{ route('inventory.room.assets.update', [$classroom, $asset]) }}" data-floating-room-asset-edit class="fixed z-[9999] grid max-h-[70vh] w-64 gap-2 overflow-y-auto rounded border bg-slate-50 p-3 shadow-2xl" style="top:0;left:0;z-index:9999">@csrf @method('PATCH')<label class="text-xs font-semibold">Số lượng<input name="quantity" type="number" min=".01" step=".01" value="{{ $asset->quantity }}" required class="mt-1 w-full rounded border p-1.5"></label><label class="text-xs font-semibold">Đơn vị quản lý<select name="holding_unit_id" class="mt-1 w-full rounded border p-1.5"><option value="">Theo đơn vị quản lý phòng</option>@foreach(($units ?? collect()) as $unit)<option value="{{ $unit->id }}" @selected((int) old('holding_unit_id', $asset->holding_unit_id ?: $classroom->managing_unit_id) === (int) $unit->id)>{{ $unit->name }}</option>@endforeach</select></label><label class="text-xs font-semibold">Phân cấp<select name="grade" class="mt-1 w-full rounded border p-1.5">@for($grade=1;$grade<=5;$grade++)<option value="{{ $grade }}" @selected($asset->grade == $grade)>Cấp {{ $grade }}</option>@endfor</select></label><label class="text-xs font-semibold">Trạng thái<select name="status" class="mt-1 w-full rounded border p-1.5"><option value="NORMAL" @selected($asset->status==='NORMAL')>Bình thường</option><option value="BROKEN" @selected($asset->status==='BROKEN')>Hỏng</option><option value="REPAIRING" @selected($asset->status==='REPAIRING')>Đang sửa</option><option value="LIQUIDATED" @selected($asset->status==='LIQUIDATED')>Đã thanh lý</option></select></label><button class="rounded bg-emerald-600 px-3 py-1.5 text-white">Lưu sửa</button></form></details><form method="POST" action="{{ route('inventory.room.assets.delete', [$classroom, $asset]) }}" class="mt-2" onsubmit="return confirm('Xóa vật tư này khỏi phòng?')">@csrf @method('DELETE')<button class="rounded bg-rose-600 px-3 py-1.5 text-xs font-bold text-white">Xóa</button></form></td></tr>
    @empty
        <tr><td colspan="8" class="p-4 text-center text-slate-500">Chưa có vật tư ổn định.</td></tr>
    @endforelse
        </tbody></table>
    </div>

    <div class="rounded-lg border border-rose-100 bg-rose-50 p-3">
        <div class="mb-3 flex items-center justify-between gap-3">
            <h3 class="font-semibold text-rose-900">Vật tư hỏng / đang sửa</h3>
            <span class="text-sm text-rose-700">{{ $brokenAssets->count() }} dòng</span>
        </div>
        <table class="w-full min-w-[1100px] text-left text-sm"><thead class="bg-rose-100 text-rose-950"><tr><th class="p-2">Mã vật tư</th><th class="p-2">Tên vật tư</th><th class="p-2">Loại vật tư</th><th class="p-2">Số lượng hỏng</th><th class="p-2">Đơn vị quản lý</th><th class="p-2">Phân cấp</th><th class="p-2">Trạng thái</th><th class="p-2">Thao tác</th></tr></thead><tbody>
    @forelse($brokenAssets as $asset)
        <tr class="border-t border-rose-100 align-top"><td class="p-2">{{ $asset->asset_code }}</td><td class="p-2">{{ $asset->name }}</td><td class="p-2">{{ $asset->material?->category?->parent?->name ? $asset->material->category->parent->name.' / ' : '' }}{{ $asset->material?->category?->name ?: $asset->category ?: '—' }}</td><td class="p-2">{{ $asset->broken_quantity ?: $asset->quantity }} {{ $asset->unit }}</td><td class="p-2">{{ $asset->holdingUnit?->name ?: '—' }}</td><td class="p-2 font-semibold text-rose-800">Cấp {{ $asset->grade ?: 5 }}</td><td class="p-2">{{ ['NORMAL'=>'Bình thường','BROKEN'=>'Hỏng','REPAIRING'=>'Đang sửa','LIQUIDATED'=>'Đã thanh lý'][$asset->status] ?? $asset->status }}</td><td class="relative p-2"><details class="relative inline-block" data-room-asset-edit><summary class="cursor-pointer rounded bg-blue-600 px-3 py-1.5 text-xs font-bold text-white">Sửa</summary><form method="POST" action="{{ route('inventory.room.assets.update', [$classroom, $asset]) }}" data-floating-room-asset-edit class="fixed z-[9999] grid max-h-[70vh] w-64 gap-2 overflow-y-auto rounded border bg-slate-50 p-3 shadow-2xl" style="top:0;left:0;z-index:9999">@csrf @method('PATCH')<label class="text-xs font-semibold">Số lượng<input name="quantity" type="number" min=".01" step=".01" value="{{ $asset->quantity }}" required class="mt-1 w-full rounded border p-1.5"></label><label class="text-xs font-semibold">Đơn vị quản lý<select name="holding_unit_id" class="mt-1 w-full rounded border p-1.5"><option value="">Theo đơn vị quản lý phòng</option>@foreach(($units ?? collect()) as $unit)<option value="{{ $unit->id }}" @selected((int) old('holding_unit_id', $asset->holding_unit_id ?: $classroom->managing_unit_id) === (int) $unit->id)>{{ $unit->name }}</option>@endforeach</select></label><label class="text-xs font-semibold">Phân cấp<select name="grade" class="mt-1 w-full rounded border p-1.5">@for($grade=1;$grade<=5;$grade++)<option value="{{ $grade }}" @selected($asset->grade == $grade)>Cấp {{ $grade }}</option>@endfor</select></label><label class="text-xs font-semibold">Trạng thái<select name="status" class="mt-1 w-full rounded border p-1.5"><option value="NORMAL" @selected($asset->status==='NORMAL')>Bình thường</option><option value="BROKEN" @selected($asset->status==='BROKEN')>Hỏng</option><option value="REPAIRING" @selected($asset->status==='REPAIRING')>Đang sửa</option><option value="LIQUIDATED" @selected($asset->status==='LIQUIDATED')>Đã thanh lý</option></select></label><button class="rounded bg-emerald-600 px-3 py-1.5 text-white">Lưu sửa</button></form></details><form method="POST" action="{{ route('inventory.room.assets.delete', [$classroom, $asset]) }}" class="mt-2" onsubmit="return confirm('Xóa vật tư này khỏi phòng?')">@csrf @method('DELETE')<button class="rounded bg-rose-600 px-3 py-1.5 text-xs font-bold text-white">Xóa</button></form></td></tr>
    @empty
        <tr><td colspan="8" class="p-4 text-center text-rose-700">Chưa có vật tư hỏng.</td></tr>
    @endforelse
        </tbody></table>
    </div>
    <script>document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('form[action*="/vat-tu/phong/"][action*="/vat-tu"]').forEach(function(form){const material=form.querySelector('select[name="material_id"]'),quantity=form.querySelector('input[name="quantity"]');if(!material||!quantity)return;const sync=function(){const max=parseInt(material.selectedOptions[0]?.dataset.quantity||'0',10);quantity.max=max||'';if(max&&parseInt(quantity.value||'0',10)>max)quantity.value=max;};material.addEventListener('change',sync);sync();});const place=function(details){const summary=details.querySelector('summary'),panel=details.querySelector('[data-floating-room-asset-edit]');if(!summary||!panel||!details.open)return;const rect=summary.getBoundingClientRect(),width=panel.offsetWidth||256,height=panel.offsetHeight||320,gap=8;let left=Math.min(window.innerWidth-width-gap,Math.max(gap,rect.right-width));let top=rect.top-height-gap;if(top<gap)top=Math.min(window.innerHeight-height-gap,rect.bottom+gap);panel.style.left=left+'px';panel.style.top=Math.max(gap,top)+'px';};document.querySelectorAll('[data-room-asset-edit]').forEach(function(details){details.addEventListener('toggle',function(){if(details.open){document.querySelectorAll('[data-room-asset-edit]').forEach(function(other){if(other!==details)other.removeAttribute('open');});requestAnimationFrame(function(){place(details);});}});});window.addEventListener('scroll',function(){document.querySelectorAll('[data-room-asset-edit][open]').forEach(place);},true);window.addEventListener('resize',function(){document.querySelectorAll('[data-room-asset-edit][open]').forEach(place);});});</script>
</section>
