<div class="space-y-4">
    <div class="flex flex-wrap justify-end gap-2"><button type="button" id="template-default" class="rounded-lg border px-4 py-2 text-sm">↻ Mặc định</button><button type="submit" form="word-template-form" class="rounded-lg border px-4 py-2 text-sm">▣ Lưu mẫu</button></div>
    <form id="word-template-form" method="POST" action="{{ route('inventory.templates.store') }}" enctype="multipart/form-data" class="space-y-4">@csrf<input type="hidden" name="code" value="bao-cao-vat-tu"><input type="hidden" name="name" value="Mẫu báo cáo vật tư"><input type="hidden" name="description" id="template-description">
        <section class="rounded-2xl border p-4"><h2 class="font-bold">Đầu trang (xem trước)</h2><p class="mt-1 text-sm text-slate-500">Giống khung 2 cột thể hiện trên file Word</p><div class="mt-4 rounded-xl border p-4 text-center text-xs"><div class="grid grid-cols-2 gap-4 font-bold"><div id="preview-left">TỔNG CỤC HẬU CẦN<br>TRƯỜNG CAO ĐẲNG HẬU CẦN 2<br><span class="font-normal">Số: ....../....../BC-CDHC</span></div><div id="preview-right">CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM<br>Độc lập - Tự do - Hạnh phúc<br><span class="font-normal italic">Thành phố Hồ Chí Minh, ngày ... tháng ... năm ...</span></div></div></div></section>
        <section class="rounded-2xl border p-4"><h2 class="mb-4 font-bold">Sửa đầu trang</h2><div class="grid gap-3 md:grid-cols-2"><label class="text-sm font-semibold">Dòng 1 trái (cấp trên)<input name="header_left_1" value="TỔNG CỤC HẬU CẦN" class="mt-1 block w-full rounded-lg border px-3 py-2.5"></label><label class="text-sm font-semibold">Dòng 2 trái (trường / đơn vị)<input name="header_left_2" value="TRƯỜNG CAO ĐẲNG HẬU CẦN 2" class="mt-1 block w-full rounded-lg border px-3 py-2.5"></label><label class="text-sm font-semibold">Số hiệu văn bản<input name="document_number" value="....../....../BC-CDHC" class="mt-1 block w-full rounded-lg border px-3 py-2.5"></label><label class="text-sm font-semibold">Địa danh (phần ghi ngày xuất)<input name="document_place" value="Thành phố Hồ Chí Minh" class="mt-1 block w-full rounded-lg border px-3 py-2.5"></label><label class="text-sm font-semibold md:col-span-2">Quốc hiệu<input name="national_title" value="CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM" class="mt-1 block w-full rounded-lg border px-3 py-2.5"></label><label class="text-sm font-semibold md:col-span-2">Tiêu ngữ<input name="national_motto" value="Độc lập - Tự do - Hạnh phúc" class="mt-1 block w-full rounded-lg border px-3 py-2.5"></label></div></section>
        <section class="rounded-2xl border p-4"><h2 class="font-bold">Cuối trang (xem trước)</h2><div class="mt-4 rounded-xl border p-4 text-xs"><div class="grid grid-cols-2 gap-4"><div><b id="preview-recipient-title">Nơi nhận:</b><div id="preview-recipients">- Như trên;<br>- Lưu: VT, HC;</div></div><div class="text-center font-bold">CHỈ HUY ĐƠN VỊ<br><span class="font-normal italic">(Ký, ghi rõ họ tên, cấp bậc)</span><br><br>........................</div></div></div></section>
        <section class="rounded-2xl border p-4"><h2 class="mb-4 font-bold">Sửa cuối trang</h2><div class="grid gap-3 md:grid-cols-2"><label class="text-sm font-semibold">Tiêu đề “Nơi nhận”<input name="recipient_title" value="Nơi nhận:" class="mt-1 block w-full rounded-lg border px-3 py-2.5"></label><label class="text-sm font-semibold">Chức danh ký<input name="sign_title" value="CHỈ HUY ĐƠN VỊ" class="mt-1 block w-full rounded-lg border px-3 py-2.5"></label><label class="text-sm font-semibold md:col-span-2">Danh sách nơi nhận (mỗi dòng một mục)<textarea name="recipients" rows="3" class="mt-1 block w-full rounded-lg border px-3 py-2.5">- Như trên;
- Lưu: VT, HC;</textarea></label><label class="text-sm font-semibold md:col-span-2">Gợi ý dưới chức danh<textarea name="sign_hint" rows="2" class="mt-1 block w-full rounded-lg border px-3 py-2.5">(Ký, ghi rõ họ tên, cấp bậc)</textarea></label><label class="text-sm font-semibold">Cấp bậc (tùy chọn)<input name="sign_rank" placeholder="vd. Trung tá" class="mt-1 block w-full rounded-lg border px-3 py-2.5"></label><label class="text-sm font-semibold">Họ tên người ký (tùy chọn)<input name="signer_name" placeholder="Trống = in chấm ......" class="mt-1 block w-full rounded-lg border px-3 py-2.5"></label></div></section>
    </form>
    <p class="text-xs text-slate-500">Mẫu lưu trên trình duyệt; xuất Word báo cáo sẽ dùng mẫu đã lưu.</p>
</div>
<script>document.getElementById('template-default')?.addEventListener('click',()=>document.getElementById('word-template-form')?.reset());document.getElementById('word-template-form')?.addEventListener('submit',()=>{const f=document.getElementById('word-template-form');const data={};f.querySelectorAll('[name]').forEach(x=>{if(x.name!=='_token'&&x.name!=='code'&&x.name!=='name'&&x.name!=='description')data[x.name]=x.value});document.getElementById('template-description').value=JSON.stringify(data)});</script>
