<div class="space-y-4">
    <div class="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-5"><div><h2 class="text-xl font-bold">Chi tiết phiếu #{{ $transfer->id }}</h2><p class="mt-1 text-sm text-slate-500">{{ $transfer->type === 'RECALL' ? 'Thu hồi' : 'Điều động' }}</p></div><a href="{{ route('inventory.transfers') }}" class="rounded border px-4 py-2">Quay lại danh sách</a></div>
    <div class="rounded-xl border bg-white p-5"><h3 class="mb-4 text-lg font-bold">Thông tin vật tư</h3><div class="grid gap-4 md:grid-cols-4"><div><b>Vật tư</b><p>{{ $transfer->asset?->asset_code }} — {{ $transfer->asset?->name }}</p></div><div><b>Số lượng</b><p>{{ (int)($transfer->quantity ?: 1) }} {{ $transfer->asset?->unit }}</p></div><div><b>Phòng nguồn</b><p>{{ $transfer->fromClassroom?->name ?: '—' }}</p></div><div><b>Phòng đích / kho</b><p>{{ $transfer->type === 'RECALL' ? ($transfer->warehouse?->name ?: 'Kho vật tư') : ($transfer->toClassroom?->name ?: '—') }}</p></div><div><b>Đơn vị quản lý đích</b><p>{{ $transfer->using_unit ?: '—' }}</p></div><div><b>Trạng thái phiếu</b><p>{{ ['PENDING'=>'Chờ duyệt','APPROVED'=>'Đã duyệt','REJECTED'=>'Từ chối','COMPLETED'=>'Đã hoàn thành'][$transfer->status] ?? $transfer->status }}</p></div></div></div>
    <form method="POST" action="{{ route('inventory.transfers.update',$transfer) }}" class="rounded-xl border bg-white p-5">@csrf @method('PATCH')<h3 class="mb-4 text-lg font-bold">Thông tin quyết định</h3><div class="grid gap-4 md:grid-cols-2"><label class="text-sm font-semibold">Theo đề nghị của đồng chí Trưởng: *<input name="requesting_unit" required value="{{ $transfer->requesting_unit }}" class="mt-1 w-full rounded-lg border p-2.5" placeholder="Nhập họ tên/chức vụ Trưởng đơn vị"></label><label class="text-sm font-semibold">Đơn vị gọi giao *<select name="performing_unit" required class="mt-1 w-full rounded-lg border p-2.5"><option value="">Chọn đơn vị gọi giao</option>@foreach($units ?? [] as $unit)<option value="{{ $unit->name }}" @selected($transfer->performing_unit === $unit->name)>{{ $unit->name }}</option>@endforeach</select></label><label class="text-sm font-semibold">Ngày quyết định<input name="decision_date" type="date" value="{{ $transfer->decision_date?->format('Y-m-d') }}" class="mt-1 w-full rounded-lg border p-2.5"></label><label class="text-sm font-semibold">Số quyết định<input name="decision_number" value="{{ $transfer->decision_number }}" class="mt-1 w-full rounded-lg border p-2.5"></label><label class="text-sm font-semibold">Người ký<input name="signer" value="{{ $transfer->signer }}" class="mt-1 w-full rounded-lg border p-2.5"></label><label class="text-sm font-semibold">Đơn vị quản lý đích<input name="using_unit" value="{{ $transfer->using_unit }}" class="mt-1 w-full rounded-lg border p-2.5"></label><label class="text-sm font-semibold md:col-span-2">Ghi chú<textarea name="general_note" class="mt-1 w-full rounded-lg border p-2.5">{{ $transfer->general_note }}</textarea></label></div><button type="submit" name="print" value="1" class="mt-4 rounded bg-blue-600 px-5 py-2.5 font-semibold text-white">In</button></form>
    <div class="flex flex-wrap items-center gap-2 rounded-xl border bg-white p-5"><a href="{{ route('inventory.transfers.word',$transfer) }}" class="rounded bg-blue-600 px-5 py-2.5 font-semibold text-white">In quyết định Word</a>@if($transfer->is_printed && $transfer->status === 'PENDING')<form method="POST" action="{{ route('inventory.transfers.decide',$transfer) }}">@csrf @method('PATCH')<button name="status" value="APPROVED" class="rounded bg-emerald-600 px-5 py-2.5 font-semibold text-white">Duyệt</button></form><form method="POST" action="{{ route('inventory.transfers.decide',$transfer) }}">@csrf @method('PATCH')<button name="status" value="REJECTED" class="rounded bg-rose-600 px-5 py-2.5 font-semibold text-white">Từ chối</button></form>@elseif(!$transfer->is_printed && $transfer->status === 'PENDING')<span class="text-sm text-amber-700">Lưu thông tin rồi in quyết định trước khi duyệt.</span>@elseif($transfer->is_printed && $transfer->status === 'APPROVED')<form method="POST" action="{{ route('inventory.transfers.decide',$transfer) }}">@csrf @method('PATCH')<button name="status" value="COMPLETED" class="rounded bg-indigo-600 px-5 py-2.5 font-semibold text-white">Hoàn thành</button></form>@endif</div>
</div>
@if(!$transfer->is_printed && $transfer->status === 'PENDING')
<div id="transfer-approval-after-print" class="hidden flex justify-end gap-2">
    <form method="POST" action="{{ route('inventory.transfers.decide',$transfer) }}">@csrf @method('PATCH')<button name="status" value="APPROVED" class="rounded bg-emerald-600 px-5 py-2.5 font-semibold text-white">Duyệt</button></form>
<form method="POST" action="{{ route('inventory.transfers.decide',$transfer) }}" class="flex flex-col gap-2"><textarea name="decision_note" required minlength="3" rows="2" class="rounded border p-2 text-sm" placeholder="Nhập lý do từ chối..."></textarea>@csrf @method('PATCH')<button name="status" value="REJECTED" class="rounded bg-rose-600 px-5 py-2.5 font-semibold text-white">Từ chối</button></form>
</div>
<script>document.addEventListener('DOMContentLoaded',()=>{const printForm=document.querySelector('form[action*="/update"]'),actions=document.getElementById('transfer-approval-after-print');printForm?.addEventListener('submit',()=>setTimeout(()=>actions?.classList.remove('hidden'),800));});</script>
@endif
<script>document.addEventListener('DOMContentLoaded',()=>{const button=document.querySelector('a[href*="/word"]');if(button)button.style.display='none';});</script>
